#ifndef FLASHPLAYER_GAMESWF_COMPAT_TU_CONFIG_H
#define FLASHPLAYER_GAMESWF_COMPAT_TU_CONFIG_H

#include_next "base/tu_config.h"

#undef TU_USE_SDL
#undef TU_USE_OPENAL

#undef TU_CONFIG_LINK_TO_THREAD
#define TU_CONFIG_LINK_TO_THREAD 0

#undef TU_CONFIG_LINK_TO_JPEGLIB
#define TU_CONFIG_LINK_TO_JPEGLIB 0

#undef TU_CONFIG_LINK_TO_ZLIB
#define TU_CONFIG_LINK_TO_ZLIB 0

#undef TU_CONFIG_LINK_TO_LIBPNG
#define TU_CONFIG_LINK_TO_LIBPNG 0

#undef TU_CONFIG_LINK_TO_FFMPEG
#define TU_CONFIG_LINK_TO_FFMPEG 0

#undef TU_CONFIG_LINK_TO_FREETYPE
#define TU_CONFIG_LINK_TO_FREETYPE 0

#undef TU_CONFIG_VERBOSE
#define TU_CONFIG_VERBOSE 0

#endif
