/home/david/Documents/RockBox_Personal-master/tools/ios/OpenLaraCompact/.theos/obj/armv7/../../../apps/plugins/openlara/fixed/common.cpp.03636c61.o: \
  ../../../apps/plugins/openlara/fixed/common.cpp \
  /home/david/theos/Prefix.pch \
  ../../../apps/plugins/openlara/fixed/common.h \
  ../../../apps/plugins/openlara/fixed/lang/en.h

/home/david/theos/Prefix.pch:

../../../apps/plugins/openlara/fixed/common.h:

../../../apps/plugins/openlara/fixed/lang/en.h:
