#define BMPHEIGHT_minishcap_room_links_house_bedroom 160
#define BMPWIDTH_minishcap_room_links_house_bedroom 240
extern const unsigned short minishcap_room_links_house_bedroom[];
extern const struct bitmap bm_minishcap_room_links_house_bedroom;
