/* Generated by tools/configure_nano.py; Nano-only optional features. */
#pragma once

static inline uint8_t Nano_GameInteractor_NoUIActive(void) {  return 0; }
#define GameInteractor_NoUIActive Nano_GameInteractor_NoUIActive
static inline GILinkSize Nano_GameInteractor_GetLinkSize(void) {  return GI_LINK_SIZE_NORMAL; }
#define GameInteractor_GetLinkSize Nano_GameInteractor_GetLinkSize
static inline void Nano_GameInteractor_SetLinkSize(GILinkSize size) { (void)size; }
#define GameInteractor_SetLinkSize Nano_GameInteractor_SetLinkSize
static inline uint8_t Nano_GameInteractor_InvisibleLinkActive(void) {  return 0; }
#define GameInteractor_InvisibleLinkActive Nano_GameInteractor_InvisibleLinkActive
static inline uint8_t Nano_GameInteractor_OneHitKOActive(void) {  return 0; }
#define GameInteractor_OneHitKOActive Nano_GameInteractor_OneHitKOActive
static inline uint8_t Nano_GameInteractor_PacifistModeActive(void) {  return 0; }
#define GameInteractor_PacifistModeActive Nano_GameInteractor_PacifistModeActive
static inline uint8_t Nano_GameInteractor_DisableZTargetingActive(void) {  return 0; }
#define GameInteractor_DisableZTargetingActive Nano_GameInteractor_DisableZTargetingActive
static inline uint8_t Nano_GameInteractor_ReverseControlsActive(void) {  return 0; }
#define GameInteractor_ReverseControlsActive Nano_GameInteractor_ReverseControlsActive
static inline int32_t Nano_GameInteractor_DefenseModifier(void) {  return 0; }
#define GameInteractor_DefenseModifier Nano_GameInteractor_DefenseModifier
static inline float Nano_GameInteractor_MovementSpeedMultiplier(void) {  return 1.0f; }
#define GameInteractor_MovementSpeedMultiplier Nano_GameInteractor_MovementSpeedMultiplier
static inline GIGravityLevel Nano_GameInteractor_GravityLevel(void) {  return GI_GRAVITY_LEVEL_NORMAL; }
#define GameInteractor_GravityLevel Nano_GameInteractor_GravityLevel
static inline uint32_t Nano_GameInteractor_GetEmulatedButtons(void) {  return 0; }
#define GameInteractor_GetEmulatedButtons Nano_GameInteractor_GetEmulatedButtons
static inline void Nano_GameInteractor_SetEmulatedButtons(uint32_t buttons) { (void)buttons; }
#define GameInteractor_SetEmulatedButtons Nano_GameInteractor_SetEmulatedButtons
static inline uint8_t Nano_GameInteractor_GetRandomBombFuseTimerActive(void) {  return 0; }
#define GameInteractor_GetRandomBombFuseTimerActive Nano_GameInteractor_GetRandomBombFuseTimerActive
static inline uint8_t Nano_GameInteractor_GetDisableLedgeGrabsActive(void) {  return 0; }
#define GameInteractor_GetDisableLedgeGrabsActive Nano_GameInteractor_GetDisableLedgeGrabsActive
static inline uint8_t Nano_GameInteractor_GetRandomWindActive(void) {  return 0; }
#define GameInteractor_GetRandomWindActive Nano_GameInteractor_GetRandomWindActive
static inline uint8_t Nano_GameInteractor_GetRandomBonksActive(void) {  return 0; }
#define GameInteractor_GetRandomBonksActive Nano_GameInteractor_GetRandomBonksActive
static inline uint8_t Nano_GameInteractor_GetSlipperyFloorActive(void) {  return 0; }
#define GameInteractor_GetSlipperyFloorActive Nano_GameInteractor_GetSlipperyFloorActive
static inline uint8_t Nano_GameInteractor_SecondCollisionUpdate(void) {  return 0; }
#define GameInteractor_SecondCollisionUpdate Nano_GameInteractor_SecondCollisionUpdate
static inline void Nano_GameInteractor_SetTriforceHuntPieceGiven(bool state) { (void)state; }
#define GameInteractor_SetTriforceHuntPieceGiven Nano_GameInteractor_SetTriforceHuntPieceGiven
static inline void Nano_GameInteractor_SetTriforceHuntCreditsWarpActive(bool state) { (void)state; }
#define GameInteractor_SetTriforceHuntCreditsWarpActive Nano_GameInteractor_SetTriforceHuntCreditsWarpActive
