/* Generated by tools/configure_nano.py; Nano-only optional features. */
#pragma once

static inline void Nano_GameInteractor_ExecuteOnZTitleInit(void* gameState) { (void)gameState; }
#define GameInteractor_ExecuteOnZTitleInit Nano_GameInteractor_ExecuteOnZTitleInit
static inline void Nano_GameInteractor_ExecuteOnZTitleUpdate(void* gameState) { (void)gameState; }
#define GameInteractor_ExecuteOnZTitleUpdate Nano_GameInteractor_ExecuteOnZTitleUpdate
static inline void Nano_GameInteractor_ExecuteOnLoadGame(int32_t fileNum) { (void)fileNum; }
#define GameInteractor_ExecuteOnLoadGame Nano_GameInteractor_ExecuteOnLoadGame
static inline void Nano_GameInteractor_ExecuteOnExitGame(int32_t fileNum) { (void)fileNum; }
#define GameInteractor_ExecuteOnExitGame Nano_GameInteractor_ExecuteOnExitGame
static inline void Nano_GameInteractor_ExecuteOnGameStateMainStart(void) {  }
#define GameInteractor_ExecuteOnGameStateMainStart Nano_GameInteractor_ExecuteOnGameStateMainStart
static inline void Nano_GameInteractor_ExecuteOnGameFrameUpdate(void) {  }
#define GameInteractor_ExecuteOnGameFrameUpdate Nano_GameInteractor_ExecuteOnGameFrameUpdate
static inline void Nano_GameInteractor_ExecuteOnCameraState(PlayState* play) { (void)play; }
#define GameInteractor_ExecuteOnCameraState Nano_GameInteractor_ExecuteOnCameraState
static inline void Nano_GameInteractor_ExecuteOnItemReceiveHooks(GetItemEntry itemEntry) { (void)itemEntry; }
#define GameInteractor_ExecuteOnItemReceiveHooks Nano_GameInteractor_ExecuteOnItemReceiveHooks
static inline void Nano_GameInteractor_ExecuteOnEquipmentDelete(int16_t equipmentType, uint16_t equipValue) { (void)equipmentType; (void)equipValue; }
#define GameInteractor_ExecuteOnEquipmentDelete Nano_GameInteractor_ExecuteOnEquipmentDelete
static inline void Nano_GameInteractor_ExecuteOnSaleEndHooks(GetItemEntry itemEntry) { (void)itemEntry; }
#define GameInteractor_ExecuteOnSaleEndHooks Nano_GameInteractor_ExecuteOnSaleEndHooks
static inline void Nano_GameInteractor_ExecuteOnTransitionEndHooks(int16_t sceneNum) { (void)sceneNum; }
#define GameInteractor_ExecuteOnTransitionEndHooks Nano_GameInteractor_ExecuteOnTransitionEndHooks
static inline void Nano_GameInteractor_ExecuteOnSceneInit(int16_t sceneNum) { (void)sceneNum; }
#define GameInteractor_ExecuteOnSceneInit Nano_GameInteractor_ExecuteOnSceneInit
static inline void Nano_GameInteractor_ExecuteAfterSceneCommands(int16_t sceneNum) { (void)sceneNum; }
#define GameInteractor_ExecuteAfterSceneCommands Nano_GameInteractor_ExecuteAfterSceneCommands
static inline void Nano_GameInteractor_ExecuteOnSceneFlagSet(int16_t sceneNum, int16_t flagType, int16_t flag) { (void)sceneNum; (void)flagType; (void)flag; }
#define GameInteractor_ExecuteOnSceneFlagSet Nano_GameInteractor_ExecuteOnSceneFlagSet
static inline void Nano_GameInteractor_ExecuteOnSceneFlagUnset(int16_t sceneNum, int16_t flagType, int16_t flag) { (void)sceneNum; (void)flagType; (void)flag; }
#define GameInteractor_ExecuteOnSceneFlagUnset Nano_GameInteractor_ExecuteOnSceneFlagUnset
static inline void Nano_GameInteractor_ExecuteOnFlagSet(int16_t flagType, int16_t flag) { (void)flagType; (void)flag; }
#define GameInteractor_ExecuteOnFlagSet Nano_GameInteractor_ExecuteOnFlagSet
static inline void Nano_GameInteractor_ExecuteOnFlagUnset(int16_t flagType, int16_t flag) { (void)flagType; (void)flag; }
#define GameInteractor_ExecuteOnFlagUnset Nano_GameInteractor_ExecuteOnFlagUnset
static inline void Nano_GameInteractor_ExecuteOnSceneSpawnActors(void) {  }
#define GameInteractor_ExecuteOnSceneSpawnActors Nano_GameInteractor_ExecuteOnSceneSpawnActors
static inline void Nano_GameInteractor_ExecuteOnLinkSkeletonInit(void) {  }
#define GameInteractor_ExecuteOnLinkSkeletonInit Nano_GameInteractor_ExecuteOnLinkSkeletonInit
static inline void Nano_GameInteractor_ExecuteOnLinkEquipmentChange(void) {  }
#define GameInteractor_ExecuteOnLinkEquipmentChange Nano_GameInteractor_ExecuteOnLinkEquipmentChange
static inline void Nano_GameInteractor_ExecuteOnPlayerUpdate(void) {  }
#define GameInteractor_ExecuteOnPlayerUpdate Nano_GameInteractor_ExecuteOnPlayerUpdate
static inline void Nano_GameInteractor_ExecuteOnSetDoAction(uint16_t action) { (void)action; }
#define GameInteractor_ExecuteOnSetDoAction Nano_GameInteractor_ExecuteOnSetDoAction
static inline void Nano_GameInteractor_ExecuteOnPlayerSfx(u16 sfxId) { (void)sfxId; }
#define GameInteractor_ExecuteOnPlayerSfx Nano_GameInteractor_ExecuteOnPlayerSfx
static inline void Nano_GameInteractor_ExecuteOnOcarinaSongAction(void) {  }
#define GameInteractor_ExecuteOnOcarinaSongAction Nano_GameInteractor_ExecuteOnOcarinaSongAction
static inline void Nano_GameInteractor_ExecuteOnWarpSongLeave(void) {  }
#define GameInteractor_ExecuteOnWarpSongLeave Nano_GameInteractor_ExecuteOnWarpSongLeave
static inline void Nano_GameInteractor_ExecuteOnOcarinaNote(uint8_t note, float modulator, int8_t bend) { (void)note; (void)modulator; (void)bend; }
#define GameInteractor_ExecuteOnOcarinaNote Nano_GameInteractor_ExecuteOnOcarinaNote
static inline bool Nano_GameInteractor_ShouldActorInit(void* actor) { (void)actor; return true; }
#define GameInteractor_ShouldActorInit Nano_GameInteractor_ShouldActorInit
static inline void Nano_GameInteractor_ExecuteOnActorInit(void* actor) { (void)actor; }
#define GameInteractor_ExecuteOnActorInit Nano_GameInteractor_ExecuteOnActorInit
static inline void Nano_GameInteractor_ExecuteOnActorSpawn(void* actor) { (void)actor; }
#define GameInteractor_ExecuteOnActorSpawn Nano_GameInteractor_ExecuteOnActorSpawn
static inline bool Nano_GameInteractor_ShouldActorUpdate(void* actor) { (void)actor; return true; }
#define GameInteractor_ShouldActorUpdate Nano_GameInteractor_ShouldActorUpdate
static inline void Nano_GameInteractor_ExecuteOnActorUpdate(void* actor) { (void)actor; }
#define GameInteractor_ExecuteOnActorUpdate Nano_GameInteractor_ExecuteOnActorUpdate
static inline void Nano_GameInteractor_ExecuteOnActorKill(void* actor) { (void)actor; }
#define GameInteractor_ExecuteOnActorKill Nano_GameInteractor_ExecuteOnActorKill
static inline bool Nano_GameInteractor_ShouldActorDestroy(void* actor) { (void)actor; return true; }
#define GameInteractor_ShouldActorDestroy Nano_GameInteractor_ShouldActorDestroy
static inline void Nano_GameInteractor_ExecuteOnActorDestroy(void* actor) { (void)actor; }
#define GameInteractor_ExecuteOnActorDestroy Nano_GameInteractor_ExecuteOnActorDestroy
static inline void Nano_GameInteractor_ExecuteOnEnemyDefeat(void* actor) { (void)actor; }
#define GameInteractor_ExecuteOnEnemyDefeat Nano_GameInteractor_ExecuteOnEnemyDefeat
static inline void Nano_GameInteractor_ExecuteOnBossDefeat(void* actor) { (void)actor; }
#define GameInteractor_ExecuteOnBossDefeat Nano_GameInteractor_ExecuteOnBossDefeat
static inline void Nano_GameInteractor_ExecuteOnTimestamp(u8 item) { (void)item; }
#define GameInteractor_ExecuteOnTimestamp Nano_GameInteractor_ExecuteOnTimestamp
static inline void Nano_GameInteractor_ExecuteOnPlayerBonk(void) {  }
#define GameInteractor_ExecuteOnPlayerBonk Nano_GameInteractor_ExecuteOnPlayerBonk
static inline void Nano_GameInteractor_ExecuteOnPlayerSetModels(Player* player, u8 modelGroup) { (void)player; (void)modelGroup; }
#define GameInteractor_ExecuteOnPlayerSetModels Nano_GameInteractor_ExecuteOnPlayerSetModels
static inline void Nano_GameInteractor_ExecuteOnPlayerHealthChange(int16_t amount) { (void)amount; }
#define GameInteractor_ExecuteOnPlayerHealthChange Nano_GameInteractor_ExecuteOnPlayerHealthChange
static inline void Nano_GameInteractor_ExecuteOnPlayerBottleUpdate(int16_t contents) { (void)contents; }
#define GameInteractor_ExecuteOnPlayerBottleUpdate Nano_GameInteractor_ExecuteOnPlayerBottleUpdate
static inline void Nano_GameInteractor_ExecuteOnPlayerHoldUpShield(void) {  }
#define GameInteractor_ExecuteOnPlayerHoldUpShield Nano_GameInteractor_ExecuteOnPlayerHoldUpShield
static inline void Nano_GameInteractor_ExecuteOnPlayerFirstPersonControl(Player* player) { (void)player; }
#define GameInteractor_ExecuteOnPlayerFirstPersonControl Nano_GameInteractor_ExecuteOnPlayerFirstPersonControl
static inline void Nano_GameInteractor_ExecuteOnPlayerShieldControl(float* sp50, float* sp54) { (void)sp50; (void)sp54; }
#define GameInteractor_ExecuteOnPlayerShieldControl Nano_GameInteractor_ExecuteOnPlayerShieldControl
static inline void Nano_GameInteractor_ExecuteOnPlayerProcessStick(void) {  }
#define GameInteractor_ExecuteOnPlayerProcessStick Nano_GameInteractor_ExecuteOnPlayerProcessStick
static inline void Nano_GameInteractor_ExecuteOnShopSlotChangeHooks(uint8_t cursorIndex, int16_t price) { (void)cursorIndex; (void)price; }
#define GameInteractor_ExecuteOnShopSlotChangeHooks Nano_GameInteractor_ExecuteOnShopSlotChangeHooks
static inline void Nano_GameInteractor_ExecuteOnDungeonKeyUsedHooks(uint16_t mapIndex) { (void)mapIndex; }
#define GameInteractor_ExecuteOnDungeonKeyUsedHooks Nano_GameInteractor_ExecuteOnDungeonKeyUsedHooks
static inline void Nano_GameInteractor_ExecuteOnPlayDestroy(void) {  }
#define GameInteractor_ExecuteOnPlayDestroy Nano_GameInteractor_ExecuteOnPlayDestroy
static inline void Nano_GameInteractor_ExecuteOnPlayDrawBegin(void) {  }
#define GameInteractor_ExecuteOnPlayDrawBegin Nano_GameInteractor_ExecuteOnPlayDrawBegin
static inline void Nano_GameInteractor_ExecuteOnPlayDrawEnd(void) {  }
#define GameInteractor_ExecuteOnPlayDrawEnd Nano_GameInteractor_ExecuteOnPlayDrawEnd
static inline bool Nano_GameInteractor_Should(GIVanillaBehavior flag, uint32_t result, ...) { (void)flag; (void)result; return result != 0; }
#define GameInteractor_Should Nano_GameInteractor_Should
static inline void Nano_GameInteractor_ExecuteOnSaveFile(int32_t fileNum, int32_t sectionID) { (void)fileNum; (void)sectionID; }
#define GameInteractor_ExecuteOnSaveFile Nano_GameInteractor_ExecuteOnSaveFile
static inline void Nano_GameInteractor_ExecuteOnLoadFile(int32_t fileNum) { (void)fileNum; }
#define GameInteractor_ExecuteOnLoadFile Nano_GameInteractor_ExecuteOnLoadFile
static inline void Nano_GameInteractor_ExecuteOnDeleteFile(int32_t fileNum) { (void)fileNum; }
#define GameInteractor_ExecuteOnDeleteFile Nano_GameInteractor_ExecuteOnDeleteFile
static inline void Nano_GameInteractor_ExecuteOnDialogMessage(void) {  }
#define GameInteractor_ExecuteOnDialogMessage Nano_GameInteractor_ExecuteOnDialogMessage
static inline void Nano_GameInteractor_ExecuteOnPresentTitleCard(void) {  }
#define GameInteractor_ExecuteOnPresentTitleCard Nano_GameInteractor_ExecuteOnPresentTitleCard
static inline void Nano_GameInteractor_ExecuteOnInterfaceUpdate(void) {  }
#define GameInteractor_ExecuteOnInterfaceUpdate Nano_GameInteractor_ExecuteOnInterfaceUpdate
static inline void Nano_GameInteractor_ExecuteOnKaleidoscopeUpdate(int16_t inDungeonScene) { (void)inDungeonScene; }
#define GameInteractor_ExecuteOnKaleidoscopeUpdate Nano_GameInteractor_ExecuteOnKaleidoscopeUpdate
static inline void Nano_GameInteractor_ExecuteOnMinimapDrawCompassIcons(void) {  }
#define GameInteractor_ExecuteOnMinimapDrawCompassIcons Nano_GameInteractor_ExecuteOnMinimapDrawCompassIcons
static inline void Nano_GameInteractor_ExecuteOnPresentFileSelect(void) {  }
#define GameInteractor_ExecuteOnPresentFileSelect Nano_GameInteractor_ExecuteOnPresentFileSelect
static inline void Nano_GameInteractor_ExecuteOnUpdateFileSelectSelection(uint16_t optionIndex) { (void)optionIndex; }
#define GameInteractor_ExecuteOnUpdateFileSelectSelection Nano_GameInteractor_ExecuteOnUpdateFileSelectSelection
static inline void Nano_GameInteractor_ExecuteOnUpdateFileSelectConfirmationSelection(uint16_t optionIndex) { (void)optionIndex; }
#define GameInteractor_ExecuteOnUpdateFileSelectConfirmationSelection Nano_GameInteractor_ExecuteOnUpdateFileSelectConfirmationSelection
static inline void Nano_GameInteractor_ExecuteOnUpdateFileCopySelection(uint16_t optionIndex) { (void)optionIndex; }
#define GameInteractor_ExecuteOnUpdateFileCopySelection Nano_GameInteractor_ExecuteOnUpdateFileCopySelection
static inline void Nano_GameInteractor_ExecuteOnUpdateFileCopyConfirmationSelection(uint16_t optionIndex) { (void)optionIndex; }
#define GameInteractor_ExecuteOnUpdateFileCopyConfirmationSelection Nano_GameInteractor_ExecuteOnUpdateFileCopyConfirmationSelection
static inline void Nano_GameInteractor_ExecuteOnUpdateFileEraseSelection(uint16_t optionIndex) { (void)optionIndex; }
#define GameInteractor_ExecuteOnUpdateFileEraseSelection Nano_GameInteractor_ExecuteOnUpdateFileEraseSelection
static inline void Nano_GameInteractor_ExecuteOnUpdateFileEraseConfirmationSelection(uint16_t optionIndex) { (void)optionIndex; }
#define GameInteractor_ExecuteOnUpdateFileEraseConfirmationSelection Nano_GameInteractor_ExecuteOnUpdateFileEraseConfirmationSelection
static inline void Nano_GameInteractor_ExecuteOnUpdateFileAudioSelection(uint8_t optionIndex) { (void)optionIndex; }
#define GameInteractor_ExecuteOnUpdateFileAudioSelection Nano_GameInteractor_ExecuteOnUpdateFileAudioSelection
static inline void Nano_GameInteractor_ExecuteOnUpdateFileTargetSelection(uint8_t optionIndex) { (void)optionIndex; }
#define GameInteractor_ExecuteOnUpdateFileTargetSelection Nano_GameInteractor_ExecuteOnUpdateFileTargetSelection
static inline void Nano_GameInteractor_ExecuteOnUpdateFileLanguageSelection(uint8_t optionIndex) { (void)optionIndex; }
#define GameInteractor_ExecuteOnUpdateFileLanguageSelection Nano_GameInteractor_ExecuteOnUpdateFileLanguageSelection
static inline void Nano_GameInteractor_ExecuteOnUpdateFileQuestSelection(uint8_t questIndex) { (void)questIndex; }
#define GameInteractor_ExecuteOnUpdateFileQuestSelection Nano_GameInteractor_ExecuteOnUpdateFileQuestSelection
static inline void Nano_GameInteractor_ExecuteOnUpdateFileBossRushOptionSelection(uint8_t optionIndex, uint8_t optionValue) { (void)optionIndex; (void)optionValue; }
#define GameInteractor_ExecuteOnUpdateFileBossRushOptionSelection Nano_GameInteractor_ExecuteOnUpdateFileBossRushOptionSelection
static inline void Nano_GameInteractor_ExecuteOnUpdateFileRandomizerOptionSelection(uint8_t optionIndex) { (void)optionIndex; }
#define GameInteractor_ExecuteOnUpdateFileRandomizerOptionSelection Nano_GameInteractor_ExecuteOnUpdateFileRandomizerOptionSelection
static inline void Nano_GameInteractor_ExecuteOnUpdateFileNameSelection(int16_t charCode) { (void)charCode; }
#define GameInteractor_ExecuteOnUpdateFileNameSelection Nano_GameInteractor_ExecuteOnUpdateFileNameSelection
static inline void Nano_GameInteractor_ExecuteOnFileChooseMain(void* gameState) { (void)gameState; }
#define GameInteractor_ExecuteOnFileChooseMain Nano_GameInteractor_ExecuteOnFileChooseMain
static inline void Nano_GameInteractor_ExecuteOnSetGameLanguage(void) {  }
#define GameInteractor_ExecuteOnSetGameLanguage Nano_GameInteractor_ExecuteOnSetGameLanguage
static inline void Nano_GameInteractor_RegisterOnAssetAltChange(void (*fn)(void)) { (void)fn; }
#define GameInteractor_RegisterOnAssetAltChange Nano_GameInteractor_RegisterOnAssetAltChange
static inline void Nano_GameInteractor_ExecuteOnKaleidoUpdate(void) {  }
#define GameInteractor_ExecuteOnKaleidoUpdate Nano_GameInteractor_ExecuteOnKaleidoUpdate
static inline void Nano_GameInteractor_ExecuteOnOpenText(uint16_t* textId, bool* loadFromMessageTable) { (void)textId; (void)loadFromMessageTable; }
#define GameInteractor_ExecuteOnOpenText Nano_GameInteractor_ExecuteOnOpenText
static inline void Nano_GameInteractor_ExecuteOnSeqPlayerInit(int32_t playerIdx, int32_t seqId) { (void)playerIdx; (void)seqId; }
#define GameInteractor_ExecuteOnSeqPlayerInit Nano_GameInteractor_ExecuteOnSeqPlayerInit
static inline void Nano_GameInteractor_ExecuteOnRandoEntranceDiscovered(u16 entranceIndex, u8 isReversedEntrance) { (void)entranceIndex; (void)isReversedEntrance; }
#define GameInteractor_ExecuteOnRandoEntranceDiscovered Nano_GameInteractor_ExecuteOnRandoEntranceDiscovered
