/* Generated by tools/configure_nano.py; Nano-only optional features. */
#pragma once

static inline void Nano_FrameInterpolation_StartRecord(void) {  }
#define FrameInterpolation_StartRecord Nano_FrameInterpolation_StartRecord
static inline void Nano_FrameInterpolation_StopRecord(void) {  }
#define FrameInterpolation_StopRecord Nano_FrameInterpolation_StopRecord
static inline void Nano_FrameInterpolation_RecordOpenChild(const void* a, int b) { (void)a; (void)b; }
#define FrameInterpolation_RecordOpenChild Nano_FrameInterpolation_RecordOpenChild
static inline void Nano_FrameInterpolation_RecordCloseChild(void) {  }
#define FrameInterpolation_RecordCloseChild Nano_FrameInterpolation_RecordCloseChild
static inline void Nano_FrameInterpolation_DontInterpolateCamera(void) {  }
#define FrameInterpolation_DontInterpolateCamera Nano_FrameInterpolation_DontInterpolateCamera
static inline int Nano_FrameInterpolation_GetCameraEpoch(void) {  return 0; }
#define FrameInterpolation_GetCameraEpoch Nano_FrameInterpolation_GetCameraEpoch
static inline void Nano_FrameInterpolation_RecordActorPosRotMatrix(void) {  }
#define FrameInterpolation_RecordActorPosRotMatrix Nano_FrameInterpolation_RecordActorPosRotMatrix
static inline void Nano_FrameInterpolation_RecordMatrixPush(void) {  }
#define FrameInterpolation_RecordMatrixPush Nano_FrameInterpolation_RecordMatrixPush
static inline void Nano_FrameInterpolation_RecordMatrixPop(void) {  }
#define FrameInterpolation_RecordMatrixPop Nano_FrameInterpolation_RecordMatrixPop
static inline void Nano_FrameInterpolation_RecordMatrixPut(MtxF* src) { (void)src; }
#define FrameInterpolation_RecordMatrixPut Nano_FrameInterpolation_RecordMatrixPut
static inline void Nano_FrameInterpolation_RecordMatrixMult(MtxF* mf, u8 mode) { (void)mf; (void)mode; }
#define FrameInterpolation_RecordMatrixMult Nano_FrameInterpolation_RecordMatrixMult
static inline void Nano_FrameInterpolation_RecordMatrixTranslate(f32 x, f32 y, f32 z, u8 mode) { (void)x; (void)y; (void)z; (void)mode; }
#define FrameInterpolation_RecordMatrixTranslate Nano_FrameInterpolation_RecordMatrixTranslate
static inline void Nano_FrameInterpolation_RecordMatrixScale(f32 x, f32 y, f32 z, u8 mode) { (void)x; (void)y; (void)z; (void)mode; }
#define FrameInterpolation_RecordMatrixScale Nano_FrameInterpolation_RecordMatrixScale
static inline void Nano_FrameInterpolation_RecordMatrixRotate1Coord(u32 coord, f32 value, u8 mode) { (void)coord; (void)value; (void)mode; }
#define FrameInterpolation_RecordMatrixRotate1Coord Nano_FrameInterpolation_RecordMatrixRotate1Coord
static inline void Nano_FrameInterpolation_RecordMatrixRotateZYX(s16 x, s16 y, s16 z, u8 mode) { (void)x; (void)y; (void)z; (void)mode; }
#define FrameInterpolation_RecordMatrixRotateZYX Nano_FrameInterpolation_RecordMatrixRotateZYX
static inline void Nano_FrameInterpolation_RecordMatrixTranslateRotateZYX(Vec3f* translation, Vec3s* rotation) { (void)translation; (void)rotation; }
#define FrameInterpolation_RecordMatrixTranslateRotateZYX Nano_FrameInterpolation_RecordMatrixTranslateRotateZYX
static inline void Nano_FrameInterpolation_RecordMatrixSetTranslateRotateYXZ(f32 translateX, f32 translateY, f32 translateZ, Vec3s* rot) { (void)translateX; (void)translateY; (void)translateZ; (void)rot; }
#define FrameInterpolation_RecordMatrixSetTranslateRotateYXZ Nano_FrameInterpolation_RecordMatrixSetTranslateRotateYXZ
static inline void Nano_FrameInterpolation_RecordMatrixMtxFToMtx(MtxF* src, Mtx* dest) { (void)src; (void)dest; }
#define FrameInterpolation_RecordMatrixMtxFToMtx Nano_FrameInterpolation_RecordMatrixMtxFToMtx
static inline void Nano_FrameInterpolation_RecordMatrixToMtx(Mtx* dest, char* file, s32 line) { (void)dest; (void)file; (void)line; }
#define FrameInterpolation_RecordMatrixToMtx Nano_FrameInterpolation_RecordMatrixToMtx
static inline void Nano_FrameInterpolation_RecordMatrixReplaceRotation(MtxF* mf) { (void)mf; }
#define FrameInterpolation_RecordMatrixReplaceRotation Nano_FrameInterpolation_RecordMatrixReplaceRotation
static inline void Nano_FrameInterpolation_RecordMatrixRotateAxis(f32 angle, Vec3f* axis, u8 mode) { (void)angle; (void)axis; (void)mode; }
#define FrameInterpolation_RecordMatrixRotateAxis Nano_FrameInterpolation_RecordMatrixRotateAxis
static inline void Nano_FrameInterpolation_RecordSkinMatrixMtxFToMtx(MtxF* src, Mtx* dest) { (void)src; (void)dest; }
#define FrameInterpolation_RecordSkinMatrixMtxFToMtx Nano_FrameInterpolation_RecordSkinMatrixMtxFToMtx
