#!/usr/bin/env python3
import json
import pathlib
import sys


def c_string(value: str) -> str:
    value = value.replace("\\", "\\\\").replace('"', '\\"')
    value = value.replace("\n", "\\n")
    return f'"{value}"'


def main() -> int:
    if len(sys.argv) != 3:
        print(
            "usage: gen_cdogs_characters.py <characters.json> <output.h>",
            file=sys.stderr,
        )
        return 1

    characters_path = pathlib.Path(sys.argv[1])
    output_path = pathlib.Path(sys.argv[2])
    chars = json.loads(characters_path.read_text())["Characters"]

    lines = []
    lines.append("/* Auto-generated by tools/gen_cdogs_characters.py */")
    lines.append("#ifndef CDOGS_TERROR_CHARACTERS_H")
    lines.append("#define CDOGS_TERROR_CHARACTERS_H")
    lines.append("")
    lines.append("struct cdogs_character_data")
    lines.append("{")
    lines.append("    const char *class_name;")
    lines.append("    const char *gun;")
    lines.append("    int max_health;")
    lines.append("    int speed;")
    lines.append("    int probability_to_move;")
    lines.append("    int probability_to_track;")
    lines.append("    int probability_to_shoot;")
    lines.append("    int action_delay;")
    lines.append("};")
    lines.append("")
    lines.append(f"static const int cdogs_character_count = {len(chars)};")
    lines.append("static const struct cdogs_character_data cdogs_characters[] =")
    lines.append("{")
    for c in chars:
        lines.append("    {")
        lines.append(f"        {c_string(c.get('Class', ''))},")
        lines.append(f"        {c_string(c.get('Gun', ''))},")
        lines.append(f"        {int(c.get('maxHealth', 20))},")
        lines.append(f"        {int(c.get('speed', 256))},")
        lines.append(f"        {int(c.get('probabilityToMove', 0))},")
        lines.append(f"        {int(c.get('probabilityToTrack', 0))},")
        lines.append(f"        {int(c.get('probabilityToShoot', 0))},")
        lines.append(f"        {int(c.get('actionDelay', 10))},")
        lines.append("    },")
    lines.append("};")
    lines.append("")
    lines.append("#endif")
    lines.append("")
    output_path.write_text("\n".join(lines))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
