file=podzilla
	location=podzilla
	end-file
image=usr/local/ipod-desktop/images/games.gif
image:selected=usr/local/ipod-desktop/images/games_selected.gif
menu=Games
	file=4 Gewinnt
		location=usr/local/4wins/4wins
		image=usr/local/ipod-desktop/images/4wins.gif
		image:selected=usr/local/ipod-desktop/images/4wins_selected.gif
		end-file
	file=Tetris
		location=tetris
		image=usr/local/ipod-desktop/images/tetris.gif
		image:selected=usr/local/ipod-desktop/images/tetris_selected.gif
		end-file
	end-menu
image=usr/local/ipod-desktop/images/settings.gif
image:selected=usr/local/ipod-desktop/images/settings_selected.gif
menu=settings
	system=backlight
		location=3
		image=usr/local/ipod-desktop/images/backlight.gif
		image:selected=usr/local/ipod-desktop/images/backlight_selected.gif
		end-system
	system=contrast
		location=4
		end-system
	end-menu
system=Reboot
	location=1
	image=usr/local/ipod-desktop/images/reboot.gif
	image:selected=usr/local/ipod-desktop/images/reboot_selected.gif
	end-system
system=Quit
	location=2
	image=usr/local/ipod-desktop/images/quit.gif
	image:selected=usr/local/ipod-desktop/images/quit_selected.gif
	end-system
