/home/david/Documents/RockBox_Personal-master/tools/ios/OpenLaraCompact/.theos/obj/armv7/../../../apps/plugins/openlara/render.cpp.c8aeac1a.o: \
  ../../../apps/plugins/openlara/render.cpp /home/david/theos/Prefix.pch \
  ../../../apps/plugins/openlara/fixed/common.h \
  ../../../apps/plugins/openlara/rasterizer.h

/home/david/theos/Prefix.pch:

../../../apps/plugins/openlara/fixed/common.h:

../../../apps/plugins/openlara/rasterizer.h:
