//AUTOGENERATED FILE FROM png2asset
// Conversion args: /iona_rooftop.png -c iona_rooftop.c -map -noflip -b 255

#ifndef METASPRITE_iona_rooftop_H
#define METASPRITE_iona_rooftop_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define iona_rooftop_TILE_ORIGIN 0
#define iona_rooftop_TILE_W 8
#define iona_rooftop_TILE_H 8
#define iona_rooftop_WIDTH 160
#define iona_rooftop_HEIGHT 144
#define iona_rooftop_TILE_COUNT 68
#define iona_rooftop_PALETTE_COUNT 1
#define iona_rooftop_COLORS_PER_PALETTE 4
#define iona_rooftop_TOTAL_COLORS 4
#define iona_rooftop_MAP_ATTRIBUTES 0
extern const unsigned char iona_rooftop_map[360];
#define iona_rooftop_map_attributes iona_rooftop_map

BANKREF_EXTERN(iona_rooftop)

extern const palette_color_t iona_rooftop_palettes[4];
extern const uint8_t iona_rooftop_tiles[1088];

#endif
