//AUTOGENERATED FILE FROM png2asset
// Conversion args: /luma_lane_district.png -c /luma_lane_district.c -map -noflip -b 255

#ifndef METASPRITE_luma_lane_district_H
#define METASPRITE_luma_lane_district_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define luma_lane_district_TILE_ORIGIN 0
#define luma_lane_district_TILE_W 8
#define luma_lane_district_TILE_H 8
#define luma_lane_district_WIDTH 160
#define luma_lane_district_HEIGHT 144
#define luma_lane_district_TILE_COUNT 118
#define luma_lane_district_PALETTE_COUNT 1
#define luma_lane_district_COLORS_PER_PALETTE 4
#define luma_lane_district_TOTAL_COLORS 4
#define luma_lane_district_MAP_ATTRIBUTES 0
extern const unsigned char luma_lane_district_map[360];
#define luma_lane_district_map_attributes luma_lane_district_map

BANKREF_EXTERN(luma_lane_district)

extern const palette_color_t luma_lane_district_palettes[4];
extern const uint8_t luma_lane_district_tiles[1888];

#endif
