//AUTOGENERATED FILE FROM png2asset
// Conversion args: /luma-lane-district-v12-gb.png -c /luma-lane-district-v12-gb.c -map -noflip -b 255

#ifndef METASPRITE_luma_lane_district_v2_H
#define METASPRITE_luma_lane_district_v2_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define luma_lane_district_v2_TILE_ORIGIN 0
#define luma_lane_district_v2_TILE_W 8
#define luma_lane_district_v2_TILE_H 8
#define luma_lane_district_v2_WIDTH 160
#define luma_lane_district_v2_HEIGHT 144
#define luma_lane_district_v2_TILE_COUNT 162
#define luma_lane_district_v2_PALETTE_COUNT 1
#define luma_lane_district_v2_COLORS_PER_PALETTE 4
#define luma_lane_district_v2_TOTAL_COLORS 4
#define luma_lane_district_v2_MAP_ATTRIBUTES 0
extern const unsigned char luma_lane_district_v2_map[360];
#define luma_lane_district_v2_map_attributes luma_lane_district_v2_map

BANKREF_EXTERN(luma_lane_district_v2)

extern const palette_color_t luma_lane_district_v2_palettes[4];
extern const uint8_t luma_lane_district_v2_tiles[2592];

#endif
