//AUTOGENERATED FILE FROM png2asset
// Conversion args: /soma_ramen.png -c soma_ramen.c -map -noflip -b 255

#ifndef METASPRITE_soma_ramen_H
#define METASPRITE_soma_ramen_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define soma_ramen_TILE_ORIGIN 0
#define soma_ramen_TILE_W 8
#define soma_ramen_TILE_H 8
#define soma_ramen_WIDTH 160
#define soma_ramen_HEIGHT 144
#define soma_ramen_TILE_COUNT 79
#define soma_ramen_PALETTE_COUNT 1
#define soma_ramen_COLORS_PER_PALETTE 4
#define soma_ramen_TOTAL_COLORS 4
#define soma_ramen_MAP_ATTRIBUTES 0
extern const unsigned char soma_ramen_map[360];
#define soma_ramen_map_attributes soma_ramen_map

BANKREF_EXTERN(soma_ramen)

extern const palette_color_t soma_ramen_palettes[4];
extern const uint8_t soma_ramen_tiles[1264];

#endif
