//AUTOGENERATED FILE FROM png2asset
// Conversion args: /s2-gb.png -c /s2-gb.c -map -noflip -b 255

#ifndef METASPRITE_southline_overpass_H
#define METASPRITE_southline_overpass_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define southline_overpass_TILE_ORIGIN 0
#define southline_overpass_TILE_W 8
#define southline_overpass_TILE_H 8
#define southline_overpass_WIDTH 160
#define southline_overpass_HEIGHT 144
#define southline_overpass_TILE_COUNT 97
#define southline_overpass_PALETTE_COUNT 1
#define southline_overpass_COLORS_PER_PALETTE 4
#define southline_overpass_TOTAL_COLORS 4
#define southline_overpass_MAP_ATTRIBUTES 0
extern const unsigned char southline_overpass_map[360];
#define southline_overpass_map_attributes southline_overpass_map

BANKREF_EXTERN(southline_overpass)

extern const palette_color_t southline_overpass_palettes[4];
extern const uint8_t southline_overpass_tiles[1552];

#endif
