//AUTOGENERATED FILE FROM png2asset
// Conversion args: /dialtone_title_b.png -c /startup_dialtone_title_b.c -map -noflip -b 255

#ifndef METASPRITE_startup_dialtone_title_b_H
#define METASPRITE_startup_dialtone_title_b_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define startup_dialtone_title_b_TILE_ORIGIN 0
#define startup_dialtone_title_b_TILE_W 8
#define startup_dialtone_title_b_TILE_H 8
#define startup_dialtone_title_b_WIDTH 160
#define startup_dialtone_title_b_HEIGHT 144
#define startup_dialtone_title_b_TILE_COUNT 140
#define startup_dialtone_title_b_PALETTE_COUNT 1
#define startup_dialtone_title_b_COLORS_PER_PALETTE 4
#define startup_dialtone_title_b_TOTAL_COLORS 4
#define startup_dialtone_title_b_MAP_ATTRIBUTES 0
extern const unsigned char startup_dialtone_title_b_map[360];
#define startup_dialtone_title_b_map_attributes startup_dialtone_title_b_map

BANKREF_EXTERN(startup_dialtone_title_b)

extern const palette_color_t startup_dialtone_title_b_palettes[4];
extern const uint8_t startup_dialtone_title_b_tiles[2240];

#endif
