//AUTOGENERATED FILE FROM png2asset
// Conversion args: /luma_lane_apartment.backup.png -c /luma_lane_apartment.c -map -noflip -b 255

#ifndef METASPRITE_luma_lane_apartment_H
#define METASPRITE_luma_lane_apartment_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define luma_lane_apartment_TILE_ORIGIN 0
#define luma_lane_apartment_TILE_W 8
#define luma_lane_apartment_TILE_H 8
#define luma_lane_apartment_WIDTH 160
#define luma_lane_apartment_HEIGHT 144
#define luma_lane_apartment_TILE_COUNT 216
#define luma_lane_apartment_PALETTE_COUNT 1
#define luma_lane_apartment_COLORS_PER_PALETTE 4
#define luma_lane_apartment_TOTAL_COLORS 4
#define luma_lane_apartment_MAP_ATTRIBUTES 0
extern const unsigned char luma_lane_apartment_map[360];
#define luma_lane_apartment_map_attributes luma_lane_apartment_map

BANKREF_EXTERN(luma_lane_apartment)

extern const palette_color_t luma_lane_apartment_palettes[4];
extern const uint8_t luma_lane_apartment_tiles[3456];

#endif
