//AUTOGENERATED FILE FROM png2asset
// Conversion args: /needle_and_neon_records.png -c needle_and_neon_records.c -map -noflip -b 255

#ifndef METASPRITE_needle_and_neon_records_H
#define METASPRITE_needle_and_neon_records_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define needle_and_neon_records_TILE_ORIGIN 0
#define needle_and_neon_records_TILE_W 8
#define needle_and_neon_records_TILE_H 8
#define needle_and_neon_records_WIDTH 160
#define needle_and_neon_records_HEIGHT 144
#define needle_and_neon_records_TILE_COUNT 85
#define needle_and_neon_records_PALETTE_COUNT 1
#define needle_and_neon_records_COLORS_PER_PALETTE 4
#define needle_and_neon_records_TOTAL_COLORS 4
#define needle_and_neon_records_MAP_ATTRIBUTES 0
extern const unsigned char needle_and_neon_records_map[360];
#define needle_and_neon_records_map_attributes needle_and_neon_records_map

BANKREF_EXTERN(needle_and_neon_records)

extern const palette_color_t needle_and_neon_records_palettes[4];
extern const uint8_t needle_and_neon_records_tiles[1360];

#endif
