//AUTOGENERATED FILE FROM png2asset
// Conversion args: /dialtone_title_a.png -c /startup_dialtone_title_a.c -map -noflip -b 255

#ifndef METASPRITE_startup_dialtone_title_a_H
#define METASPRITE_startup_dialtone_title_a_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define startup_dialtone_title_a_TILE_ORIGIN 0
#define startup_dialtone_title_a_TILE_W 8
#define startup_dialtone_title_a_TILE_H 8
#define startup_dialtone_title_a_WIDTH 160
#define startup_dialtone_title_a_HEIGHT 144
#define startup_dialtone_title_a_TILE_COUNT 130
#define startup_dialtone_title_a_PALETTE_COUNT 1
#define startup_dialtone_title_a_COLORS_PER_PALETTE 4
#define startup_dialtone_title_a_TOTAL_COLORS 4
#define startup_dialtone_title_a_MAP_ATTRIBUTES 0
extern const unsigned char startup_dialtone_title_a_map[360];
#define startup_dialtone_title_a_map_attributes startup_dialtone_title_a_map

BANKREF_EXTERN(startup_dialtone_title_a)

extern const palette_color_t startup_dialtone_title_a_palettes[4];
extern const uint8_t startup_dialtone_title_a_tiles[2080];

#endif
