\name Cal Poly
# by Jonathynne Bettencourt
# Generated by iPL Color Scheme Editor
\def dkgreen #1E431B
\def ltgreen #405F33
\def gold #D5B150
\def ltgold #E3D099
\def dkgold #D3AE4C
\def white #FFFFFF
\def black #000000

menu:
	bg => <horiz dkgreen to dkgreen to ltgreen>,
	fg => white,
	choice => ltgold,
	icon => ltgold,
	selbg => <vert gold to ltgold to dkgold>,
	selfg => dkgreen,
	selchoice => dkgreen,
	icon0 => dkgreen,
	icon1 => ltgreen,
	icon2 => #619965,
	icon3 => #B8FFA9
window:
	bg => <horiz dkgreen to dkgreen to ltgreen>,
	fg => white,
	border => #A4A4A4
header:
	line => #A4A4A4,
	fg => dkgreen,
	bg => <vert ltgold to gold>,
	accent => ltgreen,
	shadow => #A3882E,
	shine => #FDE5BC,
	gradient.top => ltgold,
	gradient.middle => ltgold,
	gradient.bottom => dkgold,
	gradient.bar => dkgold
loadavg:
	bg => #86A770,
	fg => dkgreen,
	spike => dkgold
lock:
	fill => ltgreen,
	border => dkgreen
scroll:
	box => dkgold,
	bg => <horiz ltgold to dkgold to ltgold>,
	bar => <horiz dkgreen to ltgreen to dkgreen>
music:
	bar.bg => ltgold,
	bar => <vert dkgreen to ltgreen to dkgreen>
battery:
	border => dkgreen,
	bg => <vert dkgold to ltgold>,
	bg.low => <vert #B8431B to #FF5F33>,
	bg.charging => <vert #B5D099 to #AFAE4C>,
	fill.normal => <vert dkgreen to ltgreen>,
	fill.low => <vert #920000 to #FF0000>,
	fill.charge => <vert #B3FF00 to dkgreen>,
	chargingbolt => #7C1E1B
dialog:
	bg => <vert gold to ltgold to ltgold>,
	fg => dkgreen,
	line => #374E34,
	title.fg => dkgreen,
	button.border => dkgreen,
	button.bg => <vert gold to ltgold to dkgold>,
	button.fg => dkgreen,
	button.sel.bg => <vert ltgreen to dkgreen to ltgreen>,
	button.sel.border => dkgreen,
	button.sel.inner => #7EDD7E,
	button.sel.fg => ltgold
error:
	bg => <vert #FF8000 to gold to ltgold>,
	fg => #800000,
	line => #FF0000,
	title.fg => #800000,
	button.bg => <vert gold to ltgold to dkgold>,
	button.fg => dkgreen,
	button.border => dkgreen,
	button.sel.bg => <vert dkgreen to ltgreen to dkgreen>,
	button.sel.fg => ltgold,
	button.sel.border => dkgreen,
	button.sel.inner => #7EDD7E
slider:
	border => white,
	bg => <vert gold to ltgold>,
	full => <vert ltgreen to dkgreen>
textarea:
	bg => white,
	fg => black
input:
	border => #A4A4A4,
	cursor => dkgreen,
	bg => #FFFFED,
	fg => black,
	selbg => <vert dkgreen to ltgreen to dkgreen>,
	selfg => ltgold
box:
	default.bg => <vert ltgold to dkgold>,
	default.fg => dkgreen,
	default.border => #7F7601,
	selected.bg => <vert gold to #7F7601>,
	selected.fg => black,
	selected.border => black,
	special.bg => <vert ltgold to ltgreen>,
	special.fg => ltgreen,
	special.border => dkgreen
button:
	default.bg => <vert ltgold to gold to ltgold>,
	default.fg => dkgreen,
	default.border => black,
	selected.bg => <vert dkgreen to ltgreen to dkgreen>,
	selected.fg => ltgold,
	selected.border => black
