\name Eclipse
# Baced offa' IPW scheme
# by Owen McGarry
# Generated by iPL Color Scheme Editor

header:
	bg => @eclipse.bar.png,
	fg => #000000,
	line => #FFFFFF,
	accent => #000000,
	shadow => #000000,
	shine => #000000,
	gradient.top => #000000,
	gradient.middle => #000000,
	gradient.bottom => #000000,
	gradient.bar => #000000
music:
	bar => @eclipse.barfull.png,
	bar.bg => @eclipse.barempty.png
menu:
	bg => #FFFFFF,
	fg => #000000,
	choice => #000000,
	selfg => #FFFFFF,
	selbg => <vert #6F6F6F to #9A9A9A to #B4B4B4>,
	selchoice => #000000,
	icon0 => #000000,
	icon1 => #000000,
	icon => #000000
window:
	bg => #FFFFFF,
	fg => #000000,
	border => #000000
lock:
	fill => <vert #C1C1C1 to #969696 to #838383>,
	border => #727272
battery:
	fill.charge => @Eclipse.battcharge.png,
	fill.low => <vert #7A0101 to #B80202 to #E30202>,
	fill.normal => <vert #004800 to #008000 to #00AD01>,
	border => #000000
dialog:
	bg => #FFFFFF,
	fg => #000000,
	line => #000000,
	title.fg => #000000,
	button.bg => <vert #6F6F6F to #9A9A9A to #B4B4B4>,
	button.fg => #000000,
	button.border => #000000,
	button.sel.bg => <vert #6F6F6F to #9A9A9A to #B4B4B4>,
	button.sel.fg => #FFFFFF,
	button.sel.border => #000000
error:
	bg => #FFFFFF,
	fg => #000000,
	line => #000000,
	title.fg => #000000,
	button.bg => <vert #6F6F6F to #9A9A9A to #B4B4B4>,
	button.fg => #000000,
	button.border => #000000,
	button.sel.bg => <vert #6F6F6F to #9A9A9A to #B4B4B4>,
	button.sel.fg => #FFFFFF,
	button.sel.border => #000000
scroll:
	bg => @Eclipse.scrollbg.png,
	bar => @eclipse.scrollfg.png
slider:
	bg => @eclipse.barempty.png,
	full => @eclipse.barfull.png
textarea:
	bg => #FFFFFF,
	fg => #000000
input:
	bg => #FFFFFF,
	fg => #000000,
	border => #000000,
	cursor => #000000,
	selbg => <vert #6F6F6F to #9A9A9A to #B4B4B4>,
	selfg => #FFFFFF
box:
	default.bg => #FFFFFF,
	default.fg => #000000,
	default.border => #000000,
	selected.bg => <vert #6F6F6F to #9A9A9A to #B4B4B4>,
	selected.fg => #FFFFFF,
	selected.border => #000000,
	special.fg => #FFFFFF,
	special.border => #000000,
	special.bg => <vert #111111 to #363636 to #4D4D4D>
button:
	default.bg => #FFFFFF,
	default.fg => #000000,
	default.border => #000000,
	selected.bg => <vert #6F6F6F to #9A9A9A to #B4B4B4>,
	selected.fg => #FFFFFF,
	selected.border => #000000
