\name iTunes 7.0
# by Armon Khosravi
# Generated by iPL Color Scheme Editor

header:
	bg => <vert #C5C4C3 to #979596>,
	line => #404040,
	gradient.top => #000000,
	fg => #394351
menu:
	bg => #D2D8E2,
	fg => #000000,
	choice => #000000,
	selbg => <vert #336687 to #11222D to #336687>,
	selfg => #FFFFFF,
	selchoice => #000000,
	icon0 => #FFFFFF,
	icon => #336687,
	icon1 => #FFFFFF,
	icon2 => #FFFFFF
scroll:
	box => #B7B7B7,
	bg => #EDEDED,
	bar => <horiz #778791 to #4780A0>
textarea:
	bg => #D2D8E1,
	fg => #11161A
window:
	bg => #D2D8E1,
	fg => #11222D,
	border => #112733
dialog:
	bg => #5B6F8C,
	fg => #C0C0C0,
	line => #11222D,
	title.fg => #FFFFFF,
	button.bg => #22445A,
	button.fg => #C0C0C0,
	button.border => #FFFFFF,
	button.sel.bg => #C0C0C0,
	button.sel.fg => #11222D,
	button.sel.border => #FFFFFF,
	button.sel.inner => #004080
error:
	bg => #5B6F8C,
	title.fg => #FFFFFF,
	fg => #C0C0C0,
	button.bg => #22445A,
	line => #11222D,
	button.fg => #C0C0C0,
	button.border => #FFFFFF,
	button.sel.bg => #C0C0C0,
	button.sel.fg => #11222D,
	button.sel.border => #FFFFFF,
	button.sel.inner => #004080
music:
	bar.bg => #FFFFFF,
	bar => <vert #C0C0C0 to #004080>
slider:
	bg => #FFFFFF,
	border => #C0C0C0,
	full => <vert #336687 to #C0C0C0 to #336687>
input:
	bg => #5B6F8C,
	fg => #C0C0C0,
	selbg => #22445A,
	selfg => #FFFFFF,
	border => #004080,
	cursor => #11222D
box:
	default.bg => <vert #22445A to #C0C0C0>,
	default.fg => #C0C0C0,
	default.border => #004080,
	special.bg => #22445A,
	special.fg => #C0C0C0,
	special.border => #004080,
	selected.bg => <vert #C0C0C0 to #22445A>,
	selected.fg => #11222D,
	selected.border => #FFFF00
button:
	default.bg => <vert #22445A to #C0C0C0>,
	default.fg => #C0C0C0,
	default.border => #004080,
	selected.bg => #22445A,
	selected.fg => #C0C0C0,
	selected.border => #0080C0
loadavg:
	bg => <vert #5B6F8C to #C0C0C0>,
	fg => #22445A,
	spike => #004080
lock:
	border => #004080,
	fill => #22445A
battery:
	border => #000000,
	bg => <vert #11222D to #004080>,
	bg.low => <vert #11222D to #0000A0>,
	bg.charging => #5B6F8C,
	fill.normal => #0080FF,
	chargingbolt => #FFFF00,
	fill.charge => #004080,
	fill.low => <vert #11222D to #0080FF>
