\name Mango Guava
# by Jonathynne Bettencourt
# Generated by iPL Color Scheme Editor

menu:
	bg => <horiz #FF7E00 to #FF7E00 to #FFFF00>,
	fg => #000000,
	choice => #000000,
	icon => #000000,
	selbg => <vert #00FF00 to #0000FF>,
	selfg => #7E0000,
	selchoice => #FF0000,
	icon0 => #000000,
	icon3 => #FF0000,
	icon1 => #570000,
	icon2 => #B10000
scroll:
	box => #000000,
	bar => <horiz #0000FF to #FF00FF>,
	bg => <horiz #FFCCFF to #FFFFFF>
header:
	line => #000000,
	bg => <vert #00FF00 to #FFFF00>,
	fg => #B800FF,
	gradient.top => #00FF00,
	gradient.bottom => #FFFD00,
	gradient.middle => #00FFFF,
	gradient.bar => #00C4FF,
	accent => #00E17C,
	shadow => #00D200,
	shine => #E3E300
window:
	bg => #FFFFFF,
	fg => #000000,
	border => #5BAD00
music:
	bar.bg => <vert #FDFF7E to #7EFF7E>,
	bar => <vert #0000FF to #FF00FF>
loadavg:
	bg => #00DD00,
	fg => #00FF00,
	spike => #FFFF00
lock:
	fill => #FF0000,
	border => #D40000
battery:
	border => #0000FF,
	bg => <vert #FFFFFF to #D6D6D6 to #FFFFFF>,
	fill.normal => <vert #00FFFF to #FF7EFF>,
	bg.low => <vert #FFE9E9 to #FFC4C4 to #FFEDED>,
	fill.low => <vert #FF0000 to #FF00FF>,
	bg.charging => <vert #FFFFFF to #C0FFC0 to #FFFDFF>,
	fill.charge => <vert #00FF00 to #E500FF>,
	chargingbolt => #FF0000
box:
	default.bg => <vert #BCFFC8 to #3AFFBA>,
	default.fg => #7E00FF,
	default.border => #007EFF,
	selected.bg => <vert #00B880 to #00C0FF to #00CE80>,
	selected.fg => #000000,
	selected.border => #0000C6,
	special.bg => <vert #FFC8FD to #95FDBA>,
	special.fg => #FF00FF,
	special.border => #AD00FF
button:
	default.bg => <vert #B8E9FF to #BEADFF to #00CEFF>,
	default.fg => #0000C2,
	default.border => #0000D4,
	selected.bg => <vert #D000FF to #FF00FF to #90C4FF>,
	selected.fg => #000000,
	selected.border => #000000
input:
	bg => <vert #FFEDFF to #FFFDFF to #FFEBFF>,
	fg => #6B0093,
	selbg => <vert #FF00FF to #FFFF00 to #FF00FF>,
	selfg => #FF0000,
	border => #2CFF28,
	cursor => #FF8800
textarea:
	bg => #E1FFE3,
	fg => #000095
slider:
	border => #009590,
	full => <vert #FF0095 to #8ED6F7>,
	bg => <vert #D2FBE3 to #E7F9FF>
dialog:
	bg => <vert #FFC400 to #FFFF00>,
	fg => #000000,
	line => #800000,
	title.fg => #7A007A,
	button.bg => <vert #FFFF00 to #CAFFAF to #FFFFBA>,
	button.fg => #005300,
	button.border => #009D9D,
	button.sel.bg => <vert #FFD000 to #FF67B3 to #EFC200>,
	button.sel.fg => #000000,
	button.sel.border => #00BA00,
	button.sel.inner => #00FF00
error:
	bg => <vert #FF0000 to #FFFF00>,
	fg => #000000,
	line => #FF00FF,
	title.fg => #447400,
	button.bg => <vert #FFFFFF to #FFDFE1 to #FFFFFF>,
	button.fg => #FF0000,
	button.border => #C60000,
	button.sel.bg => <vert #FF0000 to #0000FD>,
	button.sel.fg => #FFFFFF,
	button.sel.border => #C600C6,
	button.sel.inner => #FF00FD
