\name Tom-Bob
# by Tgifman1
# Generated by iPL Color Scheme Editor
\def color1 #008000
\def color2 #000000
\def color3 #80FF00
\def color4 <vert #008040 to #66FF66>
\def color5 @Matrix_wallpaper_2.bmp
\def color6 #000000

header:
	bg => <horiz color2 to color1 to color2>,
	fg => color2,
	line => <horiz #00FF00 to #008040>,
	accent => <vert #00FF00 to #008040>,
	shadow => color2,
	gradient.middle => @Matrix_wallpaper_2.jpg,
	gradient.top => @Matrix_wallpaper_2.jpg,
	shine => @Matrix_wallpaper_2.jpg,
	gradient.bottom => @Matrix_wallpaper_2.jpg,
	gradient.bar => @Matrix_wallpaper_2.jpg
music:
	bar => <horiz color1 to color2> *6,
	bar.bg => #408000
window:
	bg => @Matrix_wallpaper_2.jpg,
	fg => #FFFFFF,
	border => #CCCCCC
dialog:
	bg => color2,
	fg => #FFFFFF,
	line => #B3B3B3,
	title.fg => #FFFFFF,
	button.bg => <vert #408000 to #008040>,
	button.fg => color2,
	button.border => #FFFFFF,
	button.sel.bg => color1,
	button.sel.fg => #CCCCCC,
	button.sel.border => #4C4C4C,
	button.sel.inner => #333333
error:
	bg => #333333,
	fg => #FFFFFF,
	line => #FFFFFF,
	title.fg => #FFFFFF,
	button.bg => #008040,
	button.fg => #FFFFFF,
	button.border => #CCCCCC,
	button.sel.bg => color1,
	button.sel.fg => #FFFFFF,
	button.sel.border => #CCCCCC,
	button.sel.inner => color2
menu:
	bg => @Matrix_wallpaper_2.jpg,
	fg => #FFFFFF,
	choice => color2,
	icon => color1,
	selbg => <horiz #408000 to color2>,
	selfg => color2,
	selchoice => color2,
	icon0 => #666666,
	icon1 => #E6E6E6,
	icon2 => #CCCCCC,
	icon3 => #B3B3B3
scroll:
	box => #008040,
	bg => #7F7F7F,
	bar => #408000
slider:
	border => #FFFFFF,
	bg => #008040,
	full => #00FF00
textarea:
	fg => #FFFFFF
input:
	bg => #4C4C4C,
	fg => #FFFFFF,
	selbg => color1,
	selfg => color2,
	border => #CCCCCC,
	cursor => #00FF00
box:
	default.fg => #FFFFFF,
	default.border => #999999,
	selected.bg => #00FF00,
	selected.fg => color2,
	selected.border => #FFFFFF,
	special.bg => #B3B3B3,
	special.fg => #FFFFFF,
	special.border => #FFFFFF,
	default.bg => color1
button:
	default.fg => #FFFFFF,
	default.border => #B3B3B3,
	selected.bg => #333333,
	selected.fg => #00FF00,
	selected.border => #00FF00,
	default.bg => color1
battery:
	border => #FFFFFF,
	bg => color1,
	bg.low => #00FF00,
	bg.charging => color2,
	fill.normal => #00FF00,
	fill.low => #FFFFFF,
	fill.charge => color2,
	chargingbolt => color1
loadavg:
	bg => <vert color1 to color2>,
	fg => <vert #CCCCCC to color2>,
	spike => #FFFFFF
lock:
	border => color1,
	fill => color2
