\name Metallic
# by Owen McGarry
# Generated by iPL Color Scheme Editor

header:
	bg => @Metallic.titlebar.png,
	fg => #000000
window:
	bg => #FFFFFF,
	fg => #000000,
	border => #000000
music:
	bar.bg => <vert #C5C5C5 to #EEEEEE to #DEDEDE>,
	bar => <vert #0C0C0C to #393939 to #292929>
lock:
	border => #000000,
	fill => <vert #0C0C0C to #393939 to #292929>
battery:
	border => #000000,
	fill.normal => <vert #0C0C0C to #393939 to #292929>,
	fill.low => <vert #C00000 to #DB0000 to #BC0000>,
	fill.charge => <vert #C5C5C5 to #EEEEEE to #DEDEDE>,
	chargingbolt => #FBFA00
dialog:
	bg => #FFFFFF,
	fg => #000000,
	line => #000000,
	title.fg => #000000,
	button.bg => <vert #C5C5C5 to #EEEEEE to #DEDEDE>,
	button.fg => #000000,
	button.border => #000000,
	button.sel.bg => <vert #0C0C0C to #393939 to #292929>,
	button.sel.fg => #FFFFFF,
	button.sel.border => #000000
error:
	bg => #FFFFFF,
	fg => #000000,
	line => #000000,
	title.fg => #000000,
	button.bg => <vert #C5C5C5 to #EEEEEE to #DEDEDE>,
	button.fg => #000000,
	button.border => #000000,
	button.sel.border => #000000,
	button.sel.fg => #FFFFFF,
	button.sel.bg => <vert #0C0C0C to #393939 to #292929>
menu:
	bg => #FFFFFF,
	fg => #000000,
	choice => #000000,
	icon => #000000,
	selchoice => #000000,
	icon0 => #000000,
	icon1 => #000000,
	icon2 => #000000,
	icon3 => #000000,
	selbg => <vert #0C0C0C to #393939 to #292929>,
	selfg => #FFFFFF
scroll:
	bg => <horiz #C5C5C5 to #E5E5E5 to #DEDEDE>,
	bar => <horiz #0C0C0C to #393939 to #292929>
slider:
	border => #000000,
	bg => <vert #C5C5C5 to #EEEEEE to #DEDEDE>,
	full => <vert #0C0C0C to #393939 to #292929>
textarea:
	bg => #FFFFFF,
	fg => #000000
input:
	bg => #FFFFFF,
	fg => #000000,
	selbg => <vert #0C0C0C to #393939 to #292929>,
	selfg => #FFFFFF,
	border => #000000,
	cursor => #000000
box:
	default.bg => #FFFFFF,
	default.fg => #000000,
	default.border => #000000,
	selected.bg => <vert #0C0C0C to #393939 to #292929>,
	selected.fg => #FFFFFF,
	selected.border => #000000,
	special.fg => #000000,
	special.border => #000000,
	special.bg => <vert #C5C5C5 to #EEEEEE to #DEDEDE>
button:
	default.bg => #FFFFFF,
	default.fg => #000000,
	default.border => #000000,
	selected.fg => #FFFFFF,
	selected.border => #000000,
	selected.bg => <vert #0C0C0C to #393939 to #292929>
