\name Muse
# Baced offa' IPW scheme
# by Owen McGarry
# Generated by iPL Color Scheme Editor
\def color2 <vert #C76400 to #DC6E00 to #FF8000>

header:
	bg => @Muse.bar.png,
	fg => #000000,
	line => #FFFFFF,
	accent => #FFFFFF,
	shadow => #FFFFFF
music:
	bar.bg => @Muse.Barempty.png,
	bar => @Muse.Barfull.png
scroll:
	bg => @Muse.Scrollempty.png,
	bar => @Muse.Scrollfull.png,
	box => #000000
lock:
	border => #000000,
	fill => #FF8000
window:
	bg => #FFFFFF,
	fg => #000000,
	border => #000000
dialog:
	bg => #FFFFFF,
	fg => #000000,
	line => #000000,
	title.fg => #000000,
	button.bg => color2,
	button.fg => #000000,
	button.border => #000000,
	button.sel.bg => color2,
	button.sel.fg => #FFFFFF,
	button.sel.border => #000000
error:
	bg => #FFFFFF,
	fg => #000000,
	line => #000000,
	title.fg => #000000,
	button.bg => color2,
	button.fg => #000000,
	button.border => #000000,
	button.sel.bg => color2,
	button.sel.fg => #FFFFFF,
	button.sel.border => #000000
menu:
	selbg => color2,
	bg => #FFFFFF,
	fg => #000000,
	choice => #000000,
	icon => #000000,
	selfg => #000000,
	selchoice => #000000,
	icon0 => #000000,
	icon1 => #000000
slider:
	bg => @Muse.Barempty.png,
	full => @Muse.Barfull.png
textarea:
	bg => #FFFFFF,
	fg => #000000
input:
	bg => #FFFFFF,
	fg => #000000,
	selbg => color2,
	selfg => #FFFFFF,
	border => #000000,
	cursor => #000000
box:
	default.bg => #FFFFFF,
	default.fg => #000000,
	default.border => #000000,
	selected.bg => color2,
	selected.fg => #FFFFFF,
	selected.border => #000000,
	special.bg => <vert #D8D8D8 to #E6E6E6 to #CCCCCC>,
	special.fg => #000000,
	special.border => #000000
button:
	default.bg => #FFFFFF,
	default.fg => #000000,
	default.border => #000000,
	selected.bg => color2,
	selected.fg => #FFFFFF,
	selected.border => #000000
battery:
	border => #000000,
	bg.low => <vert #FF0000 to #CD0202 to #A80101>,
	bg.charging => #FF0000,
	fill.normal => <vert #008000 to #009E01 to #00C902>,
	chargingbolt => #FFFF00
