\name New Tech High
# by Jonathynne Bettencourt
# Generated by iPL Color Scheme Editor
\def black #000000
\def white #FFFFFF
\def purple #662A85
\def silver #E5E5E5
\def ltpurple #CC8CFF

menu:
	bg => silver,
	fg => purple,
	choice => purple,
	icon => purple,
	selbg => <vert purple to ltpurple to purple>,
	selfg => white,
	selchoice => white,
	icon0 => silver,
	icon1 => #FFBBF3,
	icon2 => ltpurple,
	icon3 => purple
window:
	bg => silver,
	fg => black,
	border => ltpurple
header:
	bg => @newtech-header.png,
	line => purple,
	fg => purple,
	accent => ltpurple,
	shadow => purple,
	shine => ltpurple,
	gradient.top => silver,
	gradient.middle => ltpurple,
	gradient.bottom => ltpurple,
	gradient.bar => ltpurple
scroll:
	box => black,
	bar => <horiz purple to ltpurple to purple>,
	bg => <horiz silver to white to silver>
textarea:
	bg => silver,
	fg => black
slider:
	border => black,
	bg => <vert silver to white to silver>,
	full => <vert purple to ltpurple to purple>
music:
	bar => <vert purple to ltpurple to purple>,
	bar.bg => <vert silver to white to silver>
loadavg:
	bg => ltpurple,
	fg => purple,
	spike => #FF0000
lock:
	border => purple,
	fill => ltpurple
battery:
	border => purple,
	bg => <vert silver to white>,
	bg.low => <vert #FFC6C6 to white>,
	bg.charging => <vert #BEFFBE to white>,
	fill.normal => <vert purple to ltpurple to purple>,
	fill.low => <vert purple to #FF0000 to purple>,
	fill.charge => <vert purple to silver to purple>,
	chargingbolt => #00BF17
dialog:
	bg => <vert ltpurple to white>,
	fg => purple,
	line => purple,
	title.fg => purple,
	button.bg => <vert white to silver to white>,
	button.fg => purple,
	button.border => purple,
	button.sel.bg => <vert ltpurple to silver to ltpurple>,
	button.sel.fg => purple,
	button.sel.border => purple,
	button.sel.inner => ltpurple
error:
	bg => <vert #FFDBDB to white>,
	fg => purple,
	line => purple,
	title.fg => #E90063,
	button.bg => <vert white to #FFDFFF to white>,
	button.fg => purple,
	button.border => purple,
	button.sel.bg => <vert purple to ltpurple to purple>,
	button.sel.fg => white,
	button.sel.border => ltpurple,
	button.sel.inner => #FFBBF3
input:
	bg => white,
	fg => black,
	selbg => <vert purple to ltpurple to purple>,
	selfg => white,
	border => ltpurple,
	cursor => purple
box:
	default.bg => <vert white to silver>,
	default.fg => purple,
	default.border => purple,
	selected.bg => <vert ltpurple to purple>,
	selected.fg => white,
	selected.border => black,
	special.bg => <vert silver to ltpurple>,
	special.fg => purple,
	special.border => black
button:
	default.bg => <vert white to silver to white>,
	default.fg => purple,
	default.border => black,
	selected.bg => <vert purple to ltpurple to purple>,
	selected.fg => white,
	selected.border => purple
