\name Simplicity
# Based offa' IPW scheme
# by Owen McGarry
# Generated by iPL Color Scheme Editor

header:
	bg => @simple.titlebar.png,
	fg => #000000
music:
	bar.bg => @simple.barempty.png,
	bar => @simple.barfull.png
scroll:
	box => #000000,
	bg => @simple.Scrollbg.png,
	bar => @simple.scrollfg.png
slider:
	bg => @simple.barempty.png,
	full => @simple.barfull.png
lock:
	border => #000000,
	fill => <vert #B3B3B3 to #999999 to #666666>
battery:
	border => #000000,
	fill.normal => <vert #008000 to #009901 to #00BD01>,
	fill.low => <vert #A50101 to #C50202 to #E50202>,
	fill.charge => #FF8000,
	chargingbolt => #FFFF00
window:
	bg => #FFFFFF,
	fg => #000000,
	border => #000000
dialog:
	bg => #FFFFFF,
	fg => #000000,
	line => #000000,
	title.fg => #000000,
	button.fg => #000000,
	button.border => #000000,
	button.sel.fg => #FFFFFF,
	button.sel.border => #000000,
	button.bg => <vert #0000A6 to #0000C5 to #0100F5>,
	button.sel.bg => <vert #0000A6 to #0000C5 to #0100F5>
error:
	bg => #FFFFFF,
	fg => #000000,
	line => #000000,
	title.fg => #000000,
	button.bg => <vert #0000A6 to #0000C5 to #0100F5>,
	button.fg => #000000,
	button.border => #000000,
	button.sel.bg => <vert #0000A6 to #0000C5 to #0100F5>,
	button.sel.fg => #FFFFFF,
	button.sel.border => #000000
menu:
	bg => #FFFFFF,
	fg => #000000,
	choice => #000000,
	icon => #000000,
	icon0 => #000000,
	icon1 => #000000,
	selchoice => #000000,
	selfg => #FFFFFF,
	selbg => <vert #0000A6 to #0000C5 to #0100F5>
textarea:
	bg => #FFFFFF,
	fg => #000000
input:
	bg => #FFFFFF,
	fg => #000000,
	selbg => <vert #0000A6 to #0000C5 to #0100F5>,
	selfg => #FFFFFF,
	border => #000000,
	cursor => #000000
box:
	default.bg => #FFFFFF,
	default.fg => #000000,
	default.border => #000000,
	selected.bg => <vert #0000A6 to #0000C5 to #0100F5>,
	selected.fg => #FFFFFF,
	selected.border => #000000,
	special.bg => @simple.barfull.png,
	special.fg => #FFFFFF,
	special.border => #000000
button:
	default.bg => #FFFFFF,
	default.fg => #000000,
	default.border => #000000,
	selected.bg => <vert #0000A6 to #0000C5 to #0100F5>,
	selected.fg => #FFFFFF,
	selected.border => #000000
