\name smooth red
# my first :-)
# by circa27 aka adsam
# Generated by iPL Color Scheme Editor
\def black #000000
\def red #FF0000
\def titlbar @
\def dkred #B30012
\def white #FFFFFF
\def grey #C0C0C0
\def yellow #FFFF00
\def blue #0000FF

header:
	bg => <vert red to #FF8040 to dkred>,
	fg => grey,
	line => <horiz black to black>,
	accent => white,
	shadow => black,
	shine => black,
	gradient.top => <horiz black to dkred>,
	gradient.middle => <vert black to dkred to black>,
	gradient.bottom => black,
	gradient.bar => <horiz black to red to black>
window:
	bg => red,
	fg => dkred,
	border => black
music:
	bar => <vert red to #FF8040 to dkred>,
	bar.bg => black
loadavg:
	bg => black,
	fg => <vert red to #FF8040 to dkred>,
	spike => <vert red to #FF8040>
lock:
	border => black,
	fill => blue
battery:
	border => black,
	bg => black,
	bg.low => yellow,
	bg.charging => black,
	fill.normal => <horiz red to #FF8040>,
	fill.low => <horiz #FF8040 to yellow>,
	fill.charge => <horiz red to blue>,
	chargingbolt => blue
dialog:
	bg => black,
	fg => <vert red to #FF8040>,
	line => red,
	title.fg => red,
	button.bg => #FF8040,
	button.fg => black,
	button.border => red,
	button.sel.bg => blue,
	button.sel.fg => black,
	button.sel.border => red,
	button.sel.inner => dkred
error:
	bg => red,
	fg => black,
	line => black,
	title.fg => black,
	button.bg => #FF8040,
	button.fg => black,
	button.border => black,
	button.sel.bg => blue,
	button.sel.fg => black,
	button.sel.border => black,
	button.sel.inner => red
menu:
	bg => red,
	fg => black,
	choice => <vert red to #FF8040 to dkred>,
	icon => dkred,
	selbg => <vert red to #FF8040 to dkred>,
	selfg => black,
	selchoice => <vert red to #FF8040 to dkred>,
	icon0 => dkred,
	icon1 => dkred,
	icon2 => black,
	icon3 => black
scroll:
	box => black,
	bg => <vert black to black>,
	bar => <horiz red to #FF8040 to dkred>
slider:
	border => dkred,
	bg => black,
	full => <vert red to #FF8040 to black>
textarea:
	fg => black,
	bg => red
input:
	fg => black,
	selbg => black,
	selfg => dkred,
	border => black,
	cursor => black
box:
	default.bg => dkred,
	default.fg => black,
	default.border => black,
	selected.bg => blue,
	selected.fg => black,
	selected.border => black,
	special.bg => red,
	special.fg => black,
	special.border => black
button:
	default.bg => <vert red to dkred to red>,
	default.fg => black,
	default.border => black,
	selected.bg => <vert yellow to #FF8040 to yellow>,
	selected.fg => black,
	selected.border => black
