\name Solar
# by Owen McGarry
# Generated by iPL Color Scheme Editor

window:
	bg => @ v@solar.bg.png,
	fg => #FFFFFF,
	border => #000000
header:
	bg => #000000,
	fg => #FFFFFF,
	line => #FFFFFF
music:
	bar => @solar.barfull.png,
	bar.bg => @solar.barempty.png
battery:
	border => #000000,
	fill.normal => #000000,
	fill.low => <vert #EE0202 to #CC0202 to #FF0000>,
	fill.charge => #000000,
	chargingbolt => #FFFF00
dialog:
	bg => #000000,
	fg => #FFFFFF,
	line => #FFFFFF,
	title.fg => #FFFFFF,
	button.bg => #000000,
	button.fg => #FFFFFF,
	button.border => #000000,
	button.sel.bg => #000000,
	button.sel.fg => #FFFFFF,
	button.sel.border => #FFFFFF
error:
	bg => #000000,
	fg => #FFFFFF,
	line => #FFFFFF,
	title.fg => #FFFFFF,
	button.bg => #000000,
	button.fg => #FFFFFF,
	button.border => #000000,
	button.sel.bg => #000000,
	button.sel.fg => #FFFFFF,
	button.sel.border => #FFFFFF
menu:
	fg => #FFFFFF,
	selbg => <vert #232323 to #333333 to #4C4C4C>,
	selfg => #FFFFFF
scroll:
	bg => @solar.scrollbg.png,
	bar => @solar.scrollfg.png
lock:
	border => #4C4C4C,
	fill => #4C4C4C
slider:
	bg => @solar.barempty.png,
	full => @solar.barfull.png
textarea:
	bg => #000000,
	fg => #FFFFFF
input:
	bg => #000000,
	fg => #FFFFFF,
	selfg => #FFFFFF,
	selbg => <vert #232323 to #333333 to #4C4C4C>,
	cursor => #FFFFFF
box:
	default.bg => #000000,
	default.fg => #FFFFFF,
	default.border => #000000,
	selected.bg => #000000,
	selected.border => #FFFFFF,
	selected.fg => #FFFFFF,
	special.bg => <vert #232323 to #333333 to #4C4C4C>,
	special.fg => #FFFFFF,
	special.border => #000000
button:
	default.bg => #000000,
	default.fg => #FFFFFF,
	default.border => #000000,
	selected.bg => #000000,
	selected.fg => #FFFFFF,
	selected.border => #FFFFFF
