\name Velvet Revolver
# Slash rules!
# by Sean Doyle
# Generated by iPL Color Scheme Editor
\def Red #BA0000
\def Black #000000

window:
	bg => @velvetrevolver.png,
	border => #BE009B,
	fg => #BF0000
header:
	line => #BD0000,
	fg => <vert #B60000 to #B200B9>,
	shadow => #A7A9A9,
	bg => <vert Black to #800072>
music:
	bar => #BC0000,
	bar.bg => #5B5B5B
loadavg:
	bg => #7E0070,
	fg => Red,
	spike => #BD0000
lock:
	border => #B700BC,
	fill => #B800AA
battery:
	border => #B700B3,
	fill.normal => <vert #BC0000 to Black>,
	chargingbolt => #D800D1,
	fill.charge => #BE0000,
	fill.low => #BA00B6,
	bg => Black
dialog:
	fg => #DE0002,
	line => #B90002,
	title.fg => #BD0000,
	button.bg => Black,
	button.fg => #E20002,
	button.sel.bg => #BC009B,
	button.border => #BC00AA,
	button.sel.fg => Black,
	button.sel.inner => Black,
	button.sel.border => #BD00AE
error:
	fg => #D50002,
	line => #C00002,
	title.fg => #BF0000,
	button.bg => Black,
	button.fg => #C30000,
	button.border => #BD00AC,
	button.sel.bg => #BC00B2,
	button.sel.fg => Black,
	button.sel.border => #C100B9,
	button.sel.inner => Black
menu:
	bg => @select.png,
	fg => #BA0002,
	choice => #C00000,
	icon => #BD0002,
	selbg => #420042,
	selfg => #B40000,
	selchoice => Black,
	icon3 => #BD0002,
	icon0 => #BE00B6
scroll:
	box => #BE00B0,
	bg => Black,
	bar => #B50202
slider:
	border => Red,
	bg => Black,
	full => #B80000
textarea:
	bg => Black,
	fg => #F10202
input:
	bg => Black,
	fg => #E60000,
	selbg => #BC0000,
	selfg => Black,
	border => #B60001,
	cursor => #BC00B2
box:
	selected.fg => Black,
	selected.border => #BF00C4,
	special.bg => #C30002,
	special.fg => Black,
	special.border => Black,
	selected.bg => #B80206,
	default.border => Black,
	default.fg => Black,
	default.bg => #B80004
button:
	default.bg => Black,
	default.fg => Black,
	default.border => #BD0000,
	selected.bg => #B70001,
	selected.fg => Black,
	selected.border => #BE00BC
