\name Vista
# Beta, as usual
# by tuxnoob
# Generated by iPL Color Scheme Editor

header:
	bg => @n@vista_nano_bar.png p@vista_photo_bar.png v@vista_5g_bar.png,
	fg => #EBEBEB,
	accent => #808080,
	shadow => #808080,
	shine => #C0C0C0
music:
	bar => <horiz #000000 to #0D4B99>,
	bar.bg => #808080
loadavg:
	bg => #000000,
	fg => #C0C0C0,
	spike => #FFFFFF
lock:
	border => #000000,
	fill => <vert #000000 to #FFFFFF to #000000>
battery:
	border => #000000,
	bg => #585858,
	bg.low => #808080,
	bg.charging => #FFFFFF,
	fill.normal => <vert #FFB3B3 to #000000 to #FF0000>,
	fill.low => <vert #FFB3B3 to #000000 to #FF0000>,
	fill.charge => #FFFFFF,
	chargingbolt => #FF0000
window:
	bg => @n@vista_nano_back.png p@vista_photo_back.png v@vista_5g_back.png,
	fg => #DDDDDD,
	border => #C0C0C0 *2
dialog:
	bg => <horiz #000000 to #C0C0C0> *2,
	fg => #FFFFFF,
	title.fg => #808080,
	button.bg => <vert #0A609E to #060E4D to #0A609E> *2,
	button.sel.bg => <vert #0A609E to #B3D9FF to #0A609E> *2,
	button.sel.border => #C0C0C0 *2,
	button.fg => #FFFFFF,
	button.sel.fg => #000000
error:
	bg => <horiz #000000 to #C0C0C0> *2,
	fg => #FFFFFF,
	title.fg => #808080,
	button.bg => <vert #0A609E to #060E4D to #0A609E> *2,
	button.sel.bg => <vert #0A609E to #B3D9FF to #0A609E> *2,
	button.sel.border => #C0C0C0 *2,
	button.fg => #FFFFFF,
	button.sel.fg => #000000
menu:
	fg => #949494,
	selfg => #FFFFFF
scroll:
	box => #000000 *2,
	bg => <horiz #C0C0C0 to #FFFFFF> *1,
	bar => <horiz #6F6F6F to #000000> *1
slider:
	bg => #000000,
	full => #C0C0C0
textarea:
	bg => #000000,
	fg => #FFFFFF
input:
	bg => #000000 *2,
	fg => #FFFFFF,
	selbg => #C0C0C0,
	selfg => #000000,
	border => #C0C0C0,
	cursor => #FFFFFF
box:
	default.bg => <vert #000000 to #808080>,
	default.fg => #C0C0C0,
	default.border => #C0C0C0,
	selected.bg => #FFFFFF,
	selected.fg => #000000,
	selected.border => #B30000,
	special.bg => #C0C0C0,
	special.fg => #FFFFFF,
	special.border => #000000
button:
	default.bg => <vert #000000 to #808080>,
	default.fg => #FFFFFF,
	default.border => #C0C0C0,
	selected.fg => #000000,
	selected.bg => #C0C0C0,
	selected.border => #FFFFFF
