/***************************************************************************
 * Offline achievements browser for the iPodJS Extras menu.
 *
 * Artwork and catalogs are generated by RockPod.  This plugin never uses
 * playback memory and performs image decoding only after input settles.
 ****************************************************************************/

#include "plugin.h"
#include "bmp.h"

#define ACH_ROOT ROCKBOX_DIR "/achievements"
#define ACH_CURRENT ACH_ROOT "/current"
#define ACH_SESSIONS ACH_ROOT "/state/sessions.v1.tsv"
#define ACH_UNLOCKS ACH_ROOT "/state/unlocks.v1.tsv"
#define ACH_EVENTS ACH_ROOT "/state/events.v1.tsv"
#define ACH_AVATAR_ROOT ACH_ROOT "/avatar"
#define ACH_AVATAR_CURRENT ACH_AVATAR_ROOT "/current"
#define ACH_AVATAR_PREFS ACH_ROOT "/state/avatar-preferences.v1.tsv"
#define ACH_ORB ROCKBOX_DIR \
    "/ipodjs/achievements/xbox360-sphere-official.32x32x24.bmp"
#define ACH_BOOT_ROOT ROCKBOX_DIR "/ipodjs/achievements/boot"
#define MAX_GAMES 1024
#define MAX_ACHIEVEMENTS 384
#define MAX_CONSOLES 64
#define ART_BYTES BM_SCALED_SIZE(96, 96, FORMAT_NATIVE, 0)
#define AVATAR_CLIP_BYTES (1024 * 1024)
#define AVATAR_SOUND_BYTES (96 * 1024)
#define AVATAR_WIDTH 104
#define AVATAR_HEIGHT 168
#define AVATAR_PIXELS (AVATAR_WIDTH * AVATAR_HEIGHT)
#define AVATAR_TRANSPARENT 0xf81f
#define AVATAR_EMOTE_COUNT 7
#define AVATAR_TURNTABLE_CLIP 7
#define AVATAR_CLIP_COUNT 8
#define XBOX_BOOT_WIDTH 320
#define XBOX_BOOT_HEIGHT 180
#define XBOX_BOOT_SOURCE_RATE 20000
#define XBOX_BOOT_PACK_HEADER 16
#define XBOX_BOOT_MAX_FRAMES 64
#define XBOX_BOOT_INDEX_BYTES \
    (XBOX_BOOT_WIDTH * XBOX_BOOT_HEIGHT / 2)

#ifdef HAVE_LCD_COLOR
#define SILVER_TOP LCD_RGBPACK(247, 248, 249)
#define SILVER_BOTTOM LCD_RGBPACK(184, 188, 192)
#define SILVER_LINE LCD_RGBPACK(125, 130, 135)
#define GREEN_TOP LCD_RGBPACK(139, 201, 37)
#define GREEN_BOTTOM LCD_RGBPACK(70, 132, 15)
#define GREEN_DARK LCD_RGBPACK(45, 92, 9)
#define TEXT_COLOR LCD_RGBPACK(22, 24, 25)
#define MUTED_COLOR LCD_RGBPACK(82, 86, 89)
#define LOCKED_COLOR LCD_RGBPACK(111, 114, 117)
#define DASH_DARK_TOP LCD_RGBPACK(73, 77, 81)
#define DASH_DARK_BOTTOM LCD_RGBPACK(38, 41, 44)
#define DASH_PANEL LCD_RGBPACK(226, 228, 230)
#define DASH_WHITE LCD_RGBPACK(252, 252, 252)
#define CARD_SHADOW LCD_RGBPACK(151, 155, 159)
#define CARD_LINE LCD_RGBPACK(199, 202, 205)
#define BLADE_TOP LCD_RGBPACK(214, 216, 218)
#define BLADE_BOTTOM LCD_RGBPACK(137, 141, 145)
#define OVERLAY_SHADOW LCD_RGBPACK(21, 23, 25)
#else
#define SILVER_TOP LCD_WHITE
#define SILVER_BOTTOM LCD_WHITE
#define SILVER_LINE LCD_BLACK
#define GREEN_TOP LCD_BLACK
#define GREEN_BOTTOM LCD_BLACK
#define GREEN_DARK LCD_BLACK
#define TEXT_COLOR LCD_BLACK
#define MUTED_COLOR LCD_BLACK
#define LOCKED_COLOR LCD_BLACK
#define DASH_DARK_TOP LCD_BLACK
#define DASH_DARK_BOTTOM LCD_BLACK
#define DASH_PANEL LCD_WHITE
#define DASH_WHITE LCD_WHITE
#define CARD_SHADOW LCD_BLACK
#define CARD_LINE LCD_BLACK
#define BLADE_TOP LCD_WHITE
#define BLADE_BOTTOM LCD_BLACK
#define OVERLAY_SHADOW LCD_BLACK
#endif

enum achievements_screen
{
    SCREEN_GAMES = 0,
    SCREEN_ACHIEVEMENTS,
    SCREEN_DETAIL,
    SCREEN_CONSOLES,
    SCREEN_AVATAR,
    SCREEN_AVATAR_SETTINGS,
};

enum avatar_preference
{
    AVATAR_PREF_MOTION = 0,
    AVATAR_PREF_SOUNDS,
    AVATAR_PREF_OVER_MUSIC,
    AVATAR_PREF_IDLE,
    AVATAR_PREF_COUNT,
};

struct achievement_game
{
    char key[21];
    char title[72];
    char console[28];
    char kind[24];
    char cover[MAX_PATH];
    char achievements[MAX_PATH];
    char launch_target[MAX_PATH];
    int unlocked;
    int total;
    int earned_points;
    int total_points;
    int sessions;
    long seconds;
};

struct achievement_item
{
    char id[32];
    char title[72];
    char description[160];
    char unlocked_badge[MAX_PATH];
    char locked_badge[MAX_PATH];
    int points;
    bool unlocked;
    bool imported;
    bool ipod_hardcore;
};

static struct achievement_game games[MAX_GAMES];
static struct achievement_item achievements[MAX_ACHIEVEMENTS];
static int game_count;
static int visible_games[MAX_GAMES];
static int visible_game_count;
static int selected_game_row;
static int achievement_count;
static int selected_game;
static int selected_achievement;
static char consoles[MAX_CONSOLES][28];
static int console_count;
static int console_filter;
static int picker_console;
static enum achievements_screen screen;
static bool locked_only;
static long art_due;
static int art_owner = -1;
static bool art_is_achievement;
static struct bitmap art;
static unsigned char art_data[ART_BYTES];
static struct bitmap orb;
static unsigned char orb_data[BM_SCALED_SIZE(32, 32, FORMAT_NATIVE, 0)];
static bool orb_loaded;
static char known_unlocks[MAX_ACHIEVEMENTS][32];
static bool known_unlock_hardcore[MAX_ACHIEVEMENTS];
static int known_unlock_count;
static enum achievements_screen avatar_return_screen;
static char avatar_generation[40];
static char avatar_name[24] = "OFFLINE PLAYER";
static int avatar_games;
static int avatar_unlocked;
static int avatar_total;
static int avatar_score;
static int avatar_clip;
static int avatar_emote_clip;
static int avatar_turntable_frame;
static int avatar_settings_row;
static int avatar_motion = 2;
static int avatar_sound_mode = 2;
static bool avatar_sounds_over_music = true;
static bool avatar_idle_emotes = true;
static bool avatar_paused;
static bool avatar_pack_loaded;
static bool avatar_profile_checked;
static bool avatar_clip_loaded;
static bool avatar_clip_pending;
static bool avatar_rav2;
static bool avatar_opaque;
static bool avatar_keyframes;
static long avatar_clip_due;
static long avatar_frame_started;
static long avatar_enter_started;
static int avatar_frame;
static int avatar_frame_count;
static int avatar_frame_ms;
static int avatar_width;
static int avatar_height;
static size_t avatar_clip_size;
static uint32_t avatar_offsets[24];
static unsigned char avatar_clip_data[AVATAR_CLIP_BYTES];
static fb_data avatar_pixels[AVATAR_PIXELS];
#ifndef HAVE_HARDWARE_BEEP
static unsigned char avatar_sound_data[AVATAR_SOUND_BYTES] CACHEALIGN_ATTR;
static size_t avatar_sound_size;
static uint32_t avatar_sound_offsets[3];
static uint32_t avatar_sound_lengths[3];
static bool avatar_sound_loaded;
static const unsigned char *xbox_boot_audio;
static size_t xbox_boot_audio_size;
static size_t xbox_boot_audio_position;
static unsigned int xbox_boot_audio_phase;
static unsigned int xbox_boot_output_rate;
#endif

static const char *avatar_clip_ids[AVATAR_CLIP_COUNT] = {
    "jump", "throw", "faint", "sit-idle", "punch", "kick", "walk",
    "turntable"
};

static const char *avatar_clip_labels[AVATAR_CLIP_COUNT] = {
    "Jump", "Throw", "Faint", "Sit Idle", "Punch", "Kick", "Walk",
    "360 Model"
};

#ifdef BUTTON_PLAY
static const struct button_mapping avatar_button_map[] = {
    { ACTION_WPS_PLAY, BUTTON_PLAY | BUTTON_REL, BUTTON_PLAY },
    LAST_ITEM_IN_LIST__NEXTLIST(CONTEXT_STD)
};

static const struct button_mapping *avatar_get_context_map(int context)
{
    (void)context;
    return avatar_button_map;
}
#endif

static const char *console_filter_name(int filter);

static char *next_field(char **cursor)
{
    char *start = *cursor;
    char *tab;

    if (!start)
        return "";
    tab = rb->strchr(start, '\t');
    if (tab)
    {
        *tab = '\0';
        *cursor = tab + 1;
    }
    else
        *cursor = NULL;
    return start;
}

static void copy_field(char *destination, size_t size, char **cursor)
{
    rb->strlcpy(destination, next_field(cursor), size);
}

static int int_field(char **cursor)
{
    return rb->atoi(next_field(cursor));
}

static uint16_t read_le16(const unsigned char *data)
{
    return (uint16_t)data[0] | ((uint16_t)data[1] << 8);
}

static uint32_t read_le32(const unsigned char *data)
{
    return (uint32_t)data[0] | ((uint32_t)data[1] << 8) |
           ((uint32_t)data[2] << 16) | ((uint32_t)data[3] << 24);
}

static uint32_t avatar_crc32(const unsigned char *data, size_t size)
{
    uint32_t crc = 0xffffffff;
    size_t index;

    for (index = 0; index < size; ++index)
    {
        int bit;
        crc ^= data[index];
        for (bit = 0; bit < 8; ++bit)
            crc = (crc >> 1) ^ (0xedb88320 & (0 - (crc & 1)));
    }
    return ~crc;
}

static bool read_exact_file(const char *path, unsigned char *buffer,
                            size_t capacity, size_t *size)
{
    int fd = rb->open(path, O_RDONLY);
    off_t length;
    ssize_t count;

    if (fd < 0)
        return false;
    length = rb->lseek(fd, 0, SEEK_END);
    if (length <= 0 || (size_t)length > capacity ||
        rb->lseek(fd, 0, SEEK_SET) < 0)
    {
        rb->close(fd);
        return false;
    }
    count = rb->read(fd, buffer, (size_t)length);
    rb->close(fd);
    if (count != length)
        return false;
    *size = (size_t)length;
    return true;
}

#if defined(HAVE_LCD_COLOR) && LCD_WIDTH == XBOX_BOOT_WIDTH && \
    LCD_HEIGHT >= XBOX_BOOT_HEIGHT
static size_t xbox_boot_pack_size;
static unsigned char *xbox_boot_indices;
static int xbox_boot_frame_count;
static int xbox_boot_frame_ms;

#ifndef HAVE_HARDWARE_BEEP
static int16_t xbox_boot_mulaw_decode(unsigned char value)
{
    int sample;
    int exponent;

    value = ~value;
    exponent = (value >> 4) & 7;
    sample = (((value & 15) << 3) + 0x84) << exponent;
    sample -= 0x84;
    return (value & 0x80) ? -sample : sample;
}

static void xbox_boot_pcm_more(const void **start, size_t *size)
{
    int16_t *output = (int16_t *)avatar_pixels;
    const size_t capacity = sizeof(avatar_pixels) / (2 * sizeof(int16_t));
    size_t frames = 0;

    while (frames < capacity &&
           xbox_boot_audio_position < xbox_boot_audio_size)
    {
        int16_t sample =
            xbox_boot_mulaw_decode(xbox_boot_audio[xbox_boot_audio_position]);
        output[frames * 2] = sample;
        output[frames * 2 + 1] = sample;
        ++frames;
        xbox_boot_audio_phase += XBOX_BOOT_SOURCE_RATE;
        while (xbox_boot_audio_phase >= xbox_boot_output_rate)
        {
            xbox_boot_audio_phase -= xbox_boot_output_rate;
            ++xbox_boot_audio_position;
        }
    }
    *start = output;
    *size = frames * 2 * sizeof(int16_t);
}
#endif

static bool load_xbox_boot(void)
{
    char path[MAX_PATH];
    size_t audio_offset;
    size_t loaded_audio_size = 0;
    size_t index_offset;
    int palette_count;

    rb->snprintf(path, sizeof(path), ACH_BOOT_ROOT "/boot-320x180.nfx");
    if (!read_exact_file(path, avatar_clip_data, sizeof(avatar_clip_data),
                         &xbox_boot_pack_size) ||
        xbox_boot_pack_size < XBOX_BOOT_PACK_HEADER ||
        rb->memcmp(avatar_clip_data, "NFX1", 4) ||
        read_le16(avatar_clip_data + 4) != XBOX_BOOT_WIDTH ||
        read_le16(avatar_clip_data + 6) != XBOX_BOOT_HEIGHT)
        return false;
    xbox_boot_frame_count = read_le16(avatar_clip_data + 8);
    xbox_boot_frame_ms = read_le16(avatar_clip_data + 10);
    palette_count = read_le16(avatar_clip_data + 12);
    if (xbox_boot_frame_count <= 0 ||
        xbox_boot_frame_count > XBOX_BOOT_MAX_FRAMES ||
        xbox_boot_frame_ms < 40 || xbox_boot_frame_ms > 500 ||
        palette_count <= 0 || palette_count > 16)
        return false;
    audio_offset = (xbox_boot_pack_size + 3) & ~(size_t)3;
#ifndef HAVE_HARDWARE_BEEP
    rb->snprintf(path, sizeof(path),
                 ACH_BOOT_ROOT "/boot-20000-mono.mulaw");
    xbox_boot_audio = avatar_clip_data + audio_offset;
    xbox_boot_audio_size = 0;
    if (!read_exact_file(path, (unsigned char *)xbox_boot_audio,
                         sizeof(avatar_clip_data) - audio_offset,
                         &xbox_boot_audio_size))
        xbox_boot_audio_size = 0;
    loaded_audio_size = xbox_boot_audio_size;
#endif
    index_offset = (audio_offset + loaded_audio_size + 3) & ~(size_t)3;
    if (index_offset + XBOX_BOOT_INDEX_BYTES > sizeof(avatar_clip_data))
        return false;
    xbox_boot_indices = avatar_clip_data + index_offset;
    rb->memset(xbox_boot_indices, 0, XBOX_BOOT_INDEX_BYTES);
    return true;
}

static unsigned int xbox_boot_index_get(size_t position)
{
    unsigned char packed = xbox_boot_indices[position / 2];
    return position & 1 ? packed & 15 : packed >> 4;
}

static void xbox_boot_index_set(size_t position, unsigned int value)
{
    unsigned char *packed = &xbox_boot_indices[position / 2];

    if (position & 1)
        *packed = (*packed & 0xf0) | value;
    else
        *packed = (*packed & 0x0f) | (value << 4);
}

static bool draw_xbox_boot_frame(int frame)
{
    fb_data palette[16];
    struct viewport *viewport;
    fb_data *output;
    size_t offsets_at;
    size_t cursor;
    size_t end;
    size_t position = 0;
    int palette_count = read_le16(avatar_clip_data + 12);

    offsets_at = XBOX_BOOT_PACK_HEADER + palette_count * 2;
    if (offsets_at + (xbox_boot_frame_count + 1) * 4 >
            xbox_boot_pack_size)
        return false;
    cursor = read_le32(avatar_clip_data + offsets_at + frame * 4);
    end = read_le32(avatar_clip_data + offsets_at + (frame + 1) * 4);
    if (cursor >= end || end > xbox_boot_pack_size)
        return false;
    while (cursor + 2 <= end &&
           position < XBOX_BOOT_WIDTH * XBOX_BOOT_HEIGHT)
    {
        unsigned int token = read_le16(avatar_clip_data + cursor);
        size_t count = token & 0x7fff;

        cursor += 2;
        if (count == 0 ||
            position + count > XBOX_BOOT_WIDTH * XBOX_BOOT_HEIGHT)
            return false;
        if (token & 0x8000)
        {
            position += count;
            continue;
        }
        if (cursor + (count + 1) / 2 > end)
            return false;
        for (size_t pixel = 0; pixel < count; ++pixel)
        {
            unsigned char packed = avatar_clip_data[cursor + pixel / 2];
            unsigned int color = pixel & 1 ? packed & 15 : packed >> 4;

            if (color >= (unsigned int)palette_count)
                return false;
            xbox_boot_index_set(position + pixel, color);
        }
        cursor += (count + 1) / 2;
        position += count;
    }
    if (position != XBOX_BOOT_WIDTH * XBOX_BOOT_HEIGHT || cursor != end)
        return false;
    for (int index = 0; index < palette_count; ++index)
        palette[index] = (fb_data)read_le16(
            avatar_clip_data + XBOX_BOOT_PACK_HEADER + index * 2);
    rb->lcd_set_viewport(NULL);
    viewport = *(rb->screens[SCREEN_MAIN]->current_viewport);
    if (!viewport || !viewport->buffer || !viewport->buffer->fb_ptr)
        return false;
    output = viewport->buffer->fb_ptr +
        ((LCD_HEIGHT - XBOX_BOOT_HEIGHT) / 2) * LCD_WIDTH;
    for (position = 0;
         position < XBOX_BOOT_WIDTH * XBOX_BOOT_HEIGHT; ++position)
        output[position] = palette[xbox_boot_index_get(position)];
    rb->lcd_update();
    return true;
}

static void run_xbox_boot(void)
{
    long started;

    if (!load_xbox_boot())
        return;

    rb->button_clear_queue();
    rb->lcd_set_backdrop(NULL);
    rb->lcd_set_background(LCD_BLACK);
    rb->lcd_clear_display();
    if (!draw_xbox_boot_frame(0))
        return;

#ifndef HAVE_HARDWARE_BEEP
    xbox_boot_output_rate = rb->mixer_get_frequency();
    xbox_boot_audio_position = 0;
    xbox_boot_audio_phase = 0;
    if (xbox_boot_audio_size > 0 && xbox_boot_output_rate > 0)
    {
        rb->mixer_channel_stop(PCM_MIXER_CHAN_BEEP);
        rb->mixer_channel_set_amplitude(PCM_MIXER_CHAN_BEEP, MIX_AMP_UNITY);
        rb->mixer_channel_play_data(PCM_MIXER_CHAN_BEEP,
                                    xbox_boot_pcm_more, NULL, 0);
    }
#endif

    started = *rb->current_tick;
    for (int frame = 1; frame < xbox_boot_frame_count; ++frame)
    {
        long target = started + frame * xbox_boot_frame_ms * HZ / 1000;

        while (TIME_BEFORE(*rb->current_tick, target))
        {
            /* Ignore launch-time press/release noise. A button physically
             * held after the intro settles is an intentional skip. */
            if (*rb->current_tick - started > HZ / 2 &&
                rb->button_status() != BUTTON_NONE)
                goto stop;
            rb->sleep(1);
        }
        if (!draw_xbox_boot_frame(frame))
            break;
    }

stop:
#ifndef HAVE_HARDWARE_BEEP
    {
        long deadline = *rb->current_tick + HZ / 4;
        rb->mixer_channel_stop(PCM_MIXER_CHAN_BEEP);
        while (rb->mixer_channel_status(PCM_MIXER_CHAN_BEEP) !=
               CHANNEL_STOPPED &&
               TIME_BEFORE(*rb->current_tick, deadline))
            rb->sleep(1);
    }
#endif
    rb->button_clear_queue();
}
#else
static void run_xbox_boot(void)
{
}
#endif

static void wait_for_menu_release(void)
{
#ifdef BUTTON_MENU
    while (rb->button_status() & BUTTON_MENU)
        rb->sleep(1);
    rb->button_clear_queue();
#endif
}

static void avatar_totals_from_catalog(void)
{
    int index;

    avatar_games = game_count;
    avatar_unlocked = 0;
    avatar_total = 0;
    avatar_score = 0;
    for (index = 0; index < game_count; ++index)
    {
        avatar_unlocked += games[index].unlocked;
        avatar_total += games[index].total;
        avatar_score += games[index].earned_points;
    }
}

static void load_avatar_preferences(void)
{
    char line[96];
    int fd = rb->open(ACH_AVATAR_PREFS, O_RDONLY);

    if (fd < 0)
        return;
    rb->read_line(fd, line, sizeof(line));
    while (rb->read_line(fd, line, sizeof(line)) > 0)
    {
        char *cursor = line;
        char *key = next_field(&cursor);
        char *value = next_field(&cursor);

        if (!rb->strcmp(key, "motion"))
            avatar_motion = !rb->strcmp(value, "off") ? 0 :
                (!rb->strcmp(value, "reduced") ? 1 : 2);
        else if (!rb->strcmp(key, "sounds"))
            avatar_sound_mode = !rb->strcmp(value, "off") ? 0 :
                (!rb->strcmp(value, "achievement") ? 1 : 2);
        else if (!rb->strcmp(key, "sounds_over_music"))
            avatar_sounds_over_music = rb->strcmp(value, "off");
        else if (!rb->strcmp(key, "idle_emotes"))
            avatar_idle_emotes = rb->strcmp(value, "off");
    }
    rb->close(fd);
}

static void save_avatar_preferences(void)
{
    int fd = rb->open(ACH_AVATAR_PREFS, O_WRONLY | O_CREAT | O_TRUNC, 0666);

    if (fd < 0)
        return;
    rb->fdprintf(fd,
        "key\tvalue\n"
        "motion\t%s\n"
        "sounds\t%s\n"
        "sounds_over_music\t%s\n"
        "idle_emotes\t%s\n",
        avatar_motion == 0 ? "off" :
            (avatar_motion == 1 ? "reduced" : "full"),
        avatar_sound_mode == 0 ? "off" :
            (avatar_sound_mode == 1 ? "achievement" : "full"),
        avatar_sounds_over_music ? "on" : "off",
        avatar_idle_emotes ? "on" : "off");
    rb->close(fd);
}

static void fill_gradient(int x, int y, int width, int height,
                          unsigned top, unsigned bottom)
{
#ifdef HAVE_LCD_COLOR
    int index;
    int red_top = RGB_UNPACK_RED(top);
    int green_top = RGB_UNPACK_GREEN(top);
    int blue_top = RGB_UNPACK_BLUE(top);
    int red_bottom = RGB_UNPACK_RED(bottom);
    int green_bottom = RGB_UNPACK_GREEN(bottom);
    int blue_bottom = RGB_UNPACK_BLUE(bottom);

    for (index = 0; index < height; ++index)
    {
        int divisor = MAX(1, height - 1);
        rb->lcd_set_foreground(LCD_RGBPACK(
            red_top + (red_bottom - red_top) * index / divisor,
            green_top + (green_bottom - green_top) * index / divisor,
            blue_top + (blue_bottom - blue_top) * index / divisor));
        rb->lcd_hline(x, x + width - 1, y + index);
    }
#else
    (void)bottom;
    rb->lcd_set_foreground(top);
    rb->lcd_fillrect(x, y, width, height);
#endif
}

static void puts_fit(int x, int y, int width, const char *text)
{
    char buffer[160];
    int text_width;
    int height;
    size_t length;

    rb->strlcpy(buffer, text, sizeof(buffer));
    rb->lcd_getstringsize(buffer, &text_width, &height);
    length = rb->strlen(buffer);
    while (text_width > width && length > 3)
    {
        buffer[--length] = '\0';
        rb->lcd_getstringsize(buffer, &text_width, &height);
    }
    if (rb->strcmp(buffer, text) && length > 3)
    {
        buffer[length - 1] = '.';
        buffer[length - 2] = '.';
        buffer[length - 3] = '.';
    }
    rb->lcd_putsxy(x, y, buffer);
}

/* Right-aligned label, so a heading and its console tag cannot collide. */
static void puts_right(int right, int y, int width, const char *text)
{
    char buffer[160];
    int text_width;
    int height;
    size_t length;

    rb->strlcpy(buffer, text, sizeof(buffer));
    rb->lcd_getstringsize(buffer, &text_width, &height);
    length = rb->strlen(buffer);
    while (text_width > width && length > 3)
    {
        buffer[--length] = '\0';
        rb->lcd_getstringsize(buffer, &text_width, &height);
    }
    rb->lcd_putsxy(right - text_width, y, buffer);
}

static void puts_wrap_2(int x, int y, int width, const char *text)
{
    char original[160];
    char first[160];
    size_t length;
    size_t split;
    int text_width;
    int height;

    rb->strlcpy(original, text, sizeof(original));
    length = rb->strlen(original);
    split = length;
    rb->lcd_getstringsize(original, &text_width, &height);
    while (text_width > width && split > 1)
    {
        first[0] = '\0';
        rb->strlcpy(first, original, split);
        --split;
        first[split] = '\0';
        rb->lcd_getstringsize(first, &text_width, &height);
    }
    if (split >= length)
    {
        rb->lcd_putsxy(x, y, original);
        return;
    }
    while (split > 1 && original[split] != ' ')
        --split;
    if (split <= 1)
        split = MIN(length, (size_t)24);
    rb->strlcpy(first, original, split + 1);
    puts_fit(x, y, width, first);
    while (original[split] == ' ')
        ++split;
    puts_fit(x, y + 16, width, original + split);
}

static void header(const char *title, const char *subtitle)
{
    fill_gradient(0, 0, LCD_WIDTH, 39, SILVER_TOP, SILVER_BOTTOM);
    rb->lcd_set_foreground(SILVER_LINE);
    rb->lcd_hline(0, LCD_WIDTH - 1, 38);
    if (orb_loaded)
        rb->lcd_bitmap_part((fb_data *)orb.data, 0, 0, orb.width, 7, 3,
                            orb.width, orb.height);
    rb->lcd_set_foreground(TEXT_COLOR);
    puts_fit(45, 4, LCD_WIDTH - 53, title);
    rb->lcd_set_foreground(MUTED_COLOR);
    puts_fit(45, 21, LCD_WIDTH - 53, subtitle);
}

static void guide_footer(const char *text)
{
    fill_gradient(0, LCD_HEIGHT - 18, LCD_WIDTH, 18,
                  DASH_DARK_TOP, DASH_DARK_BOTTOM);
    rb->lcd_set_foreground(GREEN_TOP);
    rb->lcd_hline(0, LCD_WIDTH - 1, LCD_HEIGHT - 18);
    rb->lcd_set_foreground(LCD_WHITE);
    puts_fit(10, LCD_HEIGHT - 14, LCD_WIDTH - 18, text);
}

static void draw_blade_rail(int active)
{
    int index;

    for (index = 0; index < 3; ++index)
    {
        int x = index * 8;
        unsigned top = index == active ? GREEN_TOP : BLADE_TOP;
        unsigned bottom = index == active ? GREEN_BOTTOM : BLADE_BOTTOM;

        fill_gradient(x, 39, 8, LCD_HEIGHT - 57, top, bottom);
        rb->lcd_set_foreground(index == active ? GREEN_DARK : SILVER_LINE);
        rb->lcd_vline(x + 7, 39, LCD_HEIGHT - 19);
    }
}

static void draw_card(int x, int y, int width, int height, bool selected)
{
    rb->lcd_set_foreground(CARD_SHADOW);
    rb->lcd_fillrect(x + 2, y + 2, width, height);
    if (selected)
        fill_gradient(x, y, width, height, GREEN_TOP, GREEN_BOTTOM);
    else
    {
        rb->lcd_set_foreground(DASH_WHITE);
        rb->lcd_fillrect(x, y, width, height);
        rb->lcd_set_foreground(CARD_LINE);
        rb->lcd_drawrect(x, y, width, height);
    }
}

static bool load_art(const char *path)
{
    int result;

    rb->memset(&art, 0, sizeof(art));
    art.data = art_data;
    result = rb->read_bmp_file(path, &art, sizeof(art_data),
                               FORMAT_NATIVE, NULL);
    return result > 0;
}

static void schedule_art(void)
{
    art_owner = -1;
    art_due = *rb->current_tick + HZ / 7;
}

static bool load_due_art(void)
{
    const char *path = "";
    int owner;

    if (!TIME_AFTER(*rb->current_tick, art_due))
        return false;
    if (screen == SCREEN_GAMES && game_count > 0)
    {
        owner = selected_game;
        path = games[selected_game].cover;
        art_is_achievement = false;
    }
    else if ((screen == SCREEN_ACHIEVEMENTS || screen == SCREEN_DETAIL) &&
             achievement_count > 0)
    {
        owner = selected_achievement;
        path = achievements[selected_achievement].unlocked ?
            achievements[selected_achievement].unlocked_badge :
            achievements[selected_achievement].locked_badge;
        art_is_achievement = true;
    }
    else
        return false;
    if (art_owner == owner &&
        art_is_achievement == (screen != SCREEN_GAMES))
        return false;
    art_owner = load_art(path) ? owner : -2;
    return true;
}

static bool load_avatar_profile(void)
{
    char path[MAX_PATH];
    char line[160];
    int fd;

    avatar_profile_checked = true;
    fd = rb->open(ACH_AVATAR_CURRENT, O_RDONLY);
    if (fd < 0 || rb->read_line(fd, avatar_generation,
                                sizeof(avatar_generation)) <= 0)
    {
        if (fd >= 0)
            rb->close(fd);
        avatar_pack_loaded = false;
        avatar_totals_from_catalog();
        return false;
    }
    rb->close(fd);
    rb->snprintf(path, sizeof(path),
                 ACH_AVATAR_ROOT "/generations/%s/profile.v1.tsv",
                 avatar_generation);
    fd = rb->open(path, O_RDONLY);
    if (fd < 0)
    {
        avatar_pack_loaded = false;
        avatar_totals_from_catalog();
        return false;
    }
    avatar_totals_from_catalog();
    rb->read_line(fd, line, sizeof(line));
    while (rb->read_line(fd, line, sizeof(line)) > 0)
    {
        char *cursor = line;
        char *key = next_field(&cursor);
        char *value = next_field(&cursor);

        if (!rb->strcmp(key, "display_name"))
            rb->strlcpy(avatar_name, value, sizeof(avatar_name));
        else if (!rb->strcmp(key, "favorite_clip"))
        {
            int index;
            for (index = 0; index < AVATAR_EMOTE_COUNT; ++index)
                if (!rb->strcmp(value, avatar_clip_ids[index]))
                    avatar_emote_clip = index;
        }
        else if (!rb->strcmp(key, "games"))
            avatar_games = rb->atoi(value);
        else if (!rb->strcmp(key, "unlocked"))
            avatar_unlocked = rb->atoi(value);
        else if (!rb->strcmp(key, "achievements"))
            avatar_total = rb->atoi(value);
        else if (!rb->strcmp(key, "gamerscore"))
            avatar_score = rb->atoi(value);
    }
    rb->close(fd);
    avatar_clip = AVATAR_TURNTABLE_CLIP;
    avatar_pack_loaded = true;
    return true;
}

static bool decode_avatar_frame(int frame)
{
    const unsigned char *cursor;
    const unsigned char *end;
    size_t pixel = 0;
    uint32_t offset;
    uint32_t length;

    if (!avatar_clip_loaded || frame < 0 || frame >= avatar_frame_count)
        return false;
    offset = avatar_offsets[frame];
    if (offset + 4 > avatar_clip_size)
        return false;
    length = read_le32(avatar_clip_data + offset);
    if (offset + 4 + length > avatar_clip_size)
        return false;
    cursor = avatar_clip_data + offset + 4;
    end = cursor + length;
    while (cursor + 2 <= end && pixel < (size_t)(avatar_width * avatar_height))
    {
        uint16_t command = read_le16(cursor);
        unsigned kind = avatar_rav2 ? command & 0xc000 :
                        command & 0x8000;
        size_t run = (command & (avatar_rav2 ? 0x3fff : 0x7fff)) + 1;
        cursor += 2;
        if (pixel + run > (size_t)(avatar_width * avatar_height))
            return false;
        if (avatar_rav2 && kind == 0xc000)
        {
            size_t index;
            fb_data value;

            if (cursor + 2 > end)
                return false;
            value = (fb_data)read_le16(cursor);
            cursor += 2;
            for (index = 0; index < run; ++index)
                avatar_pixels[pixel + index] = value;
        }
        else if (kind & 0x8000)
        {
            size_t index;
            if (cursor + run * 2 > end)
                return false;
            for (index = 0; index < run; ++index)
                avatar_pixels[pixel + index] =
                    (fb_data)read_le16(cursor + index * 2);
            cursor += run * 2;
        }
        else if (frame == 0 || avatar_keyframes)
            return false;
        pixel += run;
    }
    if (cursor != end || pixel != (size_t)(avatar_width * avatar_height))
        return false;
    avatar_frame = frame;
    return true;
}

static void schedule_avatar_clip(void)
{
    avatar_clip_pending = true;
    avatar_clip_due = *rb->current_tick + HZ / 8;
    avatar_clip_loaded = false;
}

static void rotate_avatar(int direction)
{
    int count = 24;

    if (avatar_clip == AVATAR_TURNTABLE_CLIP &&
        avatar_clip_loaded && avatar_frame_count > 0)
        count = avatar_frame_count;
    avatar_turntable_frame =
        (avatar_turntable_frame + direction + count) % count;
    avatar_paused = true;
    if (avatar_clip != AVATAR_TURNTABLE_CLIP)
    {
        avatar_clip = AVATAR_TURNTABLE_CLIP;
        schedule_avatar_clip();
    }
    else if (avatar_clip_loaded && avatar_keyframes)
        decode_avatar_frame(avatar_turntable_frame);
    else
        schedule_avatar_clip();
}

static bool load_avatar_clip(void)
{
    char path[MAX_PATH];
    int index;

    if (!avatar_pack_loaded)
        return false;
    rb->snprintf(path, sizeof(path),
        ACH_AVATAR_ROOT "/generations/%s/clips/%s.rav",
        avatar_generation, avatar_clip_ids[avatar_clip]);
    if (!read_exact_file(path, avatar_clip_data, sizeof(avatar_clip_data),
                         &avatar_clip_size))
        return false;
    if (avatar_clip_size < 20 ||
        (rb->memcmp(avatar_clip_data, "RAV1", 4) &&
         rb->memcmp(avatar_clip_data, "RAV2", 4)))
        return false;
    avatar_rav2 = !rb->memcmp(avatar_clip_data, "RAV2", 4);
    avatar_opaque = avatar_rav2 && (read_le16(avatar_clip_data + 12) & 4);
    avatar_keyframes = avatar_rav2 &&
                       (read_le16(avatar_clip_data + 12) & 8);
    avatar_width = read_le16(avatar_clip_data + 4);
    avatar_height = read_le16(avatar_clip_data + 6);
    avatar_frame_count = read_le16(avatar_clip_data + 8);
    avatar_frame_ms = read_le16(avatar_clip_data + 10);
    if (avatar_width <= 0 || avatar_width > AVATAR_WIDTH ||
        avatar_height <= 0 || avatar_height > AVATAR_HEIGHT ||
        avatar_frame_count <= 0 || avatar_frame_count > 24 ||
        avatar_frame_ms < 40 ||
        (size_t)(20 + avatar_frame_count * 4) > avatar_clip_size)
        return false;
    for (index = 0; index < avatar_frame_count; ++index)
    {
        avatar_offsets[index] = read_le32(avatar_clip_data + 20 + index * 4);
        if (avatar_offsets[index] >= avatar_clip_size)
            return false;
    }
    if (avatar_offsets[0] < (uint32_t)(20 + avatar_frame_count * 4) ||
        avatar_crc32(avatar_clip_data + avatar_offsets[0],
                     avatar_clip_size - avatar_offsets[0]) !=
        read_le32(avatar_clip_data + 16))
        return false;
    rb->memset(avatar_pixels, 0xff, sizeof(avatar_pixels));
    avatar_clip_loaded = true;
    avatar_frame_started = *rb->current_tick;
    if (!decode_avatar_frame(0))
        return false;
    if (avatar_clip == AVATAR_TURNTABLE_CLIP &&
        avatar_turntable_frame > 0 &&
        avatar_turntable_frame < avatar_frame_count)
    {
        avatar_frame_started = *rb->current_tick -
            avatar_turntable_frame * avatar_frame_ms * HZ / 1000;
        return decode_avatar_frame(avatar_turntable_frame);
    }
    return true;
}

#ifndef HAVE_HARDWARE_BEEP
static bool load_avatar_sounds(void)
{
    char path[MAX_PATH];
    unsigned int rate = rb->mixer_get_frequency();
    int index;

    if (!avatar_pack_loaded || (rate != 44100 && rate != 48000))
        return false;
    rb->snprintf(path, sizeof(path),
        ACH_AVATAR_ROOT "/generations/%s/sounds/ui-%u.uib",
        avatar_generation, rate);
    if (!read_exact_file(path, avatar_sound_data, sizeof(avatar_sound_data),
                         &avatar_sound_size) || avatar_sound_size < 48 ||
        rb->memcmp(avatar_sound_data, "UIB1", 4) ||
        read_le32(avatar_sound_data + 4) != rate ||
        read_le16(avatar_sound_data + 8) != 3)
        return false;
    for (index = 0; index < 3; ++index)
    {
        size_t entry = 12 + index * 12;
        avatar_sound_offsets[index] = read_le32(avatar_sound_data + entry + 4);
        avatar_sound_lengths[index] = read_le32(avatar_sound_data + entry + 8);
        if (avatar_sound_offsets[index] + avatar_sound_lengths[index] >
            avatar_sound_size)
            return false;
    }
    avatar_sound_loaded = true;
    rb->mixer_channel_set_amplitude(PCM_MIXER_CHAN_BEEP, MIX_AMP_UNITY);
    return true;
}

static void play_avatar_sound(int sound)
{
    if (avatar_sound_mode != 2 || !avatar_sound_loaded ||
        sound < 0 || sound > 2)
        return;
    if (!avatar_sounds_over_music && (rb->audio_status() & AUDIO_STATUS_PLAY))
        return;
    rb->mixer_channel_stop(PCM_MIXER_CHAN_BEEP);
    rb->mixer_channel_play_data(
        PCM_MIXER_CHAN_BEEP, NULL,
        avatar_sound_data + avatar_sound_offsets[sound],
        avatar_sound_lengths[sound]);
}
#else
static void play_avatar_sound(int sound)
{
    (void)sound;
}
#endif

static bool load_due_avatar_assets(void)
{
    bool changed = false;

    if (!avatar_profile_checked)
    {
        changed = load_avatar_profile();
        load_avatar_preferences();
#ifndef HAVE_HARDWARE_BEEP
        load_avatar_sounds();
#endif
    }
    if (avatar_clip_pending &&
        TIME_AFTER(*rb->current_tick, avatar_clip_due) &&
        rb->button_queue_count() == 0)
    {
        avatar_clip_pending = false;
        changed = load_avatar_clip() || changed;
    }
    return changed;
}

static bool advance_avatar_frame(void)
{
    long elapsed;
    int target;

    if (screen != SCREEN_AVATAR || !avatar_clip_loaded || avatar_paused ||
        avatar_motion == 0 || avatar_frame_count < 2)
        return false;
    elapsed = *rb->current_tick - avatar_frame_started;
    target = (int)((elapsed * 1000 / HZ) / avatar_frame_ms);
    if (avatar_motion == 1)
        target /= 2;
    if (avatar_clip == AVATAR_TURNTABLE_CLIP || avatar_idle_emotes)
        target %= avatar_frame_count;
    else if (target >= avatar_frame_count)
        target = avatar_frame_count - 1;
    if (target == avatar_frame)
        return false;
    if (avatar_keyframes)
        return decode_avatar_frame(target % avatar_frame_count);
    if (target < avatar_frame)
    {
        if (!decode_avatar_frame(0))
            return false;
    }
    while (avatar_frame < target)
        if (!decode_avatar_frame(avatar_frame + 1))
            return false;
    return true;
}

static bool avatar_transition_active(void)
{
    if (screen != SCREEN_AVATAR || avatar_motion == 0)
        return false;
    return !TIME_AFTER(*rb->current_tick,
                       avatar_enter_started + MAX(1, HZ / 5));
}

static bool load_catalog(void)
{
    char generation[40];
    char path[MAX_PATH];
    char line[1024];
    int fd;

    fd = rb->open(ACH_CURRENT, O_RDONLY);
    if (fd < 0 || rb->read_line(fd, generation, sizeof(generation)) <= 0)
    {
        if (fd >= 0)
            rb->close(fd);
        return false;
    }
    rb->close(fd);
    rb->snprintf(path, sizeof(path), ACH_ROOT "/generations/%s/catalog.tsv",
                 generation);
    fd = rb->open(path, O_RDONLY);
    if (fd < 0)
        return false;
    game_count = 0;
    rb->read_line(fd, line, sizeof(line));
    while (game_count < MAX_GAMES &&
           rb->read_line(fd, line, sizeof(line)) > 0)
    {
        struct achievement_game *game = &games[game_count];
        char *cursor = line;

        rb->memset(game, 0, sizeof(*game));
        copy_field(game->key, sizeof(game->key), &cursor);
        copy_field(game->title, sizeof(game->title), &cursor);
        copy_field(game->console, sizeof(game->console), &cursor);
        copy_field(game->kind, sizeof(game->kind), &cursor);
        copy_field(game->cover, sizeof(game->cover), &cursor);
        copy_field(game->achievements, sizeof(game->achievements), &cursor);
        game->unlocked = int_field(&cursor);
        game->total = int_field(&cursor);
        game->earned_points = int_field(&cursor);
        game->total_points = int_field(&cursor);
        next_field(&cursor);
        copy_field(game->launch_target, sizeof(game->launch_target), &cursor);
        if (game->key[0] && game->title[0] && game->achievements[0])
            ++game_count;
    }
    rb->close(fd);
    return game_count > 0;
}

static const char *console_filter_name(int filter)
{
    if (filter <= 0 || filter > console_count)
        return "All Games";
    return consoles[filter - 1];
}

static void collect_consoles(void)
{
    int game_index;

    console_count = 0;
    for (game_index = 0; game_index < game_count; ++game_index)
    {
        int console_index;
        bool known = false;

        for (console_index = 0; console_index < console_count;
             ++console_index)
        {
            if (!rb->strcasecmp(consoles[console_index],
                                games[game_index].console))
            {
                known = true;
                break;
            }
        }
        if (!known && console_count < MAX_CONSOLES)
            rb->strlcpy(consoles[console_count++],
                        games[game_index].console,
                        sizeof(consoles[0]));
    }
}

static void rebuild_visible_games(void)
{
    int previous_game = selected_game;
    int game_index;

    visible_game_count = 0;
    selected_game_row = 0;
    for (game_index = 0; game_index < game_count; ++game_index)
    {
        if (console_filter > 0 &&
            rb->strcasecmp(games[game_index].console,
                           console_filter_name(console_filter)))
            continue;
        visible_games[visible_game_count] = game_index;
        if (game_index == previous_game)
            selected_game_row = visible_game_count;
        ++visible_game_count;
    }
    if (visible_game_count > 0)
        selected_game = visible_games[selected_game_row];
}

static void wait_for_select_release(void)
{
    while (rb->button_status() & BUTTON_SELECT)
        rb->sleep(1);
    rb->button_clear_queue();
}

static void load_sessions(void)
{
    char line[512];
    int fd = rb->open(ACH_SESSIONS, O_RDONLY);

    if (fd < 0)
        return;
    rb->read_line(fd, line, sizeof(line));
    while (rb->read_line(fd, line, sizeof(line)) > 0)
    {
        char target[MAX_PATH];
        char *cursor = line;
        int sessions;
        long seconds;
        int index;

        copy_field(target, sizeof(target), &cursor);
        sessions = int_field(&cursor);
        seconds = rb->strtol(next_field(&cursor), NULL, 10);
        for (index = 0; index < game_count; ++index)
        {
            struct achievement_game *game = &games[index];
            if (rb->strcasecmp(target, game->launch_target))
                continue;
            game->sessions = sessions;
            game->seconds = seconds;
            if (!rb->strcmp(game->kind, "local-baseline"))
            {
                game->unlocked = (sessions >= 1) + (seconds >= 15 * 60) +
                    (seconds >= 60 * 60) + (sessions >= 10);
                game->earned_points = (sessions >= 1 ? 5 : 0) +
                    (seconds >= 15 * 60 ? 10 : 0) +
                    (seconds >= 60 * 60 ? 20 : 0) +
                    (sessions >= 10 ? 15 : 0);
            }
            break;
        }
    }
    rb->close(fd);
}

static bool imported_unlock_info(const struct achievement_game *game,
                                 const char *id, bool *imported,
                                 int *points)
{
    char line[4096];
    int fd = rb->open(game->achievements, O_RDONLY);

    if (fd < 0)
        return false;
    rb->read_line(fd, line, sizeof(line));
    while (rb->read_line(fd, line, sizeof(line)) > 0)
    {
        char row_id[32];
        char state[16];
        char *cursor = line;

        copy_field(row_id, sizeof(row_id), &cursor);
        if (rb->strcmp(row_id, id))
            continue;
        next_field(&cursor);
        next_field(&cursor);
        *points = int_field(&cursor);
        next_field(&cursor);
        next_field(&cursor);
        copy_field(state, sizeof(state), &cursor);
        *imported = !rb->strcmp(state, "unlocked");
        rb->close(fd);
        return true;
    }
    rb->close(fd);
    return false;
}

static void load_device_unlock_totals(void)
{
    char line[256];
    int fd = rb->open(ACH_UNLOCKS, O_RDONLY);

    if (fd < 0)
        return;
    rb->read_line(fd, line, sizeof(line));
    while (rb->read_line(fd, line, sizeof(line)) > 0)
    {
        char key[24];
        char id[32];
        char *cursor = line;
        int index;

        copy_field(key, sizeof(key), &cursor);
        copy_field(id, sizeof(id), &cursor);
        for (index = 0; index < game_count; ++index)
        {
            bool imported = false;
            int points = 0;

            if (rb->strcmp(key, games[index].key) ||
                !rb->strcmp(games[index].kind, "local-baseline"))
                continue;
            if (imported_unlock_info(&games[index], id, &imported, &points) &&
                !imported)
            {
                games[index].unlocked++;
                games[index].earned_points += points;
            }
            break;
        }
    }
    rb->close(fd);
}

static bool baseline_unlocked(const struct achievement_game *game,
                              const char *id)
{
    if (rb->strcmp(game->kind, "local-baseline"))
        return false;
    if (!rb->strcmp(id, "local-first-play"))
        return game->sessions >= 1;
    if (!rb->strcmp(id, "local-15-minutes"))
        return game->seconds >= 15 * 60;
    if (!rb->strcmp(id, "local-60-minutes"))
        return game->seconds >= 60 * 60;
    if (!rb->strcmp(id, "local-10-sessions"))
        return game->sessions >= 10;
    return false;
}

static void load_known_unlocks(void)
{
    char line[256];
    int fd = rb->open(ACH_UNLOCKS, O_RDONLY);

    known_unlock_count = 0;
    if (fd < 0)
        return;
    rb->read_line(fd, line, sizeof(line));
    while (known_unlock_count < MAX_ACHIEVEMENTS &&
           rb->read_line(fd, line, sizeof(line)) > 0)
    {
        char key[24];
        char source[32];
        char *cursor = line;

        copy_field(key, sizeof(key), &cursor);
        if (rb->strcmp(key, games[selected_game].key))
            continue;
        copy_field(known_unlocks[known_unlock_count],
                   sizeof(known_unlocks[known_unlock_count]), &cursor);
        next_field(&cursor);
        copy_field(source, sizeof(source), &cursor);
        known_unlock_hardcore[known_unlock_count] =
            !rb->strcmp(source, "ipod-hardcore");
        if (known_unlocks[known_unlock_count][0])
            ++known_unlock_count;
    }
    rb->close(fd);
}

static bool unlock_is_known(const char *id)
{
    int index;

    for (index = 0; index < known_unlock_count; ++index)
        if (!rb->strcmp(known_unlocks[index], id))
            return true;
    return false;
}

static bool unlock_is_ipod_hardcore(const char *id)
{
    int index;

    for (index = 0; index < known_unlock_count; ++index)
        if (!rb->strcmp(known_unlocks[index], id))
            return known_unlock_hardcore[index];
    return false;
}

static unsigned long next_event_sequence(void)
{
    char line[256];
    unsigned long sequence = 0;
    int fd = rb->open(ACH_EVENTS, O_RDONLY);

    if (fd < 0)
        return 1;
    rb->read_line(fd, line, sizeof(line));
    while (rb->read_line(fd, line, sizeof(line)) > 0)
    {
        unsigned long value = rb->strtoul(line, NULL, 10);
        if (value > sequence)
            sequence = value;
    }
    rb->close(fd);
    return sequence + 1;
}

static uint32_t achievement_notification_id(const char *game_key,
                                            const char *achievement_id)
{
    uint32_t hash = 2166136261u;
    const unsigned char *text;

    for (text = (const unsigned char *)game_key; *text; ++text)
    {
        hash ^= *text;
        hash *= 16777619u;
    }
    hash ^= ':';
    hash *= 16777619u;
    for (text = (const unsigned char *)achievement_id; *text; ++text)
    {
        hash ^= *text;
        hash *= 16777619u;
    }
    return hash ? hash : 1;
}

static void record_unlock_event(const struct achievement_item *item)
{
    long timestamp;
    unsigned long sequence;
    bool unlock_written = false;
    bool event_written = false;
    int fd;

    if (unlock_is_known(item->id) ||
        known_unlock_count >= MAX_ACHIEVEMENTS)
        return;
    timestamp = (long)rb->mktime(rb->get_time());
    sequence = next_event_sequence();
    fd = rb->open(ACH_UNLOCKS, O_WRONLY | O_CREAT | O_APPEND, 0666);
    if (fd >= 0)
    {
        if (rb->lseek(fd, 0, SEEK_END) == 0)
            rb->fdprintf(fd,
                         "game_key\tachievement_id\tunlock_time\tsource\n");
        unlock_written = rb->fdprintf(fd, "%s\t%s\t%ld\trockpod-local\n",
                     games[selected_game].key, item->id, timestamp) > 0;
        rb->close(fd);
    }
    fd = rb->open(ACH_EVENTS, O_WRONLY | O_CREAT | O_APPEND, 0666);
    if (fd >= 0)
    {
        if (rb->lseek(fd, 0, SEEK_END) == 0)
            rb->fdprintf(fd,
                         "sequence\tgame_key\tachievement_id\tevent_time\tmode\tclient\n");
        event_written = rb->fdprintf(fd,
                     "%lu\t%s\t%s\t%ld\tlocal\tipod\n", sequence,
                     games[selected_game].key, item->id, timestamp) > 0;
        rb->close(fd);
    }
    if (!unlock_written || !event_written)
        return;
    rb->strlcpy(known_unlocks[known_unlock_count++], item->id,
                sizeof(known_unlocks[0]));
    known_unlock_hardcore[known_unlock_count - 1] = false;
#ifdef HAVE_IPODJS_UI
    {
        struct notification_request request;

        rb->memset(&request, 0, sizeof(request));
        request.source = NOTIFICATION_SOURCE_ACHIEVEMENTS;
        request.kind = NOTIFICATION_ACHIEVEMENT_UNLOCKED;
        request.stable_id = achievement_notification_id(
            games[selected_game].key, item->id);
        request.timestamp = timestamp;
        rb->strlcpy(request.title, "Achievement Unlocked",
                    sizeof(request.title));
        rb->snprintf(request.body, sizeof(request.body), "%s — %s",
                     games[selected_game].title, item->title);
        rb->strlcpy(request.route, "achievements",
                    sizeof(request.route));
        rb->notification_post(&request);
    }
#endif
}

static bool load_achievements(void)
{
    char line[4096];
    int fd;
    int total_unlocked = 0;
    int earned_points = 0;

    achievement_count = 0;
    selected_achievement = 0;
    if (selected_game < 0 || selected_game >= game_count)
        return false;
    fd = rb->open(games[selected_game].achievements, O_RDONLY);
    if (fd < 0)
        return false;
    load_known_unlocks();
    rb->read_line(fd, line, sizeof(line));
    while (achievement_count < MAX_ACHIEVEMENTS &&
           rb->read_line(fd, line, sizeof(line)) > 0)
    {
        struct achievement_item *item = &achievements[achievement_count];
        char state[16];
        char *cursor = line;

        rb->memset(item, 0, sizeof(*item));
        copy_field(item->id, sizeof(item->id), &cursor);
        copy_field(item->title, sizeof(item->title), &cursor);
        copy_field(item->description, sizeof(item->description), &cursor);
        item->points = int_field(&cursor);
        copy_field(item->unlocked_badge, sizeof(item->unlocked_badge), &cursor);
        copy_field(item->locked_badge, sizeof(item->locked_badge), &cursor);
        copy_field(state, sizeof(state), &cursor);
        item->imported = !rb->strcmp(state, "unlocked");
        item->ipod_hardcore = unlock_is_ipod_hardcore(item->id);
        item->unlocked = item->imported || item->ipod_hardcore ||
            unlock_is_known(item->id) ||
            baseline_unlocked(&games[selected_game], item->id);
        if (item->unlocked)
        {
            ++total_unlocked;
            earned_points += item->points;
        }
        if (item->unlocked &&
            !rb->strcmp(games[selected_game].kind, "local-baseline"))
            record_unlock_event(item);
        if (!locked_only || !item->unlocked)
            ++achievement_count;
    }
    rb->close(fd);
    games[selected_game].unlocked = total_unlocked;
    games[selected_game].earned_points = earned_points;
    return achievement_count > 0;
}

static void draw_empty(void)
{
    rb->lcd_set_background(SILVER_TOP);
    rb->lcd_clear_display();
    rb->lcd_set_drawmode(DRMODE_FG);
    header("Achievements", "Xbox 360 Offline Profile");
    rb->lcd_set_foreground(TEXT_COLOR);
    puts_fit(20, 92, LCD_WIDTH - 40, "No achievements database found.");
    rb->lcd_set_foreground(MUTED_COLOR);
    puts_fit(20, 116, LCD_WIDTH - 40, "Sync games with RockPod first.");
    rb->lcd_update();
}

static void draw_progress(int x, int y, int width, int value, int total)
{
    int filled = total > 0 ? width * value / total : 0;

    rb->lcd_set_foreground(SILVER_LINE);
    rb->lcd_drawrect(x, y, width, 7);
    rb->lcd_set_foreground(GREEN_BOTTOM);
    if (filled > 2)
        rb->lcd_fillrect(x + 1, y + 1, filled - 2, 5);
}

static void draw_games(void)
{
    int top = MAX(0, selected_game_row - 1);
    int index;
    int total_unlocked = 0;
    int total_achievements = 0;
    int total_score = 0;
    char status[80];

    rb->lcd_set_background(SILVER_TOP);
    rb->lcd_clear_display();
    rb->lcd_set_drawmode(DRMODE_FG);
    for (index = 0; index < visible_game_count; ++index)
    {
        struct achievement_game *game = &games[visible_games[index]];

        total_unlocked += game->unlocked;
        total_achievements += game->total;
        total_score += game->earned_points;
    }
    rb->snprintf(status, sizeof(status), "%d G  |  %d achievements",
                 total_score, total_unlocked);
    header("achievements", status);
    draw_blade_rail(0);

    draw_card(35, 46, 169, 42, false);
    rb->lcd_set_foreground(GREEN_BOTTOM);
    rb->lcd_fillrect(35, 46, 5, 42);
    rb->lcd_set_foreground(TEXT_COLOR);
    puts_fit(48, 50, 148, avatar_name);
    rb->lcd_set_foreground(MUTED_COLOR);
    rb->snprintf(status, sizeof(status), "%d G   %d/%d unlocked",
                 total_score, total_unlocked, total_achievements);
    puts_fit(48, 67, 148, status);

    draw_card(212, 46, 100, 42, false);
    rb->lcd_set_foreground(MUTED_COLOR);
    puts_fit(220, 50, 84, "CONSOLE");
    rb->lcd_set_foreground(GREEN_DARK);
    puts_fit(220, 67, 84, console_filter_name(console_filter));

    rb->lcd_set_foreground(GREEN_DARK);
    rb->lcd_fillrect(35, 90, 277, 2);
    rb->lcd_set_foreground(MUTED_COLOR);
    puts_fit(36, 94, 168, "recent games");
    puts_fit(221, 94, 90, "selected");
    for (index = top; index < visible_game_count && index < top + 3; ++index)
    {
        int game_index = visible_games[index];
        struct achievement_game *game = &games[game_index];
        int y = 108 + (index - top) * 35;

        draw_card(35, y, 169, 32, index == selected_game_row);
        if (index == selected_game_row)
        {
            rb->lcd_set_foreground(GREEN_DARK);
            rb->lcd_fillrect(35, y, 5, 32);
            rb->lcd_set_foreground(LCD_WHITE);
        }
        else
            rb->lcd_set_foreground(TEXT_COLOR);
        puts_fit(46, y + 2, 150, game->title);
        rb->lcd_set_foreground(index == selected_game_row ?
                               LCD_WHITE : MUTED_COLOR);
        rb->lcd_putsxyf(46, y + 17, "%s  %d/%d", game->console,
                        game->unlocked, game->total);
    }
    if (art_owner == selected_game && !art_is_achievement && art.data)
    {
        int width = MIN(88, art.width);
        int height = MIN(88, art.height);
        int source_x = MAX(0, (art.width - width) / 2);
        int source_y = MAX(0, (art.height - height) / 2);

        rb->lcd_set_foreground(DASH_WHITE);
        rb->lcd_fillrect(219, 106, 92, 92);
        rb->lcd_bitmap_part((fb_data *)art.data, source_x, source_y,
                            art.width, 221, 108, width, height);
    }
    else
    {
        /* No cover yet: a filled plate carrying the console reads as a Guide
         * tile instead of an empty outline. */
        fill_gradient(220, 107, 90, 90, DASH_WHITE, SILVER_TOP);
        rb->lcd_set_foreground(MUTED_COLOR);
        puts_fit(226, 143, 78, games[selected_game].console);
    }
    rb->lcd_set_foreground(CARD_SHADOW);
    rb->lcd_drawrect(219, 106, 92, 92);
    rb->lcd_set_foreground(TEXT_COLOR);
    rb->lcd_putsxyf(220, 200, "%d/%d   %d G",
                    games[selected_game].unlocked,
                    games[selected_game].total,
                    games[selected_game].earned_points);
    draw_progress(220, 213, 90, games[selected_game].unlocked,
                  games[selected_game].total);
    guide_footer("SELECT View   HOLD Filter   HOLD MENU Avatar");
    rb->lcd_update();
}

static void draw_achievement_list(void)
{
    int top = MAX(0, selected_achievement - 1);
    int index;
    char subtitle[96];
    char score[80];

    rb->lcd_set_background(SILVER_TOP);
    rb->lcd_clear_display();
    rb->lcd_set_drawmode(DRMODE_FG);
    rb->snprintf(subtitle, sizeof(subtitle), "%s  |  %d G",
                 games[selected_game].console,
                 games[selected_game].earned_points);
    header(games[selected_game].title, subtitle);
    draw_blade_rail(1);
    draw_card(35, 46, 277, 37, false);
    rb->lcd_set_foreground(GREEN_BOTTOM);
    rb->lcd_fillrect(35, 46, 5, 37);
    rb->lcd_set_foreground(TEXT_COLOR);
    puts_fit(48, 49, 186,
             !rb->strcmp(games[selected_game].kind, "retroachievements") ?
             "iPOD HARDCORE" : "LOCAL ACHIEVEMENTS");
    rb->snprintf(score, sizeof(score), "%d/%d unlocked   %d G",
                 games[selected_game].unlocked, games[selected_game].total,
                 games[selected_game].earned_points);
    rb->lcd_set_foreground(MUTED_COLOR);
    puts_fit(48, 65, 188, score);
    draw_progress(245, 63, 59, games[selected_game].unlocked,
                  games[selected_game].total);
    rb->lcd_set_foreground(MUTED_COLOR);
    puts_fit(36, 89, 220, locked_only ? "locked achievements" : "achievements");
    for (index = top; index < achievement_count && index < top + 3; ++index)
    {
        struct achievement_item *item = &achievements[index];
        int y = 102 + (index - top) * 38;

        draw_card(35, y, 277, 35, index == selected_achievement);
        if (index == selected_achievement)
        {
            rb->lcd_set_foreground(GREEN_DARK);
            rb->lcd_fillrect(35, y, 5, 35);
        }
        else
        {
            rb->lcd_set_foreground(item->unlocked ?
                                   GREEN_BOTTOM : LOCKED_COLOR);
            rb->lcd_fillrect(43, y + 6, 5, 23);
        }
        rb->lcd_set_foreground(index == selected_achievement ?
                               LCD_WHITE : TEXT_COLOR);
        puts_fit(78, y + 3, 224, item->title);
        rb->lcd_set_foreground(index == selected_achievement ?
                               LCD_WHITE : MUTED_COLOR);
        rb->lcd_putsxyf(78, y + 19, "%s   %d G",
                        item->unlocked ? "Unlocked" : "Locked", item->points);
    }
    if (art_owner == selected_achievement && art_is_achievement && art.data)
        rb->lcd_bitmap_part((fb_data *)art.data, 0, 0, art.width, 44,
                            105 + (selected_achievement - top) * 38,
                            MIN(29, art.width), MIN(29, art.height));
    guide_footer(locked_only ?
                 "SELECT Open   HOLD All   MENU Games" :
                 "SELECT Open   HOLD Locked   MENU Games");
    rb->lcd_update();
}

static void draw_detail(void)
{
    struct achievement_item *item = &achievements[selected_achievement];
    char line[64];

    rb->lcd_set_background(SILVER_TOP);
    rb->lcd_clear_display();
    rb->lcd_set_drawmode(DRMODE_FG);
    header("achievement details", games[selected_game].title);
    draw_blade_rail(2);
    draw_card(35, 48, 277, 166, false);
    fill_gradient(35, 48, 277, 34,
                  item->unlocked ? GREEN_TOP : DASH_DARK_TOP,
                  item->unlocked ? GREEN_BOTTOM : DASH_DARK_BOTTOM);
    rb->lcd_set_foreground(LCD_WHITE);
    /* The heading gets the top line to itself; the console tag and score
     * share the line below it so nothing overlaps. */
    puts_fit(47, 52, 252, item->unlocked ?
             "ACHIEVEMENT UNLOCKED" : "ACHIEVEMENT LOCKED");
    puts_fit(47, 68, 170, games[selected_game].console);
    rb->snprintf(line, sizeof(line), "%d G", item->points);
    puts_right(302, 68, 70, line);

    /* Xbox Guide accent under the band. */
    rb->lcd_set_foreground(item->unlocked ? GREEN_DARK : DASH_DARK_BOTTOM);
    rb->lcd_fillrect(35, 82, 277, 2);

    /* Badge tile: a filled plate reads as a frame even with no artwork. */
    rb->lcd_set_foreground(SILVER_LINE);
    rb->lcd_fillrect(44, 92, 76, 76);
    rb->lcd_set_foreground(item->unlocked ? GREEN_TOP : DASH_DARK_TOP);
    rb->lcd_fillrect(45, 93, 74, 74);
    if (art_owner == selected_achievement && art_is_achievement && art.data)
        rb->lcd_bitmap_part((fb_data *)art.data, 0, 0, art.width, 46, 94,
                            MIN(72, art.width), MIN(72, art.height));
    rb->lcd_set_foreground(item->unlocked ? GREEN_DARK : LOCKED_COLOR);
    rb->lcd_drawrect(44, 92, 76, 76);

    rb->lcd_set_foreground(TEXT_COLOR);
    puts_fit(133, 94, 172, item->title);
    rb->lcd_set_foreground(item->unlocked ? GREEN_DARK : LOCKED_COLOR);
    rb->snprintf(line, sizeof(line), "%d Gamerscore", item->points);
    puts_fit(133, 114, 172, line);
    rb->lcd_set_foreground(SILVER_LINE);
    rb->lcd_hline(133, 300, 132);
    rb->lcd_set_foreground(MUTED_COLOR);
    puts_wrap_2(133, 140, 172, item->description);
    if (item->ipod_hardcore)
        puts_fit(133, 178, 172, "Unlocked on iPod - Hardcore");
    else if (item->imported)
        puts_fit(133, 178, 172, "Imported RA unlock");
    else if (item->unlocked)
        puts_fit(133, 178, 172, "Local iPod milestone");
    else if (!rb->strcmp(games[selected_game].kind, "retroachievements"))
        puts_fit(133, 178, 172, "iPod Hardcore challenge");
    else
        puts_fit(133, 178, 172, "Not yet unlocked");
    rb->lcd_set_foreground(SILVER_LINE);
    rb->lcd_hline(47, 300, 196);
    rb->lcd_set_foreground(MUTED_COLOR);
    if (item->ipod_hardcore)
        puts_fit(47, 199, 250, "Verified locally on this iPod");
    else if (item->imported)
        puts_fit(47, 199, 250, "Imported from RetroAchievements");
    else if (!rb->strcmp(games[selected_game].kind, "retroachievements"))
        puts_fit(47, 199, 250, "Official RA set - local iPod rules");
    else
        puts_fit(47, 199, 250, "Offline profile achievement");
    guide_footer("MENU Back");
    rb->lcd_update();
}

static int games_for_console(int filter)
{
    int count = 0;
    int index;

    if (filter == 0)
        return game_count;
    for (index = 0; index < game_count; ++index)
        if (!rb->strcasecmp(games[index].console,
                            console_filter_name(filter)))
            ++count;
    return count;
}

static void draw_console_picker(void)
{
    int option_count = console_count + 1;
    int top = MAX(0, picker_console - 2);
    int index;

    rb->lcd_set_background(DASH_DARK_BOTTOM);
    rb->lcd_clear_display();
    rb->lcd_set_drawmode(DRMODE_FG);
    header("xbox guide", "game library");
    fill_gradient(0, 39, LCD_WIDTH, LCD_HEIGHT - 57,
                  DASH_DARK_TOP, DASH_DARK_BOTTOM);
    rb->lcd_set_foreground(OVERLAY_SHADOW);
    rb->lcd_fillrect(40, 51, 248, 166);
    rb->lcd_set_foreground(DASH_WHITE);
    rb->lcd_fillrect(34, 46, 248, 166);
    fill_gradient(34, 46, 248, 38, GREEN_TOP, GREEN_BOTTOM);
    rb->lcd_set_foreground(LCD_WHITE);
    puts_fit(47, 50, 218, "FILTER BY CONSOLE");
    puts_fit(47, 66, 218, "Choose a game system");
    for (index = top; index < option_count && index < top + 5; ++index)
    {
        int y = 87 + (index - top) * 24;
        int count = games_for_console(index);

        if (index == picker_console)
        {
            fill_gradient(40, y, 236, 22,
                          GREEN_TOP, GREEN_BOTTOM);
            rb->lcd_set_foreground(LCD_WHITE);
        }
        else
            rb->lcd_set_foreground(TEXT_COLOR);
        puts_fit(49, y + 4, 184, console_filter_name(index));
        rb->lcd_set_foreground(index == picker_console ?
                               LCD_WHITE : MUTED_COLOR);
        rb->lcd_putsxyf(250, y + 4, "%d", count);
    }
    guide_footer("SELECT Apply   MENU Cancel");
    rb->lcd_update();
}

static void draw_avatar_sprite(int x, int y)
{
    int row;

    if (!avatar_clip_loaded)
        return;
    if (avatar_opaque)
    {
        rb->lcd_bitmap(avatar_pixels, x, y, avatar_width, avatar_height);
        return;
    }
    for (row = 0; row < avatar_height; ++row)
    {
        int column = 0;
        while (column < avatar_width)
        {
            int start;
            while (column < avatar_width &&
                   (uint16_t)avatar_pixels[row * avatar_width + column] ==
                   AVATAR_TRANSPARENT)
                ++column;
            start = column;
            while (column < avatar_width &&
                   (uint16_t)avatar_pixels[row * avatar_width + column] !=
                   AVATAR_TRANSPARENT)
                ++column;
            if (column > start)
                rb->lcd_bitmap_part(avatar_pixels, start, row, avatar_width,
                                    x + start, y + row, column - start, 1);
        }
    }
}

static void draw_avatar(void)
{
    char line[96];
    int shadow;
    int stage_x = 136;

    if (avatar_transition_active())
    {
        long duration = MAX(1, HZ / 5);
        long remaining = avatar_enter_started + duration - *rb->current_tick;
        stage_x += 184 * MAX(0, remaining) / duration;
    }

    rb->lcd_set_background(DASH_PANEL);
    rb->lcd_clear_display();
    rb->lcd_set_drawmode(DRMODE_FG);
    header("my xbox", "offline profile avatar");

    draw_card(8, 48, 121, 166, false);
    rb->lcd_set_foreground(GREEN_BOTTOM);
    rb->lcd_fillrect(8, 48, 6, 166);
    rb->lcd_set_foreground(TEXT_COLOR);
    puts_fit(22, 58, 99, avatar_name);
    rb->lcd_set_foreground(GREEN_DARK);
    rb->lcd_putsxyf(22, 84, "%d G", avatar_score);
    rb->lcd_set_foreground(MUTED_COLOR);
    rb->lcd_putsxyf(22, 106, "%d/%d unlocked",
                    avatar_unlocked, avatar_total);
    rb->lcd_putsxyf(22, 128, "%d games", avatar_games);
    rb->lcd_set_foreground(SILVER_LINE);
    rb->lcd_hline(22, 116, 151);
    rb->lcd_set_foreground(GREEN_DARK);
    puts_fit(22, 160, 96, avatar_clip_labels[avatar_clip]);
    rb->lcd_set_foreground(MUTED_COLOR);
    puts_fit(22, 178, 96, avatar_motion == 0 ? "Motion off" :
             (avatar_motion == 1 ? "Reduced motion" : "Full motion"));

    if (stage_x < LCD_WIDTH)
    {
        fill_gradient(stage_x, 48, 176, 166, SILVER_TOP, SILVER_BOTTOM);
        rb->lcd_set_foreground(CARD_LINE);
        rb->lcd_drawrect(stage_x, 48, 176, 166);
        for (shadow = 0; shadow < 7; ++shadow)
        {
            int inset = shadow * 6;
            rb->lcd_set_foreground(shadow < 3 ? CARD_SHADOW : SILVER_LINE);
            rb->lcd_hline(stage_x + 42 + inset,
                          stage_x + 138 - inset, 196 + shadow);
        }
        rb->lcd_set_foreground(GREEN_BOTTOM);
        rb->lcd_fillrect(stage_x, 202, 176, 12);
        if (avatar_clip_loaded)
            draw_avatar_sprite(stage_x + 36, 43);
        else
        {
            rb->lcd_set_foreground(TEXT_COLOR);
            puts_fit(stage_x + 17, 107, 142, avatar_pack_loaded ?
                     "Loading avatar..." : "Avatar pack not installed");
            rb->lcd_set_foreground(MUTED_COLOR);
            puts_fit(stage_x + 17, 128, 142, "Sync in RockPod");
        }
        if (avatar_clip == AVATAR_TURNTABLE_CLIP && avatar_frame_count > 0)
            rb->snprintf(line, sizeof(line), "%d%c  real 3D model",
                         avatar_frame * 360 / avatar_frame_count, 0xb0);
        else
            rb->snprintf(line, sizeof(line), "%s  %d frames",
                         avatar_clip_labels[avatar_clip], avatar_frame_count);
        rb->lcd_set_foreground(LCD_WHITE);
        puts_fit(stage_x + 10, 201, 156, line);
    }
    if (avatar_clip == AVATAR_TURNTABLE_CLIP)
        guide_footer(avatar_paused ?
                     "WHEEL Rotate  PLAY Auto  SELECT Emote" :
                     "WHEEL Rotate  PLAY Pause  SELECT Emote");
    else
        guide_footer(avatar_paused ?
                     "WHEEL Rotate  PLAY Resume  SELECT Replay" :
                     "WHEEL Rotate  PLAY Pause  SELECT Replay");
    rb->lcd_update();
}

static const char *avatar_setting_value(int row)
{
    if (row == AVATAR_PREF_MOTION)
        return avatar_motion == 0 ? "Off" :
            (avatar_motion == 1 ? "Reduced" : "Full");
    if (row == AVATAR_PREF_SOUNDS)
        return avatar_sound_mode == 0 ? "Off" :
            (avatar_sound_mode == 1 ? "Achievement" : "Full");
    if (row == AVATAR_PREF_OVER_MUSIC)
        return avatar_sounds_over_music ? "On" : "Off";
    return avatar_idle_emotes ? "On" : "Off";
}

static void draw_avatar_settings(void)
{
    static const char *labels[AVATAR_PREF_COUNT] = {
        "Motion", "Dashboard sounds", "Sounds over music", "Idle emotes"
    };
    int index;

    rb->lcd_set_background(DASH_DARK_BOTTOM);
    rb->lcd_clear_display();
    rb->lcd_set_drawmode(DRMODE_FG);
    header("xbox guide", "avatar preferences");
    fill_gradient(0, 39, LCD_WIDTH, LCD_HEIGHT - 57,
                  DASH_DARK_TOP, DASH_DARK_BOTTOM);
    rb->lcd_set_foreground(OVERLAY_SHADOW);
    rb->lcd_fillrect(40, 51, 248, 166);
    rb->lcd_set_foreground(DASH_WHITE);
    rb->lcd_fillrect(34, 46, 248, 166);
    fill_gradient(34, 46, 248, 38, GREEN_TOP, GREEN_BOTTOM);
    rb->lcd_set_foreground(LCD_WHITE);
    puts_fit(47, 50, 218, "AVATAR SETTINGS");
    puts_fit(47, 66, 218, "Xbox 360 presentation");
    for (index = 0; index < AVATAR_PREF_COUNT; ++index)
    {
        int y = 91 + index * 27;
        if (index == avatar_settings_row)
        {
            fill_gradient(40, y, 236, 24, GREEN_TOP, GREEN_BOTTOM);
            rb->lcd_set_foreground(LCD_WHITE);
        }
        else
            rb->lcd_set_foreground(TEXT_COLOR);
        puts_fit(49, y + 5, 154, labels[index]);
        rb->lcd_set_foreground(index == avatar_settings_row ?
                               LCD_WHITE : GREEN_DARK);
        puts_fit(209, y + 5, 60, avatar_setting_value(index));
    }
    guide_footer("SELECT Change   MENU Done");
    rb->lcd_update();
}

static void draw(void)
{
    if (screen == SCREEN_GAMES)
        draw_games();
    else if (screen == SCREEN_ACHIEVEMENTS)
        draw_achievement_list();
    else if (screen == SCREEN_DETAIL)
        draw_detail();
    else if (screen == SCREEN_CONSOLES)
        draw_console_picker();
    else if (screen == SCREEN_AVATAR)
        draw_avatar();
    else
        draw_avatar_settings();
}

static enum plugin_status finish(enum plugin_status status)
{
#ifndef HAVE_HARDWARE_BEEP
    long deadline = *rb->current_tick + HZ / 4;

    rb->mixer_channel_stop(PCM_MIXER_CHAN_BEEP);
    rb->mixer_channel_set_buffer_hook(PCM_MIXER_CHAN_BEEP, NULL);
    while (rb->mixer_channel_status(PCM_MIXER_CHAN_BEEP) !=
           CHANNEL_STOPPED && TIME_BEFORE(*rb->current_tick, deadline))
        rb->sleep(1);
#endif
    rb->lcd_set_drawmode(DRMODE_SOLID);
    return status;
}

enum plugin_status plugin_start(const void *parameter)
{
    bool loaded;

    (void)parameter;
    rb->lcd_setfont(FONT_UI);
    run_xbox_boot();
    orb.data = orb_data;
    orb_loaded = rb->read_bmp_file(ACH_ORB, &orb, sizeof(orb_data),
                                   FORMAT_NATIVE, NULL) > 0;
    loaded = load_catalog();
    if (loaded)
    {
        load_sessions();
        load_device_unlock_totals();
        avatar_totals_from_catalog();
    }
    if (!loaded)
        draw_empty();
    else
    {
        screen = SCREEN_GAMES;
        selected_game = 0;
        console_filter = 0;
        collect_consoles();
        rebuild_visible_games();
        schedule_art();
        draw();
    }

    while (true)
    {
        int action;
        bool redraw = false;

#ifdef BUTTON_PLAY
        action = rb->get_custom_action(CONTEXT_PLUGIN, HZ / 20,
                                       avatar_get_context_map);
#else
        action = rb->get_action(CONTEXT_LIST, HZ / 20);
#endif
        if (action == ACTION_NONE)
        {
            bool changed = false;

            if (loaded && load_due_art())
                changed = true;
            if (loaded && load_due_avatar_assets())
                changed = true;
            if (loaded && advance_avatar_frame())
                changed = true;
            if (loaded && avatar_transition_active())
                changed = true;
            if (changed)
                draw();
            continue;
        }
        if (!loaded)
        {
            if (action == ACTION_STD_CANCEL || action == ACTION_STD_MENU)
                return finish(PLUGIN_OK);
        }
        else switch (action)
        {
            case ACTION_STD_PREV:
            case ACTION_STD_PREVREPEAT:
                if (screen == SCREEN_GAMES && selected_game_row > 0)
                {
                    --selected_game_row;
                    selected_game = visible_games[selected_game_row];
                }
                else if ((screen == SCREEN_ACHIEVEMENTS ||
                          screen == SCREEN_DETAIL) &&
                         selected_achievement > 0)
                    --selected_achievement;
                else if (screen == SCREEN_CONSOLES && picker_console > 0)
                    --picker_console;
                else if (screen == SCREEN_AVATAR)
                    rotate_avatar(-1);
                else if (screen == SCREEN_AVATAR_SETTINGS &&
                         avatar_settings_row > 0)
                    --avatar_settings_row;
                else
                    break;
                schedule_art();
                play_avatar_sound(0);
                redraw = true;
                break;
            case ACTION_STD_NEXT:
            case ACTION_STD_NEXTREPEAT:
                if (screen == SCREEN_GAMES &&
                    selected_game_row + 1 < visible_game_count)
                {
                    ++selected_game_row;
                    selected_game = visible_games[selected_game_row];
                }
                else if ((screen == SCREEN_ACHIEVEMENTS ||
                          screen == SCREEN_DETAIL) &&
                         selected_achievement + 1 < achievement_count)
                    ++selected_achievement;
                else if (screen == SCREEN_CONSOLES &&
                         picker_console < console_count)
                    ++picker_console;
                else if (screen == SCREEN_AVATAR)
                    rotate_avatar(1);
                else if (screen == SCREEN_AVATAR_SETTINGS &&
                         avatar_settings_row + 1 < AVATAR_PREF_COUNT)
                    ++avatar_settings_row;
                else
                    break;
                schedule_art();
                play_avatar_sound(0);
                redraw = true;
                break;
            case ACTION_STD_OK:
                if (screen == SCREEN_GAMES && load_achievements())
                    screen = SCREEN_ACHIEVEMENTS;
                else if (screen == SCREEN_ACHIEVEMENTS)
                    screen = SCREEN_DETAIL;
                else if (screen == SCREEN_CONSOLES)
                {
                    console_filter = picker_console;
                    rebuild_visible_games();
                    screen = SCREEN_GAMES;
                }
                else if (screen == SCREEN_AVATAR)
                {
                    if (avatar_clip == AVATAR_TURNTABLE_CLIP)
                    {
                        avatar_clip = avatar_emote_clip;
                        avatar_paused = false;
                        schedule_avatar_clip();
                    }
                    else
                    {
                        avatar_paused = false;
                        avatar_frame_started = *rb->current_tick;
                        decode_avatar_frame(0);
                    }
                }
                else if (screen == SCREEN_AVATAR_SETTINGS)
                {
                    if (avatar_settings_row == AVATAR_PREF_MOTION)
                        avatar_motion = (avatar_motion + 1) % 3;
                    else if (avatar_settings_row == AVATAR_PREF_SOUNDS)
                        avatar_sound_mode = (avatar_sound_mode + 1) % 3;
                    else if (avatar_settings_row == AVATAR_PREF_OVER_MUSIC)
                        avatar_sounds_over_music = !avatar_sounds_over_music;
                    else
                        avatar_idle_emotes = !avatar_idle_emotes;
                    save_avatar_preferences();
                }
                schedule_art();
                play_avatar_sound(1);
                redraw = true;
                break;
            case ACTION_STD_CONTEXT:
                if (screen == SCREEN_GAMES)
                {
                    wait_for_select_release();
                    picker_console = console_filter;
                    screen = SCREEN_CONSOLES;
                    play_avatar_sound(1);
                    redraw = true;
                }
                else if (screen == SCREEN_ACHIEVEMENTS)
                {
                    wait_for_select_release();
                    locked_only = !locked_only;
                    if (!load_achievements())
                    {
                        locked_only = false;
                        load_achievements();
                    }
                    schedule_art();
                    play_avatar_sound(1);
                    redraw = true;
                }
                else if (screen == SCREEN_AVATAR)
                {
                    wait_for_select_release();
                    avatar_settings_row = 0;
                    screen = SCREEN_AVATAR_SETTINGS;
                    play_avatar_sound(1);
                    redraw = true;
                }
                break;
            case ACTION_STD_QUICKSCREEN:
                if (screen != SCREEN_AVATAR &&
                    screen != SCREEN_AVATAR_SETTINGS)
                {
                    wait_for_menu_release();
                    avatar_return_screen = screen;
                    screen = SCREEN_AVATAR;
                    avatar_clip = AVATAR_TURNTABLE_CLIP;
                    avatar_paused = false;
                    avatar_enter_started = *rb->current_tick;
                    if (!avatar_profile_checked)
                        load_due_avatar_assets();
                    schedule_avatar_clip();
                    play_avatar_sound(1);
                    redraw = true;
                }
                break;
            case ACTION_WPS_PLAY:
                if (screen == SCREEN_AVATAR)
                {
                    avatar_paused = !avatar_paused;
                    if (!avatar_paused)
                        avatar_frame_started = *rb->current_tick -
                            avatar_frame * avatar_frame_ms * HZ / 1000;
                    play_avatar_sound(1);
                    redraw = true;
                }
                break;
            case ACTION_STD_CANCEL:
            case ACTION_STD_MENU:
                if (screen == SCREEN_DETAIL)
                    screen = SCREEN_ACHIEVEMENTS;
                else if (screen == SCREEN_ACHIEVEMENTS)
                    screen = SCREEN_GAMES;
                else if (screen == SCREEN_CONSOLES)
                    screen = SCREEN_GAMES;
                else if (screen == SCREEN_AVATAR_SETTINGS)
                {
                    save_avatar_preferences();
                    screen = SCREEN_AVATAR;
                }
                else if (screen == SCREEN_AVATAR)
                    screen = avatar_return_screen;
                else
                    return finish(PLUGIN_OK);
                schedule_art();
                play_avatar_sound(2);
                redraw = true;
                break;
            default:
                if (rb->default_event_handler(action) == SYS_USB_CONNECTED)
                    return finish(PLUGIN_USB_CONNECTED);
                break;
        }
        if (redraw)
            draw();
    }
}
