#!/usr/bin/env python3
"""Generate inline Nano implementations of explicitly excluded optional features.

This does not fill unknown linker symbols. Only enhancement notifications,
cheat state and interpolation recording are eligible; game services stay required.
"""
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]
SHIP = ROOT / 'Shipwright'
OUT = ROOT / 'platform'
SPECS = [
 ('soh/soh/Enhancements/game-interactor/GameInteractor.h', 'nano_interactor_state.h', 'GameInteractor_'),
 ('soh/soh/Enhancements/game-interactor/GameInteractor_Hooks.h', 'nano_interactor_hooks.h', 'GameInteractor_'),
 ('soh/soh/frame_interpolation.h', 'nano_interpolation.h', 'FrameInterpolation_'),
]
DEFAULTS = {
 'GameInteractor_GetLinkSize':'GI_LINK_SIZE_NORMAL',
 'GameInteractor_GravityLevel':'GI_GRAVITY_LEVEL_NORMAL',
 'GameInteractor_MovementSpeedMultiplier':'1.0f',
 'GameInteractor_Should':'result != 0',
 'GameInteractor_ShouldActorInit':'true',
 'GameInteractor_ShouldActorUpdate':'true',
 'GameInteractor_ShouldActorDestroy':'true',
}
for rel, output, prefix in SPECS:
 p=SHIP/rel
 original=p.read_text()
 # All C interface prototypes precede any C++ method definitions.
 matches=re.findall(r'^(void|bool|uint8_t|uint32_t|int32_t|float|int|GILinkSize|GIGravityLevel)\s+('+prefix+r'\w+)\(([^;]*?)\);', original,re.M)
 lines=['/* Generated by tools/configure_nano.py; Nano-only optional features. */','#pragma once','']
 for ret,name,args in matches:
  params=[]
  if args and args!='void':
   for param in args.split(','):
    if param.strip()=='...':continue
    callback=re.search(r'\(\*(\w+)\)',param)
    params.append(callback[1] if callback else re.search(r'(\w+)\s*$',param)[1])
  body=' '.join('(void)'+param+';' for param in params)
  if ret!='void':body+=' return '+DEFAULTS.get(name,'0')+';'
  lines += ['static inline '+ret+' Nano_'+name+'('+ (args or 'void') +') { '+body+' }', '#define '+name+' Nano_'+name]
 (OUT/output).write_text('\n'.join(lines)+'\n')
 marker='\n#ifdef SHIP_PLATFORM_NANO7G\n#include "'+output+'"\n#endif\n'
 if marker not in original:p.write_text(original+marker)
