/* Don't change this file! */
/* It is automatically generated of action.h */
#include "plugin.h"
#include "action_helper.h"
static const char action_names[]= 
/*ACTION_*/"%sNONE\0"
/*ACTION_*/"%sUNKNOWN\0"
/*ACTION_*/"%sREDRAW\0"
/*ACTION_*/"%sTOUCHSCREEN\0"
/*ACTION_*/"%sTOUCHSCREEN_MODE\0"
/*ACTION_*/"%sTOUCHSCREEN_IGNORE\0"
/*ACTION_*/"%sSTD_PREV\0"
/*ACTION_*/"%sSTD_PREVREPEAT\0"
/*ACTION_*/"%sSTD_NEXT\0"
/*ACTION_*/"%sSTD_NEXTREPEAT\0"
/*ACTION_*/"%sSTD_OK\0"
/*ACTION_*/"%sSTD_CANCEL\0"
/*ACTION_*/"%sSTD_CONTEXT\0"
/*ACTION_*/"%sSTD_MENU\0"
/*ACTION_*/"%sSTD_QUICKSCREEN\0"
/*ACTION_*/"%sSTD_KEYLOCK\0"
/*ACTION_*/"%sSTD_REC\0"
/*ACTION_*/"%sSTD_HOTKEY\0"
/*ACTION_*/"%sWPS_BROWSE\0"
/*ACTION_*/"%sWPS_PLAY\0"
/*ACTION_*/"%sWPS_SEEKBACK\0"
/*ACTION_*/"%sWPS_SEEKFWD\0"
/*ACTION_*/"%sWPS_STOPSEEK\0"
/*ACTION_*/"%sWPS_SKIPNEXT\0"
/*ACTION_*/"%sWPS_SKIPPREV\0"
/*ACTION_*/"%sWPS_STOP\0"
/*ACTION_*/"%sWPS_VOLDOWN\0"
/*ACTION_*/"%sWPS_VOLUP\0"
/*ACTION_*/"%sWPS_PITCHSCREEN\0"
/*ACTION_*/"%sWPS_ID3SCREEN\0"
/*ACTION_*/"%sWPS_CONTEXT\0"
/*ACTION_*/"%sWPS_QUICKSCREEN\0"
/*ACTION_*/"%sWPS_MENU\0"
/*ACTION_*/"%sWPS_VIEW_PLAYLIST\0"
/*ACTION_*/"%sWPS_LIST_BOOKMARKS\0"
/*ACTION_*/"%sWPS_CREATE_BOOKMARK\0"
/*ACTION_*/"%sWPS_REC\0"
/*ACTION_*/"%sWPS_ABSETA_PREVDIR\0"
/*ACTION_*/"%sWPS_ABSETB_NEXTDIR\0"
/*ACTION_*/"%sWPS_ABRESET\0"
/*ACTION_*/"%sWPS_HOTKEY\0"
/*ACTION_*/"%sLISTTREE_PGUP\0"
/*ACTION_*/"%sLISTTREE_PGDOWN\0"
/*ACTION_*/"%sTREE_ROOT_INIT\0"
/*ACTION_*/"%sTREE_PGLEFT\0"
/*ACTION_*/"%sTREE_PGRIGHT\0"
/*ACTION_*/"%sTREE_STOP\0"
/*ACTION_*/"%sTREE_WPS\0"
/*ACTION_*/"%sTREE_HOTKEY\0"
/*ACTION_*/"%sTREE_POWER_MENU\0"
/*ACTION_*/"%sFM_MENU\0"
/*ACTION_*/"%sFM_PRESET\0"
/*ACTION_*/"%sFM_RECORD\0"
/*ACTION_*/"%sFM_FREEZE\0"
/*ACTION_*/"%sFM_STOP\0"
/*ACTION_*/"%sFM_MODE\0"
/*ACTION_*/"%sFM_EXIT\0"
/*ACTION_*/"%sFM_PLAY\0"
/*ACTION_*/"%sFM_RECORD_DBLPRE\0"
/*ACTION_*/"%sFM_NEXT_PRESET\0"
/*ACTION_*/"%sFM_PREV_PRESET\0"
/*ACTION_*/"%sREC_LCD\0"
/*ACTION_*/"%sREC_PAUSE\0"
/*ACTION_*/"%sREC_NEWFILE\0"
/*ACTION_*/"%sREC_F2\0"
/*ACTION_*/"%sREC_F3\0"
/*ACTION_*/"%sREQUEST_MENUITEM\0"
/*ACTION_*/"%sEXIT_MENUITEM\0"
/*ACTION_*/"%sEXIT_AFTER_THIS_MENUITEM\0"
/*ACTION_*/"%sENTER_MENUITEM\0"
/*ACTION_*/"%sSETTINGS_INC\0"
/*ACTION_*/"%sSETTINGS_INCREPEAT\0"
/*ACTION_*/"%sSETTINGS_INCBIGSTEP\0"
/*ACTION_*/"%sSETTINGS_DEC\0"
/*ACTION_*/"%sSETTINGS_DECREPEAT\0"
/*ACTION_*/"%sSETTINGS_DECBIGSTEP\0"
/*ACTION_*/"%sSETTINGS_SET\0"
/*ACTION_*/"%sBMS_DELETE\0"
/*ACTION_*/"%sQS_LEFT\0"
/*ACTION_*/"%sQS_RIGHT\0"
/*ACTION_*/"%sQS_DOWN\0"
/*ACTION_*/"%sQS_TOP\0"
/*ACTION_*/"%sQS_VOLUP\0"
/*ACTION_*/"%sQS_VOLDOWN\0"
/*ACTION_*/"%sPS_INC_SMALL\0"
/*ACTION_*/"%sPS_INC_BIG\0"
/*ACTION_*/"%sPS_DEC_SMALL\0"
/*ACTION_*/"%sPS_DEC_BIG\0"
/*ACTION_*/"%sPS_NUDGE_LEFT\0"
/*ACTION_*/"%sPS_NUDGE_RIGHT\0"
/*ACTION_*/"%sPS_NUDGE_LEFTOFF\0"
/*ACTION_*/"%sPS_NUDGE_RIGHTOFF\0"
/*ACTION_*/"%sPS_TOGGLE_MODE\0"
/*ACTION_*/"%sPS_RESET\0"
/*ACTION_*/"%sPS_EXIT\0"
/*ACTION_*/"%sPS_SLOWER\0"
/*ACTION_*/"%sPS_FASTER\0"
/*ACTION_*/"%sYESNO_ACCEPT\0"
/*ACTION_*/"%sKBD_LEFT\0"
/*ACTION_*/"%sKBD_RIGHT\0"
/*ACTION_*/"%sKBD_CURSOR_LEFT\0"
/*ACTION_*/"%sKBD_CURSOR_RIGHT\0"
/*ACTION_*/"%sKBD_SELECT\0"
/*ACTION_*/"%sKBD_PAGE_FLIP\0"
/*ACTION_*/"%sKBD_DONE\0"
/*ACTION_*/"%sKBD_ABORT\0"
/*ACTION_*/"%sKBD_BACKSPACE\0"
/*ACTION_*/"%sKBD_UP\0"
/*ACTION_*/"%sKBD_DOWN\0"
/*ACTION_*/"%sKBD_MORSE_INPUT\0"
/*ACTION_*/"%sKBD_MORSE_SELECT\0"
/*ACTION_USB_HID_*/"%sFIRST\0"
/*ACTION_USB_HID_*/"%sNONE\0"
/*ACTION_USB_HID_*/"%sMODE_SWITCH_NEXT\0"
/*ACTION_USB_HID_*/"%sMODE_SWITCH_PREV\0"
/*ACTION_USB_HID_*/"%sMULTIMEDIA_VOLUME_UP\0"
/*ACTION_USB_HID_*/"%sMULTIMEDIA_VOLUME_DOWN\0"
/*ACTION_USB_HID_*/"%sMULTIMEDIA_VOLUME_MUTE\0"
/*ACTION_USB_HID_*/"%sMULTIMEDIA_PLAYBACK_PLAY_PAUSE\0"
/*ACTION_USB_HID_*/"%sMULTIMEDIA_PLAYBACK_STOP\0"
/*ACTION_USB_HID_*/"%sMULTIMEDIA_PLAYBACK_TRACK_PREV\0"
/*ACTION_USB_HID_*/"%sMULTIMEDIA_PLAYBACK_TRACK_NEXT\0"
/*ACTION_USB_HID_*/"%sPRESENTATION_SLIDESHOW_START\0"
/*ACTION_USB_HID_*/"%sPRESENTATION_SLIDESHOW_LEAVE\0"
/*ACTION_USB_HID_*/"%sPRESENTATION_SLIDE_PREV\0"
/*ACTION_USB_HID_*/"%sPRESENTATION_SLIDE_NEXT\0"
/*ACTION_USB_HID_*/"%sPRESENTATION_SLIDE_FIRST\0"
/*ACTION_USB_HID_*/"%sPRESENTATION_SLIDE_LAST\0"
/*ACTION_USB_HID_*/"%sPRESENTATION_SCREEN_BLACK\0"
/*ACTION_USB_HID_*/"%sPRESENTATION_SCREEN_WHITE\0"
/*ACTION_USB_HID_*/"%sPRESENTATION_LINK_PREV\0"
/*ACTION_USB_HID_*/"%sPRESENTATION_LINK_NEXT\0"
/*ACTION_USB_HID_*/"%sPRESENTATION_MOUSE_CLICK\0"
/*ACTION_USB_HID_*/"%sPRESENTATION_MOUSE_OVER\0"
/*ACTION_USB_HID_*/"%sBROWSER_SCROLL_UP\0"
/*ACTION_USB_HID_*/"%sBROWSER_SCROLL_DOWN\0"
/*ACTION_USB_HID_*/"%sBROWSER_SCROLL_PAGE_DOWN\0"
/*ACTION_USB_HID_*/"%sBROWSER_SCROLL_PAGE_UP\0"
/*ACTION_USB_HID_*/"%sBROWSER_ZOOM_IN\0"
/*ACTION_USB_HID_*/"%sBROWSER_ZOOM_OUT\0"
/*ACTION_USB_HID_*/"%sBROWSER_ZOOM_RESET\0"
/*ACTION_USB_HID_*/"%sBROWSER_TAB_PREV\0"
/*ACTION_USB_HID_*/"%sBROWSER_TAB_NEXT\0"
/*ACTION_USB_HID_*/"%sBROWSER_TAB_CLOSE\0"
/*ACTION_USB_HID_*/"%sBROWSER_HISTORY_BACK\0"
/*ACTION_USB_HID_*/"%sBROWSER_HISTORY_FORWARD\0"
/*ACTION_USB_HID_*/"%sBROWSER_VIEW_FULL_SCREEN\0"
/*ACTION_USB_HID_*/"%sMOUSE_UP\0"
/*ACTION_USB_HID_*/"%sMOUSE_UP_REP\0"
/*ACTION_USB_HID_*/"%sMOUSE_DOWN\0"
/*ACTION_USB_HID_*/"%sMOUSE_DOWN_REP\0"
/*ACTION_USB_HID_*/"%sMOUSE_LEFT\0"
/*ACTION_USB_HID_*/"%sMOUSE_LEFT_REP\0"
/*ACTION_USB_HID_*/"%sMOUSE_RIGHT\0"
/*ACTION_USB_HID_*/"%sMOUSE_RIGHT_REP\0"
/*ACTION_USB_HID_*/"%sMOUSE_LDRAG_UP\0"
/*ACTION_USB_HID_*/"%sMOUSE_LDRAG_UP_REP\0"
/*ACTION_USB_HID_*/"%sMOUSE_LDRAG_DOWN\0"
/*ACTION_USB_HID_*/"%sMOUSE_LDRAG_DOWN_REP\0"
/*ACTION_USB_HID_*/"%sMOUSE_LDRAG_LEFT\0"
/*ACTION_USB_HID_*/"%sMOUSE_LDRAG_LEFT_REP\0"
/*ACTION_USB_HID_*/"%sMOUSE_LDRAG_RIGHT\0"
/*ACTION_USB_HID_*/"%sMOUSE_LDRAG_RIGHT_REP\0"
/*ACTION_USB_HID_*/"%sMOUSE_RDRAG_UP\0"
/*ACTION_USB_HID_*/"%sMOUSE_RDRAG_UP_REP\0"
/*ACTION_USB_HID_*/"%sMOUSE_RDRAG_DOWN\0"
/*ACTION_USB_HID_*/"%sMOUSE_RDRAG_DOWN_REP\0"
/*ACTION_USB_HID_*/"%sMOUSE_RDRAG_LEFT\0"
/*ACTION_USB_HID_*/"%sMOUSE_RDRAG_LEFT_REP\0"
/*ACTION_USB_HID_*/"%sMOUSE_RDRAG_RIGHT\0"
/*ACTION_USB_HID_*/"%sMOUSE_RDRAG_RIGHT_REP\0"
/*ACTION_USB_HID_*/"%sMOUSE_BUTTON_LEFT\0"
/*ACTION_USB_HID_*/"%sMOUSE_BUTTON_LEFT_REL\0"
/*ACTION_USB_HID_*/"%sMOUSE_BUTTON_RIGHT\0"
/*ACTION_USB_HID_*/"%sMOUSE_BUTTON_RIGHT_REL\0"
/*ACTION_USB_HID_*/"%sMOUSE_WHEEL_SCROLL_UP\0"
/*ACTION_USB_HID_*/"%sMOUSE_WHEEL_SCROLL_DOWN\0"
/*ACTION_USB_HID_*/"%sLAST\0"
"\0" 
"PLA_UP\0" 
"PLA_DOWN\0" 
"PLA_LEFT\0" 
"PLA_RIGHT\0" 
"PLA_UP_REPEAT\0" 
"PLA_DOWN_REPEAT\0" 
"PLA_LEFT_REPEAT\0" 
"PLA_RIGHT_REPEAT\0" 
"PLA_CANCEL\0" 
"PLA_EXIT\0" 
"PLA_SELECT\0" 
"PLA_SELECT_REL\0" 
"PLA_SELECT_REPEAT\0" 
"PLA_SCROLL_FWD\0" 
"PLA_SCROLL_FWD_REPEAT\0" 
"PLA_SCROLL_BACK\0" 
"PLA_SCROLL_BACK_REPEAT\0" 
"";/* 3297 + \0 */

static const char context_names[]= 
/*CONTEXT_*/"%sSTD\0"
/*CONTEXT_*/"%sWPS\0"
/*CONTEXT_*/"%sTREE\0"
/*CONTEXT_*/"%sRECORD\0"
/*CONTEXT_*/"%sMAINMENU\0"
/*CONTEXT_*/"%sID3DB\0"
/*CONTEXT_*/"%sLIST\0"
/*CONTEXT_*/"%sSETTINGS\0"
/*CONTEXT_*/"%sSETTINGS_EQ\0"
/*CONTEXT_*/"%sSETTINGS_COLOURCHOOSER\0"
/*CONTEXT_*/"%sSETTINGS_TIME\0"
/*CONTEXT_*/"%sSETTINGS_RECTRIGGER\0"
/*CONTEXT_*/"%sBOOKMARKSCREEN\0"
/*CONTEXT_*/"%sALARMSCREEN\0"
/*CONTEXT_*/"%sQUICKSCREEN\0"
/*CONTEXT_*/"%sPITCHSCREEN\0"
/*CONTEXT_*/"%sYESNOSCREEN\0"
/*CONTEXT_*/"%sRECSCREEN\0"
/*CONTEXT_*/"%sKEYBOARD\0"
/*CONTEXT_*/"%sMORSE_INPUT\0"
"CONTEXT_FM\0" 
/*CONTEXT_*/"%sUSB_HID\0"
/*CONTEXT_*/"%sUSB_HID_MODE_MULTIMEDIA\0"
/*CONTEXT_*/"%sUSB_HID_MODE_PRESENTATION\0"
/*CONTEXT_*/"%sUSB_HID_MODE_BROWSER\0"
/*CONTEXT_*/"%sUSB_HID_MODE_MOUSE\0"
"";/* 371 + \0 */

#define ACTION_CT 196
static const uint16_t action_offsets[ACTION_CT] = {
0, /*ACTION_NONE*/
7, /*ACTION_UNKNOWN*/
17, /*ACTION_REDRAW*/
26, /*ACTION_TOUCHSCREEN*/
40, /*ACTION_TOUCHSCREEN_MODE*/
59, /*ACTION_TOUCHSCREEN_IGNORE*/
80, /*ACTION_STD_PREV*/
91, /*ACTION_STD_PREVREPEAT*/
108, /*ACTION_STD_NEXT*/
119, /*ACTION_STD_NEXTREPEAT*/
136, /*ACTION_STD_OK*/
145, /*ACTION_STD_CANCEL*/
158, /*ACTION_STD_CONTEXT*/
172, /*ACTION_STD_MENU*/
183, /*ACTION_STD_QUICKSCREEN*/
201, /*ACTION_STD_KEYLOCK*/
215, /*ACTION_STD_REC*/
225, /*ACTION_STD_HOTKEY*/
238, /*ACTION_WPS_BROWSE*/
251, /*ACTION_WPS_PLAY*/
262, /*ACTION_WPS_SEEKBACK*/
277, /*ACTION_WPS_SEEKFWD*/
291, /*ACTION_WPS_STOPSEEK*/
306, /*ACTION_WPS_SKIPNEXT*/
321, /*ACTION_WPS_SKIPPREV*/
336, /*ACTION_WPS_STOP*/
347, /*ACTION_WPS_VOLDOWN*/
361, /*ACTION_WPS_VOLUP*/
373, /*ACTION_WPS_PITCHSCREEN*/
391, /*ACTION_WPS_ID3SCREEN*/
407, /*ACTION_WPS_CONTEXT*/
421, /*ACTION_WPS_QUICKSCREEN*/
439, /*ACTION_WPS_MENU*/
450, /*ACTION_WPS_VIEW_PLAYLIST*/
470, /*ACTION_WPS_LIST_BOOKMARKS*/
491, /*ACTION_WPS_CREATE_BOOKMARK*/
513, /*ACTION_WPS_REC*/
523, /*ACTION_WPS_ABSETA_PREVDIR*/
544, /*ACTION_WPS_ABSETB_NEXTDIR*/
565, /*ACTION_WPS_ABRESET*/
579, /*ACTION_WPS_HOTKEY*/
592, /*ACTION_LISTTREE_PGUP*/
608, /*ACTION_LISTTREE_PGDOWN*/
626, /*ACTION_TREE_ROOT_INIT*/
643, /*ACTION_TREE_PGLEFT*/
657, /*ACTION_TREE_PGRIGHT*/
672, /*ACTION_TREE_STOP*/
684, /*ACTION_TREE_WPS*/
695, /*ACTION_TREE_HOTKEY*/
709, /*ACTION_TREE_POWER_MENU*/
727, /*ACTION_FM_MENU*/
737, /*ACTION_FM_PRESET*/
749, /*ACTION_FM_RECORD*/
761, /*ACTION_FM_FREEZE*/
773, /*ACTION_FM_STOP*/
783, /*ACTION_FM_MODE*/
793, /*ACTION_FM_EXIT*/
803, /*ACTION_FM_PLAY*/
813, /*ACTION_FM_RECORD_DBLPRE*/
832, /*ACTION_FM_NEXT_PRESET*/
849, /*ACTION_FM_PREV_PRESET*/
866, /*ACTION_REC_LCD*/
876, /*ACTION_REC_PAUSE*/
888, /*ACTION_REC_NEWFILE*/
902, /*ACTION_REC_F2*/
911, /*ACTION_REC_F3*/
920, /*ACTION_REQUEST_MENUITEM*/
939, /*ACTION_EXIT_MENUITEM*/
955, /*ACTION_EXIT_AFTER_THIS_MENUITEM*/
982, /*ACTION_ENTER_MENUITEM*/
999, /*ACTION_SETTINGS_INC*/
1014, /*ACTION_SETTINGS_INCREPEAT*/
1035, /*ACTION_SETTINGS_INCBIGSTEP*/
1057, /*ACTION_SETTINGS_DEC*/
1072, /*ACTION_SETTINGS_DECREPEAT*/
1093, /*ACTION_SETTINGS_DECBIGSTEP*/
1115, /*ACTION_SETTINGS_SET*/
1130, /*ACTION_BMS_DELETE*/
1143, /*ACTION_QS_LEFT*/
1153, /*ACTION_QS_RIGHT*/
1164, /*ACTION_QS_DOWN*/
1174, /*ACTION_QS_TOP*/
1183, /*ACTION_QS_VOLUP*/
1194, /*ACTION_QS_VOLDOWN*/
1207, /*ACTION_PS_INC_SMALL*/
1222, /*ACTION_PS_INC_BIG*/
1235, /*ACTION_PS_DEC_SMALL*/
1250, /*ACTION_PS_DEC_BIG*/
1263, /*ACTION_PS_NUDGE_LEFT*/
1279, /*ACTION_PS_NUDGE_RIGHT*/
1296, /*ACTION_PS_NUDGE_LEFTOFF*/
1315, /*ACTION_PS_NUDGE_RIGHTOFF*/
1335, /*ACTION_PS_TOGGLE_MODE*/
1352, /*ACTION_PS_RESET*/
1363, /*ACTION_PS_EXIT*/
1373, /*ACTION_PS_SLOWER*/
1385, /*ACTION_PS_FASTER*/
1397, /*ACTION_YESNO_ACCEPT*/
1412, /*ACTION_KBD_LEFT*/
1423, /*ACTION_KBD_RIGHT*/
1435, /*ACTION_KBD_CURSOR_LEFT*/
1453, /*ACTION_KBD_CURSOR_RIGHT*/
1472, /*ACTION_KBD_SELECT*/
1485, /*ACTION_KBD_PAGE_FLIP*/
1501, /*ACTION_KBD_DONE*/
1512, /*ACTION_KBD_ABORT*/
1524, /*ACTION_KBD_BACKSPACE*/
1540, /*ACTION_KBD_UP*/
1549, /*ACTION_KBD_DOWN*/
1560, /*ACTION_KBD_MORSE_INPUT*/
1578, /*ACTION_KBD_MORSE_SELECT*/
1597, /*ACTION_USB_HID_FIRST*/
1605, /*ACTION_USB_HID_NONE*/
1612, /*ACTION_USB_HID_MODE_SWITCH_NEXT*/
1631, /*ACTION_USB_HID_MODE_SWITCH_PREV*/
1650, /*ACTION_USB_HID_MULTIMEDIA_VOLUME_UP*/
1673, /*ACTION_USB_HID_MULTIMEDIA_VOLUME_DOWN*/
1698, /*ACTION_USB_HID_MULTIMEDIA_VOLUME_MUTE*/
1723, /*ACTION_USB_HID_MULTIMEDIA_PLAYBACK_PLAY_PAUSE*/
1756, /*ACTION_USB_HID_MULTIMEDIA_PLAYBACK_STOP*/
1783, /*ACTION_USB_HID_MULTIMEDIA_PLAYBACK_TRACK_PREV*/
1816, /*ACTION_USB_HID_MULTIMEDIA_PLAYBACK_TRACK_NEXT*/
1849, /*ACTION_USB_HID_PRESENTATION_SLIDESHOW_START*/
1880, /*ACTION_USB_HID_PRESENTATION_SLIDESHOW_LEAVE*/
1911, /*ACTION_USB_HID_PRESENTATION_SLIDE_PREV*/
1937, /*ACTION_USB_HID_PRESENTATION_SLIDE_NEXT*/
1963, /*ACTION_USB_HID_PRESENTATION_SLIDE_FIRST*/
1990, /*ACTION_USB_HID_PRESENTATION_SLIDE_LAST*/
2016, /*ACTION_USB_HID_PRESENTATION_SCREEN_BLACK*/
2044, /*ACTION_USB_HID_PRESENTATION_SCREEN_WHITE*/
2072, /*ACTION_USB_HID_PRESENTATION_LINK_PREV*/
2097, /*ACTION_USB_HID_PRESENTATION_LINK_NEXT*/
2122, /*ACTION_USB_HID_PRESENTATION_MOUSE_CLICK*/
2149, /*ACTION_USB_HID_PRESENTATION_MOUSE_OVER*/
2175, /*ACTION_USB_HID_BROWSER_SCROLL_UP*/
2195, /*ACTION_USB_HID_BROWSER_SCROLL_DOWN*/
2217, /*ACTION_USB_HID_BROWSER_SCROLL_PAGE_DOWN*/
2244, /*ACTION_USB_HID_BROWSER_SCROLL_PAGE_UP*/
2269, /*ACTION_USB_HID_BROWSER_ZOOM_IN*/
2287, /*ACTION_USB_HID_BROWSER_ZOOM_OUT*/
2306, /*ACTION_USB_HID_BROWSER_ZOOM_RESET*/
2327, /*ACTION_USB_HID_BROWSER_TAB_PREV*/
2346, /*ACTION_USB_HID_BROWSER_TAB_NEXT*/
2365, /*ACTION_USB_HID_BROWSER_TAB_CLOSE*/
2385, /*ACTION_USB_HID_BROWSER_HISTORY_BACK*/
2408, /*ACTION_USB_HID_BROWSER_HISTORY_FORWARD*/
2434, /*ACTION_USB_HID_BROWSER_VIEW_FULL_SCREEN*/
2461, /*ACTION_USB_HID_MOUSE_UP*/
2472, /*ACTION_USB_HID_MOUSE_UP_REP*/
2487, /*ACTION_USB_HID_MOUSE_DOWN*/
2500, /*ACTION_USB_HID_MOUSE_DOWN_REP*/
2517, /*ACTION_USB_HID_MOUSE_LEFT*/
2530, /*ACTION_USB_HID_MOUSE_LEFT_REP*/
2547, /*ACTION_USB_HID_MOUSE_RIGHT*/
2561, /*ACTION_USB_HID_MOUSE_RIGHT_REP*/
2579, /*ACTION_USB_HID_MOUSE_LDRAG_UP*/
2596, /*ACTION_USB_HID_MOUSE_LDRAG_UP_REP*/
2617, /*ACTION_USB_HID_MOUSE_LDRAG_DOWN*/
2636, /*ACTION_USB_HID_MOUSE_LDRAG_DOWN_REP*/
2659, /*ACTION_USB_HID_MOUSE_LDRAG_LEFT*/
2678, /*ACTION_USB_HID_MOUSE_LDRAG_LEFT_REP*/
2701, /*ACTION_USB_HID_MOUSE_LDRAG_RIGHT*/
2721, /*ACTION_USB_HID_MOUSE_LDRAG_RIGHT_REP*/
2745, /*ACTION_USB_HID_MOUSE_RDRAG_UP*/
2762, /*ACTION_USB_HID_MOUSE_RDRAG_UP_REP*/
2783, /*ACTION_USB_HID_MOUSE_RDRAG_DOWN*/
2802, /*ACTION_USB_HID_MOUSE_RDRAG_DOWN_REP*/
2825, /*ACTION_USB_HID_MOUSE_RDRAG_LEFT*/
2844, /*ACTION_USB_HID_MOUSE_RDRAG_LEFT_REP*/
2867, /*ACTION_USB_HID_MOUSE_RDRAG_RIGHT*/
2887, /*ACTION_USB_HID_MOUSE_RDRAG_RIGHT_REP*/
2911, /*ACTION_USB_HID_MOUSE_BUTTON_LEFT*/
2931, /*ACTION_USB_HID_MOUSE_BUTTON_LEFT_REL*/
2955, /*ACTION_USB_HID_MOUSE_BUTTON_RIGHT*/
2976, /*ACTION_USB_HID_MOUSE_BUTTON_RIGHT_REL*/
3001, /*ACTION_USB_HID_MOUSE_WHEEL_SCROLL_UP*/
3025, /*ACTION_USB_HID_MOUSE_WHEEL_SCROLL_DOWN*/
3051, /*ACTION_USB_HID_LAST*/
3058, /**/
3059, /*PLA_UP*/
3066, /*PLA_DOWN*/
3075, /*PLA_LEFT*/
3084, /*PLA_RIGHT*/
3094, /*PLA_UP_REPEAT*/
3108, /*PLA_DOWN_REPEAT*/
3124, /*PLA_LEFT_REPEAT*/
3140, /*PLA_RIGHT_REPEAT*/
3157, /*PLA_CANCEL*/
3168, /*PLA_EXIT*/
3177, /*PLA_SELECT*/
3188, /*PLA_SELECT_REL*/
3203, /*PLA_SELECT_REPEAT*/
3221, /*PLA_SCROLL_FWD*/
3236, /*PLA_SCROLL_FWD_REPEAT*/
3258, /*PLA_SCROLL_BACK*/
3274, /*PLA_SCROLL_BACK_REPEAT*/
};

#define CONTEXT_CT 26
#if 0 /* context_names is small enough to walk the string instead */
static const uint16_t context_offsets[CONTEXT_CT] = {
0, /*CONTEXT_STD*/
6, /*CONTEXT_WPS*/
12, /*CONTEXT_TREE*/
19, /*CONTEXT_RECORD*/
28, /*CONTEXT_MAINMENU*/
39, /*CONTEXT_ID3DB*/
47, /*CONTEXT_LIST*/
54, /*CONTEXT_SETTINGS*/
65, /*CONTEXT_SETTINGS_EQ*/
79, /*CONTEXT_SETTINGS_COLOURCHOOSER*/
104, /*CONTEXT_SETTINGS_TIME*/
120, /*CONTEXT_SETTINGS_RECTRIGGER*/
142, /*CONTEXT_BOOKMARKSCREEN*/
159, /*CONTEXT_ALARMSCREEN*/
173, /*CONTEXT_QUICKSCREEN*/
187, /*CONTEXT_PITCHSCREEN*/
201, /*CONTEXT_YESNOSCREEN*/
215, /*CONTEXT_RECSCREEN*/
227, /*CONTEXT_KEYBOARD*/
238, /*CONTEXT_MORSE_INPUT*/
252, /*CONTEXT_FM*/
263, /*CONTEXT_USB_HID*/
273, /*CONTEXT_USB_HID_MODE_MULTIMEDIA*/
299, /*CONTEXT_USB_HID_MODE_PRESENTATION*/
327, /*CONTEXT_USB_HID_MODE_BROWSER*/
350, /*CONTEXT_USB_HID_MODE_MOUSE*/
};
#endif

#define ACTIONBUFSZ 46
#define CONTEXTBUFSZ 34

const size_t action_helper_maxbuffer = ACTIONBUFSZ;
static char name_buf[ACTIONBUFSZ];

char* action_name(int action)
{
    if (action >= 0 && action < ACTION_CT)
    {
        uint16_t offset = action_offsets[action];
        const char *act = &action_names[offset];
        if (action < ACTION_USB_HID_FIRST)
            rb->snprintf(name_buf, ACTIONBUFSZ, act, "ACTION_");
        else
            rb->snprintf(name_buf, ACTIONBUFSZ, act, "ACTION_USB_HID_");
    }
    else
        rb->snprintf(name_buf, ACTIONBUFSZ, "ACTION_UNKNOWN");
    return name_buf;
}

/* walk string increment offset for each NULL if desired offset found, return */
static const char *context_getoffset(int offset)
{
    const char *names = context_names;
    const size_t len = sizeof(context_names) - 1;
    int current = 0;
    if (offset > 0)
    {
        const char *pos = names;
        const char *end = names + len;
        while (pos < end)
        {
            if (*pos++ == '\0')
            {
                current++;
                if (offset == current)
                    return pos;
                pos += 5; /* each string is at least this long */
            }
        }
    }
    return names;
}

char* context_name(int context)
{
    const char *ctx;
    if (context >= 0 && context < CONTEXT_CT)
    {
#if 0
        uint16_t offset = context_offsets[context];
        ctx = &context_names[offset];
#else
        ctx = context_getoffset(context);
#endif
    }
    else
        ctx = "%sUNKNOWN";
    rb->snprintf(name_buf, CONTEXTBUFSZ, ctx, "CONTEXT_");
    return name_buf;
}
