#!/usr/bin/env python3
"""Generate Linux timeconst.h without the host `bc` utility.

This is a narrow qualification-build helper implementing the integer formulas in
Linux's kernel/time/timeconst.bc. It is not a general-purpose bc replacement.
"""

from __future__ import annotations

import math
import sys


def _fmul(bits, numerator, denominator):
    return ((1 << bits) * numerator + denominator - 1) // denominator


def _fadj(bits, numerator, denominator):
    reduced_denominator = denominator // math.gcd(numerator, denominator)
    return ((1 << bits) * (reduced_denominator - 1)) // reduced_denominator


def _fmuls(bits, numerator, denominator):
    shift = 0
    while _fmul(shift, numerator, denominator) < (1 << (bits - 1)):
        shift += 1
    return shift


def _ratio(name, numerator, denominator):
    common = math.gcd(numerator, denominator)
    return [
        f"#define {name}_NUM\t\t{numerator // common}",
        f"#define {name}_DEN\t\t{denominator // common}",
    ]


def _conversion(name, numerator, denominator):
    shift = _fmuls(32, numerator, denominator)
    return [
        f"#define {name}_MUL32\tU64_C(0x{_fmul(shift, numerator, denominator):X})",
        f"#define {name}_ADJ32\tU64_C(0x{_fadj(shift, numerator, denominator):X})",
        f"#define {name}_SHR32\t{shift}",
    ]


def generate(hz):
    if hz < 2:
        raise ValueError("HZ must be at least 2")
    lines = [
        "/* Automatically generated by tools/ipod6g_android/generate_timeconst.py */",
        f"/* Time conversion constants for HZ == {hz} */",
        "",
        "#ifndef KERNEL_TIMECONST_H",
        "#define KERNEL_TIMECONST_H",
        "",
        "#include <linux/param.h>",
        "#include <linux/types.h>",
        "",
        f"#if HZ != {hz}",
        '#error "include/generated/timeconst.h has the wrong HZ value!"',
        "#endif",
        "",
        *_conversion("HZ_TO_MSEC", 1000, hz),
        *_conversion("MSEC_TO_HZ", hz, 1000),
        *_ratio("HZ_TO_MSEC", 1000, hz),
        *_ratio("MSEC_TO_HZ", hz, 1000),
        "",
        *_conversion("HZ_TO_USEC", 1_000_000, hz),
        *_conversion("USEC_TO_HZ", hz, 1_000_000),
        *_ratio("HZ_TO_USEC", 1_000_000, hz),
        *_ratio("USEC_TO_HZ", hz, 1_000_000),
        *_ratio("HZ_TO_NSEC", 1_000_000_000, hz),
        *_ratio("NSEC_TO_HZ", hz, 1_000_000_000),
        "",
        "#endif /* KERNEL_TIMECONST_H */",
    ]
    return "\n".join(lines) + "\n"


def main(argv=None):
    arguments = list(sys.argv[1:] if argv is None else argv)
    if len(arguments) != 1:
        print("usage: generate_timeconst.py HZ", file=sys.stderr)
        return 2
    try:
        hz = int(arguments[0])
        sys.stdout.write(generate(hz))
    except ValueError as error:
        print(error, file=sys.stderr)
        return 2
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
