//AUTOGENERATED FILE FROM png2asset
// Conversion args: /scott_stinks_a.png -c /scott_stinks_a_map.c -map -noflip -b 255

#ifndef METASPRITE_scott_stinks_a_map_H
#define METASPRITE_scott_stinks_a_map_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define scott_stinks_a_map_TILE_ORIGIN 0
#define scott_stinks_a_map_TILE_W 8
#define scott_stinks_a_map_TILE_H 8
#define scott_stinks_a_map_WIDTH 160
#define scott_stinks_a_map_HEIGHT 144
#define scott_stinks_a_map_TILE_COUNT 64
#define scott_stinks_a_map_PALETTE_COUNT 1
#define scott_stinks_a_map_COLORS_PER_PALETTE 4
#define scott_stinks_a_map_TOTAL_COLORS 4
#define scott_stinks_a_map_MAP_ATTRIBUTES 0
extern const unsigned char scott_stinks_a_map_map[360];
#define scott_stinks_a_map_map_attributes scott_stinks_a_map_map

BANKREF_EXTERN(scott_stinks_a_map)

extern const palette_color_t scott_stinks_a_map_palettes[4];
extern const uint8_t scott_stinks_a_map_tiles[1024];

#endif
