#define BMPHEIGHT_minishcap_room_links_house_smith 160
#define BMPWIDTH_minishcap_room_links_house_smith 240
extern const unsigned char minishcap_room_links_house_smith[];
extern const struct bitmap bm_minishcap_room_links_house_smith;
