#ifndef ROCKPOD_NOTIFICATION_H
#define ROCKPOD_NOTIFICATION_H

#include <stdint.h>

#define NOTIFICATION_TITLE_SIZE 40
#define NOTIFICATION_BODY_SIZE 88
#define NOTIFICATION_ROUTE_SIZE 80

enum notification_source
{
    NOTIFICATION_SOURCE_ACHIEVEMENTS = 0,
    NOTIFICATION_SOURCE_SITEKICK,
    NOTIFICATION_SOURCE_SYSTEM,
    NOTIFICATION_SOURCE_MUSIC,
    NOTIFICATION_SOURCE_LIVETV,
    NOTIFICATION_SOURCE_WEATHER,
    NOTIFICATION_SOURCE_BATTERY,
    NOTIFICATION_SOURCE_STORAGE,
    NOTIFICATION_SOURCE_MSN,
    NOTIFICATION_SOURCE_COUNT
};

enum notification_kind
{
    NOTIFICATION_ACHIEVEMENT_UNLOCKED = 0,
    NOTIFICATION_SITEKICK_DUMP_READY,
    NOTIFICATION_SITEKICK_SHOP_READY,
    NOTIFICATION_SITEKICK_CHIP_ACQUIRED,
    NOTIFICATION_SITEKICK_INBOX_APPLIED,
    NOTIFICATION_MUSIC_NOW_PLAYING,
    NOTIFICATION_MUSIC_PAUSED,
    NOTIFICATION_MUSIC_RESUMED,
    NOTIFICATION_MUSIC_STOPPED,
    NOTIFICATION_MUSIC_QUEUE_FINISHED,
    NOTIFICATION_LIVETV_SHOW_REMINDER,
    NOTIFICATION_WEATHER_SYNC_MISSING,
    NOTIFICATION_WEATHER_SYNC_STALE,
    NOTIFICATION_WEATHER_SYNC_EXPIRED,
    NOTIFICATION_BATTERY_LOW,
    NOTIFICATION_BATTERY_CRITICAL,
    NOTIFICATION_STORAGE_LOW,
    NOTIFICATION_STORAGE_CRITICAL,
    NOTIFICATION_SYSTEM_TEST,
    NOTIFICATION_WEATHER_SYNCED,
    NOTIFICATION_SYSTEM_IPHONE_TETHER,
    NOTIFICATION_MUSIC_NEW_RELEASE,
    NOTIFICATION_MUSIC_CONCERT_ALERT,
    NOTIFICATION_SYSTEM_TIMER_DUE,
    NOTIFICATION_SYSTEM_ALARM_DUE,
    NOTIFICATION_MSN_MESSAGE
};

struct notification_request
{
    unsigned source;
    unsigned kind;
    unsigned priority;
    uint32_t stable_id;
    long timestamp;
    char title[NOTIFICATION_TITLE_SIZE];
    char body[NOTIFICATION_BODY_SIZE];
    char route[NOTIFICATION_ROUTE_SIZE];
};

#endif
