#!/usr/bin/env python3
import json
import pathlib
import sys


def c_string(value: str) -> str:
    value = value.replace("\\", "\\\\").replace('"', '\\"')
    value = value.replace("\n", "\\n")
    return f'"{value}"'


def main() -> int:
    if len(sys.argv) != 4:
        print(
            "usage: gen_cdogs_campaign.py <campaign.json> <missions.json> <output.h>",
            file=sys.stderr,
        )
        return 1

    campaign_path = pathlib.Path(sys.argv[1])
    missions_path = pathlib.Path(sys.argv[2])
    output_path = pathlib.Path(sys.argv[3])

    campaign = json.loads(campaign_path.read_text())
    missions = json.loads(missions_path.read_text())["Missions"]

    lines = []
    lines.append("/* Auto-generated by tools/gen_cdogs_campaign.py */")
    lines.append("#ifndef CDOGS_TERROR_CAMPAIGN_H")
    lines.append("#define CDOGS_TERROR_CAMPAIGN_H")
    lines.append("")
    lines.append("struct cdogs_mission_data")
    lines.append("{")
    lines.append("    const char *title;")
    lines.append("    const char *description;")
    lines.append("    const char *objective_type;")
    lines.append("    const char *objective;")
    lines.append("    int objective_count;")
    lines.append("    int objective_required;")
    lines.append("    int width;")
    lines.append("    int height;")
    lines.append("    int enemy_density;")
    lines.append("    const char *weapon_a;")
    lines.append("    const char *weapon_b;")
    lines.append("    const char *weapon_c;")
    lines.append("    int enemy_count;")
    lines.append("    int enemy_ids[10];")
    lines.append("    int special_count;")
    lines.append("    int special_ids[8];")
    lines.append("};")
    lines.append("")
    lines.append(
        f"static const char *const cdogs_campaign_title = {c_string(campaign['Title'])};"
    )
    lines.append(
        f"static const char *const cdogs_campaign_author = {c_string(campaign['Author'])};"
    )
    lines.append(
        "static const char *const cdogs_campaign_description = "
        f"{c_string(campaign['Description'])};"
    )
    lines.append(
        f"static const int cdogs_campaign_mission_count = {len(missions)};"
    )
    lines.append("")
    lines.append("static const struct cdogs_mission_data cdogs_campaign_missions[] =")
    lines.append("{")
    for mission in missions:
        objective = mission["Objectives"][0]
        weapons = mission.get("Weapons", [])
        enemies = mission.get("Enemies", [])
        special = mission.get("SpecialChars", [])
        weapon_a = weapons[0] if len(weapons) > 0 else ""
        weapon_b = weapons[1] if len(weapons) > 1 else ""
        weapon_c = weapons[2] if len(weapons) > 2 else ""
        enemy_ids = enemies[:10] + [0] * max(0, 10 - len(enemies[:10]))
        special_ids = special[:8] + [0] * max(0, 8 - len(special[:8]))
        lines.append("    {")
        lines.append(f"        {c_string(mission['Title'])},")
        lines.append(f"        {c_string(mission['Description'])},")
        lines.append(f"        {c_string(objective['Type'])},")
        lines.append(f"        {c_string(objective['Description'])},")
        lines.append(f"        {objective['Count']},")
        lines.append(f"        {objective['Required']},")
        lines.append(f"        {mission['Width']},")
        lines.append(f"        {mission['Height']},")
        lines.append(f"        {mission.get('EnemyDensity', 0)},")
        lines.append(f"        {c_string(weapon_a)},")
        lines.append(f"        {c_string(weapon_b)},")
        lines.append(f"        {c_string(weapon_c)},")
        lines.append(f"        {len(enemies[:10])},")
        lines.append(
            "        { " + ", ".join(str(v) for v in enemy_ids) + " },"
        )
        lines.append(f"        {len(special[:8])},")
        lines.append(
            "        { " + ", ".join(str(v) for v in special_ids) + " },"
        )
        lines.append("    },")
    lines.append("};")
    lines.append("")
    lines.append("#endif")
    lines.append("")

    output_path.write_text("\n".join(lines))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
