#!/usr/bin/env python3
"""Generate the fixed-point Web Mercator latitude table used by Maps."""

from __future__ import annotations

import math
from pathlib import Path


MIN_LAT_E6 = -85_000_000
MAX_LAT_E6 = 85_000_000
STEP_E6 = 100_000
Q30 = 1 << 30
OUTPUT = Path(__file__).resolve().parents[1] / "apps/plugins/nb_maps_mercator.h"


def mercator_y_q30(latitude_e6: int) -> int:
    latitude = math.radians(latitude_e6 / 1_000_000)
    normalized = (1.0 - math.asinh(math.tan(latitude)) / math.pi) / 2.0
    return round(normalized * Q30)


def main() -> int:
    values = [
        mercator_y_q30(latitude)
        for latitude in range(MIN_LAT_E6, MAX_LAT_E6 + 1, STEP_E6)
    ]
    lines = [
        "/* Generated by tools/generate_nb_maps_mercator.py. */",
        "#define MAR_MERCATOR_MIN_LAT_E6 (-85000000)",
        "#define MAR_MERCATOR_MAX_LAT_E6 85000000",
        "#define MAR_MERCATOR_STEP_E6 100000",
        "#define MAR_MERCATOR_Q30 (1ULL << 30)",
        "static const uint32_t mar_mercator_y_q30[] = {",
    ]
    for offset in range(0, len(values), 8):
        chunk = values[offset:offset + 8]
        lines.append("    " + ", ".join(f"{value}u" for value in chunk) + ",")
    lines.extend(("};", ""))
    OUTPUT.write_text("\n".join(lines), encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
