#!/usr/bin/env python3
"""Rasterize pinned Lucide weather geometry into bounded 4-bit ROM coverage."""
from pathlib import Path
from io import BytesIO
import subprocess
from PIL import Image
root=Path(__file__).resolve().parents[1]
source=root/'assets/ambient-clock/weather'
names=['sun','moon','cloud-sun','cloud-moon','cloud','cloud-drizzle',
       'cloud-rain','cloud-snow','cloud-fog','cloud-lightning']
lines=['/* Generated by tools/generate_ambient_icons.py.',
       ' * Lucide, ISC license: assets/ambient-clock/weather/LICENSE. */',
       'static const unsigned char ambient_icon_bits[10][288] = {']
bounds=[]
for name in names:
 svg=(source/(name+'.svg')).read_bytes().replace(b'currentColor',b'#ffffff')
 png=subprocess.run(['rsvg-convert','-w','128','-h','128'],input=svg,
                    capture_output=True,check=True).stdout
 im=Image.open(BytesIO(png)).convert('RGBA').resize((24,24),Image.Resampling.LANCZOS)
 box=im.getchannel('A').point(lambda v: 255 if v>=9 else 0).getbbox()
 bounds.extend([box[0],box[2]])
 alpha=list(im.getchannel('A').getdata());data=[((alpha[i]+8)//17<<4)|((alpha[i+1]+8)//17) for i in range(0,len(alpha),2)]
 lines.append('    { /* '+name+' */')
 lines.extend('        '+','.join(map(str,data[i:i+24]))+',' for i in range(0,len(data),24));lines.append('    },')
lines.append('};')
lines.append('static const unsigned char ambient_icon_bounds[] = {'+','.join(map(str,bounds))+'};')
(root/'apps/gui/ambient_clock_icons.h').write_text('\n'.join(lines)+'\n')
