#!/usr/bin/env python3
"""Generate original Classic-style Quick Settings glyphs (no Apple assets)."""
from pathlib import Path
import math

ROOT = Path(__file__).resolve().parents[1]
names = ['volume', 'brightness', 'dark_mode', 'shuffle', 'repeat', 'accent',
         'surface', 'density', 'font', 'extras_pane', 'haptics', 'hold',
         'usb_connection', 'kokkia', 'composite_out', 'tv_backlight',
         'cache_memory', 'screensaver']


def glyph(name):
    bits = [[0] * 14 for _ in range(14)]
    def dot(x, y, value=1):
        if 0 <= x < 14 and 0 <= y < 14:
            bits[y][x] = value
    def line(x0, y0, x1, y1):
        steps = max(abs(x1-x0), abs(y1-y0), 1)
        for i in range(steps+1):
            dot(round(x0+(x1-x0)*i/steps), round(y0+(y1-y0)*i/steps))
    def rect(x, y, w, h):
        line(x,y,x+w-1,y); line(x,y+h-1,x+w-1,y+h-1)
        line(x,y,x,y+h-1); line(x+w-1,y,x+w-1,y+h-1)
    def circle(x, y, r, lo=0, hi=360):
        for a in range(lo,hi+1,3):
            dot(round(x+r*math.cos(math.radians(a))),
                round(y+r*math.sin(math.radians(a))))
    def arrow(x,y,d):
        line(x,y,x-2*d,y-2); line(x,y,x-2*d,y+2)
    if name == 'volume':
        rect(0,5,3,4); line(3,5,6,2); line(6,2,6,11); line(6,11,3,8)
        circle(6,6,4,315,405); circle(6,6,7,315,405)
    elif name == 'brightness':
        circle(6,6,3)
        for a in range(0,360,45):
            line(round(6+5*math.cos(math.radians(a))),round(6+5*math.sin(math.radians(a))),round(6+6*math.cos(math.radians(a))),round(6+6*math.sin(math.radians(a))))
    elif name == 'dark_mode':
        for y in range(14):
            for x in range(14):
                if (x-6)**2+(y-6)**2 <= 30 and (x-9)**2+(y-3)**2 > 22:
                    dot(x,y)
    elif name == 'shuffle':
        line(0,3,3,3);line(3,3,9,10);line(9,10,12,10);arrow(12,10,1)
        line(0,10,3,10);line(3,10,5,8);line(8,5,10,3);line(10,3,12,3);arrow(12,3,1)
    elif name == 'repeat':
        line(1,7,1,4);line(1,4,11,4);arrow(11,4,1)
        line(12,7,12,10);line(12,10,2,10);arrow(2,10,-1)
    elif name == 'accent':
        circle(6,6,5);rect(3,3,2,2);rect(8,3,2,2);rect(2,7,2,2)
        line(6,11,11,6);line(7,12,12,7)
    elif name == 'surface':
        rect(1,1,10,9);line(2,3,9,3);rect(4,5,9,8);line(5,7,11,7)
    elif name == 'density':
        for y in (2,6,10):
            rect(1,y,2,2);line(5,y,12,y);line(5,y+1,12,y+1)
    elif name == 'font':
        line(1,11,5,1);line(5,1,9,11);line(3,7,7,7)
        line(0,11,3,11);line(7,11,10,11)
    elif name == 'extras_pane':
        rect(0,1,14,12);line(7,2,7,11)
        for y in (4,7,10): line(2,y,5,y)
        circle(10,6,2);line(10,6,10,4)
    elif name == 'haptics':
        rect(5,2,4,10);line(2,3,1,5);line(1,5,2,7);line(2,7,1,9)
        line(11,3,12,5);line(12,5,11,7);line(11,7,12,9)
    elif name == 'hold':
        rect(2,6,10,7);circle(6,5,3,180,360);line(3,5,3,6);line(9,5,9,6)
        dot(6,8);line(6,9,6,10)
    elif name == 'usb_connection':
        line(6,12,6,1);line(6,1,4,3);line(6,1,8,3);circle(6,12,1)
        line(6,9,2,6);line(2,6,2,4);circle(2,3,1)
        line(6,7,11,5);line(11,5,11,3);rect(10,1,3,3)
    elif name == 'kokkia':
        line(6,0,6,13);line(6,0,11,4);line(11,4,2,11)
        line(2,2,11,9);line(11,9,6,13)
    elif name == 'composite_out':
        rect(0,1,13,9);line(1,3,11,3);line(6,10,6,12);line(3,13,9,13)
    elif name == 'tv_backlight':
        rect(3,0,8,14);rect(4,1,6,6);line(4,6,9,1);circle(6,10,2);dot(6,10)
    elif name == 'cache_memory':
        rect(3,3,8,8);rect(5,5,4,4)
        for i in (4,7,10):
            line(i,0,i,2);line(i,11,i,13);line(0,i,2,i);line(11,i,13,i)
    elif name == 'screensaver':
        circle(5,5,5);line(5,2,5,5);line(5,5,7,5)
        # Battery overlay, with clear separation from the clock.
        for y in range(8,14):
            for x in range(6,14): dot(x,y,0)
        rect(6,9,7,5);line(13,10,13,12);line(8,11,10,11)
    assert sum(map(sum,bits)) > 15, name
    return [sum(value << x for x,value in enumerate(row)) for row in bits]


def generate():
    rows = [glyph(n) for n in names]
    text = '''/* Generated by tools/generate_ipodjs_qs_icons.py.
 * Original Classic-style symbols; no extracted Apple artwork.
 * 18 glyphs x 14 rows x 2 bytes = 504 bytes of read-only data.
 */
#ifndef IPODJS_QS_ICONS_H
#define IPODJS_QS_ICONS_H
#include <stdint.h>
enum ipodjs_qs_glyph {
'''
    text += ''.join('    IPODJS_QS_GLYPH_'+n.upper()+',\n' for n in names)
    text += '    IPODJS_QS_GLYPH_COUNT\n};\n\n'
    text += 'static const uint16_t ipodjs_qs_glyphs[IPODJS_QS_GLYPH_COUNT][14] = {\n'
    for n,r in zip(names,rows):
        text+='    /* '+n+' */\n    { '+', '.join(f'0x{v:04x}' for v in r[:7])+',\n      '+', '.join(f'0x{v:04x}' for v in r[7:])+' },\n'
    text+='};\n#endif\n'
    (ROOT/'apps/gui/ipodjs_qs_icons.h').write_text(text)

if __name__ == '__main__':
    generate()
