#!/usr/bin/env python3
"""Generate bounded 4-bit clock glyph atlases from the bundled OFL font."""
from pathlib import Path
root = Path(__file__).resolve().parents[1]
from PIL import Image, ImageDraw, ImageFont
fontpath=root/'assets/ambient-clock/AdwaitaSans-Regular.ttf'
lines=['/* Generated by tools/generate_ambient_font.py. Adwaita Sans (Inter-derived), SIL OFL.',
       ' * See assets/ambient-clock/OFL.txt. No runtime font allocation. */']
for name,size,chars in [('digits',96,'0123456789:'),('text',14,''.join(chr(i) for i in range(32,127))+'°')]:
 f=ImageFont.truetype(str(fontpath),size)
 f.set_variation_by_axes([32 if name=='digits' else 14, 520 if name=='digits' else 450])
 width=60 if name=='digits' else 16;height=100 if name=='digits' else 20
 data=[];adv=[];bounds=[]
 for ch in chars:
  im=Image.new('L',(width,height));d=ImageDraw.Draw(im);a=round(f.getlength(ch));adv.append(min(width,a))
  d.text((0,0),ch,font=f,fill=255,stroke_width=0)
  bbox=im.point(lambda v: 255 if v>=9 else 0).getbbox()
  bounds.extend([bbox[0],bbox[2]] if bbox else [0,0])
  pix=list(im.getdata());data.extend(((pix[i]+8)//17<<4)|((pix[i+1]+8)//17) for i in range(0,len(pix),2))
 lines.append(f'static const unsigned char ambient_{name}_width[] = {{'+','.join(map(str,adv))+'};')
 lines.append(f'static const unsigned char ambient_{name}_bounds[] = {{'+','.join(map(str,bounds))+'};')
 lines.append(f'static const unsigned char ambient_{name}_bits[] = {{')
 lines.extend('    '+','.join(map(str,data[i:i+24]))+',' for i in range(0,len(data),24));lines.append('};')
(root/'apps/gui/ambient_clock_font.h').write_text('\n'.join(lines)+'\n')
