#!/usr/bin/env python3
"""Pack the existing Classic boot bitmap as RGB565 runs for the bootloader."""
from itertools import groupby
from pathlib import Path
from PIL import Image

root = Path(__file__).resolve().parent.parent
source = root / "apps/bitmaps/native/rockboxlogo.320x98x16.bmp"
image = Image.open(source).convert("RGB")
assert image.size == (320, 240)
pixels = [(r >> 3) << 11 | (g >> 2) << 5 | b >> 3
          for r, g, b in image.getdata()]
lines = ["/* Generated by tools/generate_quiet_boot_logo.py. */",
         "static const uint16_t quiet_boot_logo[][2] = {"]
for color, group in groupby(pixels):
    count = sum(1 for _ in group)
    while count:
        run = min(count, 65535)
        lines.append(f"    {{ {run}, 0x{color:04x} }},")
        count -= run
lines.append("};")
(root / "bootloader/quiet_boot_logo.h").write_text("\n".join(lines) + "\n")
