#!/usr/bin/env python3
"""Pack the complete official Twemoji PNG set for Rockbox's native renderer."""

from __future__ import annotations

import argparse
import math
from collections import defaultdict
from pathlib import Path

from PIL import Image


CELL = 14
COLUMNS = 16
COLORKEY = (255, 0, 255)


def _sequence(path: Path) -> tuple[int, ...]:
    # Variation selector-16 is presentation metadata, not identity. Removing it
    # lets both valid Unicode spellings match the same official Twemoji asset.
    return tuple(
        int(part, 16) for part in path.stem.split("-") if part != "fe0f"
    )


def _write_data_header(path: Path, records: list[tuple[tuple[int, ...], int]]):
    codepoints: list[int] = []
    entries = []
    buckets: dict[int, list[int]] = defaultdict(list)
    for sequence, cell in sorted(records, key=lambda item: (item[0][0], -len(item[0]), item[0])):
        offset = len(codepoints)
        codepoints.extend(sequence)
        entry_index = len(entries)
        entries.append((offset, cell, len(sequence)))
        buckets[sequence[0]].append(entry_index)

    lines = [
        "/* Generated by tools/generate_twemoji_atlas.py; do not edit. */",
        "#ifndef ROCKBOX_SOCIAL_EMOJI_DATA_H",
        "#define ROCKBOX_SOCIAL_EMOJI_DATA_H",
        "",
        "struct social_emoji_entry_data {",
        "    unsigned short offset;",
        "    unsigned short cell;",
        "    unsigned char length;",
        "};",
        "",
        "struct social_emoji_bucket_data {",
        "    unsigned int codepoint;",
        "    unsigned short start;",
        "    unsigned short count;",
        "};",
        "",
        "static const unsigned int social_emoji_codepoints[] = {",
    ]
    for start in range(0, len(codepoints), 10):
        chunk = codepoints[start : start + 10]
        lines.append("    " + ", ".join(f"0x{value:x}" for value in chunk) + ",")
    lines.extend(["};", "", "static const struct social_emoji_entry_data social_emoji_entries[] = {"])
    for offset, cell, length in entries:
        lines.append(f"    {{{offset}, {cell}, {length}}},")
    lines.extend(["};", "", "static const struct social_emoji_bucket_data social_emoji_buckets[] = {"])
    for codepoint in sorted(buckets):
        indexes = buckets[codepoint]
        lines.append(f"    {{0x{codepoint:x}, {indexes[0]}, {len(indexes)}}},")
    lines.extend(
        [
            "};",
            "",
            f"#define SOCIAL_EMOJI_BUCKET_COUNT {len(buckets)}",
            f"#define SOCIAL_EMOJI_ASSET_COUNT {len(records)}",
            "",
            "#endif /* ROCKBOX_SOCIAL_EMOJI_DATA_H */",
            "",
        ]
    )
    path.write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("source", type=Path, help="Twemoji assets/72x72 directory")
    parser.add_argument("--repo", type=Path, default=Path(__file__).resolve().parents[1])
    args = parser.parse_args()
    sources = sorted(args.source.glob("*.png"), key=lambda path: _sequence(path))
    if not sources:
        raise SystemExit(f"No Twemoji PNG files found in {args.source}")

    sequences = [_sequence(path) for path in sources]
    if len(sequences) != len(set(sequences)):
        raise SystemExit("Variation-selector normalization produced duplicate sequences")
    if len(sources) > 65535 or sum(map(len, sequences)) > 65535:
        raise SystemExit("Twemoji catalog exceeds the compact 16-bit index format")

    rows = math.ceil(len(sources) / COLUMNS)
    atlas = Image.new("RGB", (CELL * COLUMNS, CELL * rows), COLORKEY)
    records = []
    for cell, (source, sequence) in enumerate(zip(sources, sequences)):
        with Image.open(source) as image:
            emoji = image.convert("RGBA").resize(
                (CELL, CELL), Image.Resampling.LANCZOS
            )
        # Rockbox's bitmap colorkey is exact magenta. Keep official RGB values
        # for every visible antialiased pixel and key only fully transparent pixels.
        pixels = Image.new("RGB", emoji.size, COLORKEY)
        pixels.putdata(
            [rgb[:3] if rgb[3] else COLORKEY for rgb in emoji.getdata()]
        )
        x = (cell % COLUMNS) * CELL
        y = (cell // COLUMNS) * CELL
        atlas.paste(pixels, (x, y))
        records.append((sequence, cell))

    atlas_path = (
        args.repo
        / "apps/bitmaps/native"
        / f"twemoji_atlas.{atlas.width}x{atlas.height}x16.bmp"
    )
    atlas.save(atlas_path, "BMP")
    _write_data_header(
        args.repo / "firmware/export/social_emoji_data.h", records
    )
    print(
        f"Packed {len(records)} official Twemoji assets into "
        f"{atlas.width}x{atlas.height}: {atlas_path}"
    )


if __name__ == "__main__":
    main()
