#!/usr/bin/env python3
"""Pack preserved Microsoft MSN emoticons; retain every original frame."""
import hashlib
import json
import sys
from pathlib import Path
from PIL import Image, ImageOps, ImageSequence
from prepare_msn_assets import bitmap
ROOT=Path(__file__).resolve().parents[1]
sys.path.insert(0,str(ROOT/'rockpod'))
from services.msn_app import MsnAppService
SOURCE=ROOT/'assets/ipodjs/sources/msn/emoticons'
DEST=ROOT/'assets/ipodjs/rockbox/msn'

def main():
    provenance=json.loads((SOURCE/'PROVENANCE.json').read_text())
    for name,digest in provenance['files'].items():
        assert hashlib.sha256((SOURCE/name).read_bytes()).hexdigest()==digest,name
    records=json.loads((SOURCE/'catalog.json').read_text());frames=[];delays=[];rows=[]
    (DEST/'gifs').mkdir(parents=True,exist_ok=True)
    for r in records:
        first=len(frames)
        with Image.open(SOURCE/r['file']) as im:
            for f in ImageSequence.Iterator(im):
                cell=Image.new('RGBA',(19,19));frame=ImageOps.contain(f.convert('RGBA'),(19,19),Image.Resampling.LANCZOS)
                cell.alpha_composite(frame,((19-frame.width)//2,(19-frame.height)//2));frames.append(cell)
                delays.append(max(20,round(f.info.get('duration',100))))
        count=len(frames)-first
        if count>1:
            gif=SOURCE/(r['id']+'.gif')
            MsnAppService._animation(gif,DEST/'gifs'/(r['id']+'.mga'))
            (DEST/'gifs'/(r['id']+'.gif')).write_bytes(gif.read_bytes())
        rows.append((r,first,count,sum(delays[first:])))
    columns=16;rows_count=(len(frames)+columns-1)//columns
    atlas=Image.new('RGBA',(columns*19,rows_count*19))
    for i,frame in enumerate(frames):atlas.alpha_composite(frame,((i%columns)*19,(i//columns)*19))
    bitmap(atlas,DEST/'emoticons.bmp')
    def c(s):return json.dumps(s,ensure_ascii=False)
    header=['/* Original Microsoft MSN resources; generated by tools/prepare_msn_emoticons.py. */',
        '#define MSN_EMOTE_COUNT '+str(len(rows)),f'#define MSN_EMOTE_ATLAS_W {atlas.width}',f'#define MSN_EMOTE_ATLAS_H {atlas.height}',
        'struct msn_emote { const char *name, *shortcut, *slug; unsigned short first, frames, duration; };',
        'static const struct msn_emote msn_emotes[] = {']
    for r,first,count,total in rows:header.append('    { '+', '.join([c(r['name']),c(r['shortcut']),c(r['id']),str(first),str(count),str(total)])+' },')
    header+=['};','static const unsigned short msn_emote_delays[] = {', '    '+','.join(map(str,delays)), '};','']
    (ROOT/'apps/plugins/msn_emoticons.h').write_text('\n'.join(header))
    print(f'{len(rows)} emoticons, {len(frames)} original frames, {sum(n>1 for _,_,n,_ in rows)} animations; atlas {atlas.size}')
if __name__=='__main__':main()
