#!/usr/bin/env python3
"""Crop original DIRECTV receiver chrome; never generate replacement artwork."""
from pathlib import Path
import hashlib
from collections import Counter
from PIL import Image
root = Path(__file__).resolve().parents[1]
source = root / 'assets/ipodjs/sources/directv/guide/d12-guide-original.png'
im = Image.open(source).convert('RGB')
# Preserve the complete original 398 x 58 header, logo and guide wordmark.
# Remove only the sample programme title and preview using clean white
# background slices from this same screenshot; live content fills those areas.
header = im.crop((0, 0, 398, 58))
white = im.crop((0, 28, 10, 36))
header.paste(white.resize((137, 21)), (77, 35))
header.paste(white.resize((112, 58)), (263, 0))
parts = [('header', header)]
code = ['/* Original DIRECTV D12 receiver artwork; copyright DIRECTV.',
        ' * Generated by tools/prepare_tv_directv_assets.py.',
        ' * See assets/ipodjs/sources/directv/guide/SOURCES.md. */']
for name, image in parts:
    size = image.size
    pixels = []
    for r, g, b in image.getdata():
        p = ((r >> 3) << 11) | ((g >> 2) << 5) | (b >> 3)
        # Original white backing becomes transparent; retain the source ink.
        alpha = 0 if name != 'header' and min(r, g, b) > 245 else 255
        pixels.extend((p & 255, p >> 8, alpha))
    symbol = 'tv_directv_' + name
    code.append('static const unsigned char ' + symbol + '_pixels[] = {\n' +
                ',\n'.join(','.join(map(str,pixels[i:i+24]))
                            for i in range(0,len(pixels),24)) + '\n};')
    code.append('static const struct ipodjs_retailos_image ' + symbol +
                ' = {%d,%d,%s_pixels};' % (*size,symbol))
# Dominant foreground RGB565 values in reference text, excluding background.
# These are screenshot colors, not an assumed all-white/navy palette.
for role, box, dark in [
    ('TITLE', (82,37,211,53), True),
    ('METADATA', (83,61,151,72), True),
    ('BODY', (18,80,254,125), False),
    ('ROW', (85,172,155,186), False),
    ('SELECTED', (82,232,165,245), True),
    ('CHANNEL', (22,172,72,186), False),
]:
    colors = Counter()
    for r,g,b in im.crop(box).getdata():
        if (r+g+b<300) if dark else (min(r,g,b)>150):
            colors[((r>>3)<<11)|((g>>2)<<5)|(b>>3)] += 1
    color = colors.most_common(1)[0][0]
    code.append('#define TV_DIRECTV_%s 0x%04xu' % (role,color))
(root/'apps/gui/tv_directv_assets.h').write_text('\n'.join(code)+'\n')
print('Original screenshot SHA256:', hashlib.sha256(source.read_bytes()).hexdigest())
