#!/usr/bin/env python3
"""Generate player limits and bind installed capabilities to the actual image."""
import argparse, hashlib, json
from pathlib import Path
ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT/'rockpod/services/data/video-capabilities-v1.json'
HEADER = ROOT/'apps/video_capabilities.h'

def digest(data):
    return hashlib.sha256(json.dumps(data, sort_keys=True, separators=(',', ':')).encode()).hexdigest()

def header(contract):
    lines = ['/* Generated by tools/video_capabilities.py. Edit the JSON source. */',
             '#ifndef VIDEO_CAPABILITIES_H', '#define VIDEO_CAPABILITIES_H',
             '#define VIDEO_CAPABILITY_SCHEMA 1',
             f'#define VIDEO_CAPABILITY_SHA256 "{digest(contract)}"']
    lines += [f'#define VIDEO_CAP_{k.upper()} {v}' for k,v in contract['limits'].items()]
    return '\n'.join(lines + ['#endif', ''])

def main():
    parser=argparse.ArgumentParser()
    parser.add_argument('--check',action='store_true')
    parser.add_argument('--generate',action='store_true')
    parser.add_argument('--info',type=Path)
    parser.add_argument('--firmware',type=Path)
    parser.add_argument('--output',type=Path)
    args=parser.parse_args(); contract=json.loads(SOURCE.read_text())
    expected=header(contract)
    if args.generate: HEADER.write_text(expected)
    if args.check or args.output:
        if HEADER.read_text()!=expected: raise SystemExit('Video capability header is stale; regenerate before building')
    if args.output:
        info=dict(line.split(':',1) for line in args.info.read_text().splitlines() if ':' in line)
        target=info.get('Target','').strip()
        base=contract['aliases'].get(target,target)
        if base not in contract['targets']: raise SystemExit('Unsupported capability target: '+target)
        firmware_hash=hashlib.sha256(args.firmware.read_bytes()).hexdigest()
        record={'schema':1,'contract_sha256':digest(contract),'build':info['Version'].strip(),
                'target':target,'firmware_sha256':firmware_hash,'limits':contract['limits'],
                'capabilities':contract['targets'][base], 'qualification':contract['qualification']}
        args.output.write_text(json.dumps(record,indent=2)+'\n')
if __name__=='__main__': main()
