port                            "6600"
music_directory                 "/mnt"
playlist_directory              "/opt/Base/MPD/Playlists"
log_file                        "/opt/Base/MPD/Misc/mpd.log"
error_file                      "/opt/Base/MPD/Misc/mpd.error"
filesystem_charset              "ISO-8859-1"
db_file                         "/opt/Base/MPD/Data/mpd.db"
state_file                      "/opt/Base/MPD/Data/mpdstate"
mixer_control                   "PCM"
audio_output {
        type                    "oss"
        name                    "oss"
}
