#!/bin/sh
set -e

while [ $# -gt 0 ]; do
    case "$1" in
        -q|-0|-1|-2|-3|-4|-5|-6|-7|-8|-9|-r|-r0|-r1|-r2|-r3|-r4|-r5|-r6|-r7|-r8|-r9)
            shift
            ;;
        --)
            shift
            break
            ;;
        -*)
            shift
            ;;
        *)
            break
            ;;
    esac
done

archive=$1
shift

exec 7z a -tzip -bd -bso0 -bsp0 "$archive" "$@"
